("/home/acl2/books/misc/sticky-disable.lisp::LIST-OF-ADD-STICKY-CALLS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ENDP) (CONS) NIL NIL NIL)
 ((FNS) NIL (SB-INT:QUASIQUOTE) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL NIL)
 ((FLG) NIL (CDR) (ADD-STICKY) NIL NIL NIL)
 ((,(CAR FNS) ,FLG FNS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/sticky-disable.lisp::GET-STICKY-ENABLES-1"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL ((ENDP ALIST) (CDAR ALIST) T) NIL NIL NIL NIL)
 ((ACC) NIL NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL)
 ((ACC) NIL (CDR CDR) (CONS) NIL NIL NIL)
 ((ALIST ALIST ACC) NIL (CAAR) NIL NIL NIL NIL)
 ((ALIST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/sticky-disable.lisp::GET-STICKY-DISABLES-1"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL ((ENDP ALIST) (CDAR ALIST) T) NIL NIL NIL NIL)
 ((ACC) NIL NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL)
 ((ACC) NIL (CDR CDR) (CONS) NIL NIL NIL)
 ((ALIST ACC ALIST) NIL (CAAR) NIL NIL NIL NIL)
 ((ALIST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/sticky-disable.lisp::GET-STICKY-ENABLES"
 (NIL NIL NIL (GET-STICKY-ENABLES-1) NIL NIL NIL)
 ((NIL) NIL NIL (TABLE-ALIST) NIL NIL NIL)
 ((WORLD) NIL (QUOTE) NIL NIL NIL NIL)
 ((STICKY-DISABLES) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/sticky-disable.lisp::GET-STICKY-DISABLES"
 (NIL NIL NIL (GET-STICKY-DISABLES-1) NIL NIL NIL)
 ((NIL) NIL NIL (TABLE-ALIST) NIL NIL NIL)
 ((WORLD) NIL (QUOTE) NIL NIL NIL NIL)
 ((STICKY-DISABLES) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
