("/home/acl2/books/std/system/invariant-risk.lisp::TBODY"
 (NIL NIL (FN) NIL NIL NIL NIL) ((WRLD) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/system/invariant-risk.lisp::INVARIANT-RISK-CALLEES1"
 (NIL NIL NIL NIL (BODY-FNS) NIL NIL) ((FN WRLD ACC) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/system/invariant-risk.lisp::INVARIANT-RISK-CALLEES"
 (NIL NIL (FN) NIL NIL NIL NIL) ((WRLD) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/system/invariant-risk.lisp::INVARIANT-RISK-CALL-PATH-REC"
 (NIL NIL NIL (FNS) NIL NIL NIL) ((EXCEPTIONS WRLD) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/system/invariant-risk.lisp::INVARIANT-RISK-CALL-PATH"
 (NIL NIL NIL (FN) NIL NIL NIL) ((EXCEPTIONS WRLD) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/system/invariant-risk.lisp::INVARIANT-RISK-CALL-PATH-ALIST"
 (NIL NIL NIL NIL (FNS) NIL NIL)
 ((EXCEPTIONS ALIST WRLD) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
