("/home/acl2/books/misc/eliminate-irrelevance-tests.lisp::REV1"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (CONSP) (MY-APP1) NIL NIL NIL)
 ((X) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (CONS) NIL NIL NIL)
 ((NIL) NIL (CDR CAR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/eliminate-irrelevance-tests.lisp::REV2"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (CONSP) (MY-APP2) NIL NIL NIL)
 ((X) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (CONS) NIL NIL NIL)
 ((NIL) NIL (CDR CAR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
