("/home/acl2/books/tools/equality-with-hons-copy.lisp::HONS-EQUAL!"
 (NIL NIL (X) NIL NIL NIL NIL) ((Y) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/equality-with-hons-copy.lisp::HONS-EQUAL!-ELIM"
 (NIL NIL NIL (COND) NIL NIL NIL)
 (NIL NIL ((AND (NVARIABLEP X) (EQ (FFN-SYMB X) 'HONS-EQUAL!)) T) NIL NIL NIL
  NIL)
 ((X) NIL NIL (COND) NIL NIL NIL)
 (NIL NIL ((HONS-EQUAL (HONS-COPY (FARGN X 1)) (HONS-COPY (FARGN X 2))) T) NIL
  NIL NIL NIL)
 ((*T*) NIL NIL (LIST) NIL NIL NIL) ((X) NIL (QUOTE) NIL NIL NIL NIL)
 ((HIDE) NIL NIL NIL NIL NIL NIL))
