("/home/acl2/books/rtl/rel11/support/util.lisp::SUB1-INDUCTION"
 (NIL NIL NIL NIL (IF) NIL NIL)
 ((N) NIL (ZP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL NIL)
 ((N) NIL (1-) NIL NIL NIL NIL) ((N) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/rtl/rel11/support/util.lisp::SPLIT-LIST"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL ((ENDP LST) (ENDP (CDR LST)) T) NIL NIL NIL NIL)
 (NIL NIL NIL (MV MV) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 ((LO HI HI) NIL (CDDR) (CONS CONS CONS) NIL NIL NIL)
 ((LO LST LO HI) NIL (CAR CAR CADR) NIL NIL NIL NIL)
 ((LST LST LST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/rtl/rel11/support/util.lisp::FAST-AND-FN"
 ((CONJUNCTS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
