("/home/acl2/books/misc/rtl-untranslate.lisp::RTL-UNTRANS-LOP"
 (NIL NIL NIL (COND) NIL NIL NIL)
 (NIL NIL ((AND (CONSP Y) (EQ (CAR Y) LOP) (EQUAL (CAR (LAST Y)) WIDTH)) T) NIL
  NIL NIL NIL)
 (NIL NIL NIL NIL (LIST*) (LIST) NIL)
 ((LOP X LOP X Y WIDTH) NIL (CDR) NIL NIL NIL NIL)
 ((Y) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/rtl-untranslate.lisp::SUM-CAT-SIZES"
 (NIL NIL NIL NIL (IF) NIL NIL) ((ACC) NIL (ENDP) NIL (IF) NIL NIL)
 ((LST NIL) NIL (ACL2-NUMBERP) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL NIL)
 (NIL NIL (CADR CDDR) (+) NIL NIL NIL)
 ((LST LST ACC) NIL (CADR) NIL NIL NIL NIL) ((LST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/rtl-untranslate.lisp::RTL-UNTRANS-CAT"
 (NIL NIL NIL (COND) NIL NIL NIL)
 (NIL NIL
  ((AND (CONSP Y) (EQ (CAR Y) 'CAT) (INTEGERP YSIZE)
        (EQL YSIZE (SUM-CAT-SIZES (CDR Y) 0)))
   T)
  NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL (LIST*) (LIST))
 ((X XSIZE X XSIZE Y YSIZE) NIL (QUOTE CDR QUOTE) NIL NIL NIL NIL)
 ((CAT Y CAT) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/rtl-untranslate.lisp::COND1-LENGTH"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((TERM) NIL (('IF1 & & Z) &) NIL NIL NIL NIL) (NIL (1) (1+) NIL NIL NIL NIL)
 (NIL NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL NIL)
 ((Z) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/rtl-untranslate.lisp::STR=-UP-TO"
 (NIL NIL NIL NIL (STR1) NIL NIL) ((STR2 I BOUND) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/rtl-untranslate.lisp::ALL-DOLLAR-SYMBS"
 ((ALIST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/rtl-untranslate.lisp::DOLLARFY"
 ((SYM) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/rtl-untranslate.lisp::DOLLAR-ALIST"
 (NIL NIL (SYMS) NIL NIL NIL NIL) ((ACC) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/rtl-untranslate.lisp::RTL-UNTRANSLATE"
 (NIL NIL NIL (LET) NIL NIL NIL)
 (((RTL-TBL (TABLE-ALIST 'RTL-TBL WRLD))) NIL NIL NIL NIL NIL NIL)
 ((TERM IFF-FLG WRLD) NIL (UNTRANS-TABLE CDR CDR UNTRANSLATE-PREPROCESS-FN) NIL
  NIL NIL NIL)
 ((WRLD WRLD) NIL NIL (ASSOC ASSOC) NIL NIL NIL)
 ((RTL-TBL RTL-TBL) NIL 'QUOTE NIL NIL NIL NIL)
 ((SIGS-BTREE LOPS-ALIST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/rtl-untranslate.lisp::RTL-UNTRANSLATE-LST"
 (NIL NIL NIL (LET) NIL NIL NIL)
 (((RTL-TBL (TABLE-ALIST 'RTL-TBL WRLD))) NIL NIL NIL NIL NIL NIL)
 ((LST IFF-FLG WRLD) NIL (UNTRANS-TABLE CDR CDR UNTRANSLATE-PREPROCESS-FN) NIL
  NIL NIL NIL)
 ((WRLD WRLD) NIL NIL (ASSOC-EQ ASSOC-EQ) NIL NIL NIL)
 ((RTL-TBL RTL-TBL) NIL 'QUOTE NIL NIL NIL NIL)
 ((SIGS-BTREE LOPS-ALIST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/rtl-untranslate.lisp::EXPAND-ADDRESS-CAT"
 (NIL NIL NIL NIL (CAR-ADDR) NIL NIL)
 ((RAW-TERM TERM WRLD) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/rtl-untranslate.lisp::EXPAND-ADDRESS-LXOR"
 (NIL NIL NIL NIL (CAR-ADDR) NIL NIL)
 ((RAW-TERM TERM WRLD) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
