("/home/acl2/books/std/stobjs/stobjtab.lisp::STOBJTAB$AP"
 ((STOBJTAB$A) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/stobjs/stobjtab.lisp::CREATE-STOBJTAB$A"
 ((NIL) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/stobjs/stobjtab.lisp::STBL-GET$A"
 (NIL NIL NIL (K) NIL NIL NIL) ((STOBJTAB$A DEFAULT) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/stobjs/stobjtab.lisp::STBL-PUT$A"
 (NIL NIL NIL (K) NIL NIL NIL) ((V STOBJTAB$A) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/stobjs/stobjtab.lisp::STBL-BOUNDP$A"
 (NIL NIL (K) NIL NIL NIL NIL) ((STOBJTAB$A) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/stobjs/stobjtab.lisp::STBL-REM$A"
 (NIL NIL (K) NIL NIL NIL NIL) ((STOBJTAB$A) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/stobjs/stobjtab.lisp::STBL-COUNT$A"
 ((STOBJTAB$A) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/stobjs/stobjtab.lisp::STBL-CLEAR$A"
 ((STOBJTAB$A) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/stobjs/stobjtab.lisp::STBL-INIT$A"
 (NIL NIL NIL NIL (HT-SIZE) NIL NIL)
 ((REHASH-SIZE REHASH-THRESHOLD STOBJTAB$A) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
