("/home/acl2/books/arithmetic-5/lib/basic-ops/remove-weak-inequalities.lisp::REMOVE-WEAK-INEQUALITIES-FN"
 (NIL NIL NIL NIL (X) NIL NIL) ((Y MFC STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/remove-weak-inequalities.lisp::REMOVE-STRICT-INEQUALITIES-FN"
 (NIL NIL NIL NIL (X) NIL NIL) ((Y MFC STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
