("/home/acl2/books/projects/numbers/support/fta.lisp::PRIME-POW-LIST-P"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL (CONSP NULL) NIL NIL (AND) NIL)
 ((L L) NIL (PRIMEP POSP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (OR) NIL NIL
  NIL)
 (NIL NIL (CAAR CDAR CDR NULL) (<) NIL NIL NIL)
 ((L L L) NIL (CDR CAAR CAADR) NIL NIL NIL NIL)
 ((L L L) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/projects/numbers/support/fta.lisp::PRIME-FACT"
 ((N) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/projects/numbers/support/fta.lisp::POW-PROD"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL (1) (CONSP) (*) NIL NIL NIL)
 ((L) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (EXPT) NIL NIL NIL)
 (NIL NIL (CAAR CDAR CDR) NIL NIL NIL NIL) ((L L L) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/projects/numbers/support/fta.lisp::PRIME-FACT-INDUCT"
 (NIL NIL (N) NIL NIL NIL NIL) ((L) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
