("/home/acl2/books/centaur/fty/fty-sum-casemacro.lisp::KIND-CASEMACRO-CASESPEC-P"
 (NIL NIL NIL NIL NIL (AND) NIL)
 (NIL NIL (CONSP SYMBOLP CONSP) NIL (IF) NIL NIL)
 ((SPEC) NIL (CAR CDR ATOM) (AND) NIL NIL (AND))
 ((SPEC SPEC) NIL (CADR SYMBOLP NOT CONSP SYMBOL-LISTP CONSP SYMBOLP NOT) NIL
  NIL NIL NIL)
 ((SPEC) NIL (CADR CDDR CADR CADR CDDR CADDR CDDDR) NIL NIL NIL NIL)
 ((SPEC SPEC SPEC SPEC SPEC SPEC SPEC) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/centaur/fty/fty-sum-casemacro.lisp::KIND-CASEMACRO-CASESPECS-P"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL (ATOM) (EQ AND) NIL NIL NIL)
 ((SPECS SPECS NIL) NIL
  (KIND-CASEMACRO-CASESPEC-P ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((SPECS SPECS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/centaur/fty/fty-sum-casemacro.lisp::KIND-CASEMACRO-SPEC-P"
 (NIL NIL NIL NIL NIL NIL (AND))
 (NIL NIL (CONSP SYMBOLP CONSP SYMBOLP KIND-CASEMACRO-CASESPECS-P) NIL NIL NIL
  NIL)
 ((SPEC) NIL (CAR CDR CADR CDDR) NIL NIL NIL NIL)
 ((SPEC SPEC SPEC SPEC) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/centaur/fty/fty-sum-casemacro.lisp::KIND-CASEMACRO-CASES"
 (NIL NIL NIL (VAR) NIL NIL NIL) ((CASES KWD-ALIST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/centaur/fty/fty-sum-casemacro.lisp::KIND-CASEMACRO-PROD-KINDS"
 ((CASES) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/centaur/fty/fty-sum-casemacro.lisp::KIND-CASEMACRO-CHECK-PROD-KINDS-COVERED"
 (NIL NIL NIL (CASES) NIL NIL NIL) ((KEYS SEEN) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/centaur/fty/fty-sum-casemacro.lisp::COND-CASEMACRO-CASESPEC-P"
 (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL (CONSP SYMBOLP CONSP CONSP SYMBOLP NOT) NIL NIL NIL NIL)
 ((SPEC) NIL (CAR CDR CDDR CADDR CDDDR) NIL NIL NIL NIL)
 ((SPEC SPEC SPEC SPEC SPEC) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/centaur/fty/fty-sum-casemacro.lisp::COND-CASEMACRO-CASESPECS-P"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL (ATOM) (EQ AND) NIL NIL NIL)
 ((SPECS SPECS NIL) NIL
  (COND-CASEMACRO-CASESPEC-P ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((SPECS SPECS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/centaur/fty/fty-sum-casemacro.lisp::COND-CASEMACRO-SPEC-P"
 (NIL NIL NIL NIL NIL NIL (AND))
 (NIL NIL (CONSP SYMBOLP CONSP SYMBOLP COND-CASEMACRO-CASESPECS-P) NIL NIL NIL
  NIL)
 ((SPEC) NIL (CAR CDR CADR CDDR) NIL NIL NIL NIL)
 ((SPEC SPEC SPEC SPEC) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/centaur/fty/fty-sum-casemacro.lisp::COND-CASEMACRO-CASES"
 (NIL NIL NIL NIL (VAR) NIL NIL)
 ((COND-VAR CASES KWD-ALIST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
