("/home/acl2/books/tools/def-functional-instance.lisp::LOOK-FOR-GOAL-HINT"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (OR) NIL NIL NIL)
 ((HINTS) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL (AND))
 (NIL NIL (CONSP STRINGP STANDARD-CHAR-LISTP CAR CDR) (EQUAL) NIL NIL NIL)
 (("GOAL" HINTS HINTS) NIL (CAR CAAR STRING-UPCASE) (COERCE) NIL NIL NIL)
 ((HINTS HINTS) NIL (CAAR QUOTE CAAR) NIL NIL NIL NIL)
 ((HINTS LIST HINTS) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/def-functional-instance.lisp::DEF-FUNCTIONAL-INSTANCE-FN"
 (NIL NIL NIL NIL NIL NIL NIL)
 ((OLDNAME SUBST HINTS RULE-CLASSES RULE-CLASSESP TRANSLATE MACRO-SUBST
   BY-HINT-P STATE)
  NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
