("/home/acl2/books/arithmetic-5/lib/basic-ops/collect.lisp::COLLECT-+"
 (NIL NIL (X) NIL NIL NIL NIL) ((Y) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/collect.lisp::POW-2"
 (NIL NIL NIL (LET) NIL NIL NIL)
 (((POW (POWER-OF-2-GENERALIZED X))) NIL NIL NIL (IF) NIL NIL)
 ((POW NIL) NIL (SB-INT:QUASIQUOTE) NIL NIL NIL NIL)
 (((,TO-BIND QUOTE ,POW)) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/collect.lisp::COLLECT-*"
 (NIL NIL (X) NIL NIL NIL NIL) ((Y) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/collect.lisp::BUBBLE-DOWN"
 (NIL NIL (X) NIL NIL NIL NIL) ((MATCH) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
