("/home/acl2/books/misc/install-not-normalized.lisp::INSTALL-NOT-NORMALIZED-NAME"
 ((NAME) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/install-not-normalized.lisp::INSTALL-NOT-NORMALIZED-FN-1"
 (NIL NIL NIL NIL NIL NIL (NAME))
 ((WRLD ENS CLIQUE DEFTHM-NAME ENABLE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/install-not-normalized.lisp::INSTALL-NOT-NORMALIZED-FN-LST"
 (NIL NIL NIL NIL NIL NIL (FNS))
 ((WRLD ENS ALL-FNS DEFTHM-NAME-DOUBLETS ENABLE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/install-not-normalized.lisp::INSTALL-NOT-NORMALIZED-FN"
 (NIL NIL NIL NIL NIL NIL (NAME))
 ((WRLD ENS ALLP DEFTHM-NAME ENABLE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/install-not-normalized.lisp::FN-IS-BODY-NAME"
 ((NAME) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
