("/home/acl2/books/meta/term-defuns.lisp::MEMB" (NIL NIL NIL NIL (IF) NIL NIL)
 ((NIL) NIL (CONSP) (OR) NIL NIL NIL)
 ((X) NIL NIL (EQUAL ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((A A) NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/meta/term-defuns.lisp::DEL" (NIL NIL NIL NIL (IF) NIL NIL)
 ((Y) NIL (CONSP) NIL (IF) NIL NIL) ((Y) NIL (CDR) (EQUAL CONS) NIL NIL NIL)
 ((X Y) NIL (CAR CAR) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((Y Y X) NIL (CDR) NIL NIL NIL NIL) ((Y) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/meta/term-defuns.lisp::SUBBAGP"
 (NIL NIL NIL NIL (IF) NIL NIL) ((T) NIL (CONSP) NIL (IF) NIL NIL)
 ((X NIL) NIL NIL (MEMB ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((Y) NIL (CAR CDR) (DEL) NIL NIL NIL) ((X X Y) NIL (CAR) NIL NIL NIL NIL)
 ((X) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/meta/term-defuns.lisp::BAGDIFF"
 (NIL NIL NIL NIL (IF) NIL NIL) ((X) NIL (CONSP) NIL (IF) NIL NIL)
 ((Y) NIL NIL
  (MEMB ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL)
 ((X X) NIL (CAR CDR CDR) (DEL) NIL NIL NIL)
 ((Y X Y Y) NIL (CAR) NIL NIL NIL NIL) ((Y) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/meta/term-defuns.lisp::BAGINT"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (CONSP) NIL (IF) NIL NIL)
 ((X) NIL NIL (MEMB CONS ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((Y Y) NIL (CAR CAR CDR) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL)
 ((X X X) NIL (CDR) (DEL) NIL NIL NIL) ((X Y) NIL (CAR) NIL NIL NIL NIL)
 ((X) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/meta/term-defuns.lisp::TERM-LIST-TO-TYPE-TERM"
 (NIL NIL (UNARY-OP-NAME) NIL NIL NIL NIL) ((LST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/meta/term-defuns.lisp::BINARY-OP_FRINGE"
 (NIL NIL (BINARY-OP-NAME) NIL NIL NIL NIL) ((X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/meta/term-defuns.lisp::BINARY-OP_TREE"
 (NIL NIL NIL NIL (BINARY-OP-NAME) NIL NIL)
 ((CONSTANT-NAME FIX-NAME LST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/meta/term-defuns.lisp::BINARY-OP_TREE-SIMPLE"
 (NIL NIL NIL (BINARY-OP-NAME) NIL NIL NIL)
 ((CONSTANT-NAME LST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/meta/term-defuns.lisp::REMOVE-DUPLICATES-MEMB"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (CONSP) NIL (IF) NIL NIL)
 ((LST) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (MEMB CONS) NIL NIL NIL)
 (NIL NIL (CAR CDR CDR CAR ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL NIL)
 ((LST LST LST LST) NIL (CDR) NIL NIL NIL NIL) ((LST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/meta/term-defuns.lisp::FRINGE-OCCUR"
 (NIL NIL NIL (BINOP) NIL NIL NIL) ((ARG TERM) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
