("/home/acl2/books/rtl/rel9/arithmetic/fp2.lisp::POINT-RIGHT-MEASURE"
 (NIL NIL NIL (FLOOR) NIL NIL NIL) (NIL (1) NIL NIL (IF) NIL NIL)
 (NIL (0) (/) (AND) NIL NIL NIL) ((X) NIL (RATIONALP) (<) NIL NIL NIL)
 ((X X) (0) NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/rtl/rel9/arithmetic/fp2.lisp::POINT-LEFT-MEASURE"
 (NIL NIL NIL (FLOOR) NIL NIL NIL) (NIL (1) NIL NIL (IF) NIL NIL)
 ((X) (0) NIL (AND) NIL NIL NIL) (NIL NIL (RATIONALP) (>) NIL NIL NIL)
 ((X X) (0) NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
