("/home/acl2/books/sorting/convert-perm-to-how-many.lisp::PERM-COUNTER-EXAMPLE"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL ((ATOM X) (NOT (MEMB (CAR X) Y)) T) NIL NIL NIL NIL)
 (NIL NIL (CAR CAR) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((Y X) NIL (CDR) (RM) NIL NIL NIL) ((X Y) NIL (CAR) NIL NIL NIL NIL)
 ((X) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/sorting/convert-perm-to-how-many.lisp::TLFIX"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ENDP) (CONS) NIL NIL NIL)
 ((X) NIL (CAR ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL NIL)
 ((X) NIL (CDR) NIL NIL NIL NIL) ((X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
