("/home/acl2/books/kestrel/arithmetic-light/floor.lisp::ALL-VARS-NEGATED"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (VARIABLEP) NIL (IF) NIL NIL)
 ((TERM T) NIL (FQUOTEP) (LET) NIL NIL NIL)
 ((TERM (FN (FFN-SYMB TERM))) NIL NIL NIL (IF) NIL NIL)
 (NIL NIL NIL (EQ AND) (IF) NIL NIL)
 ((FN NIL) NIL
  (QUOTE ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL VARIABLEP)
  (EQ) NIL NIL NIL)
 ((BINARY-+ FN) NIL (SECOND THIRD QUOTE SECOND) NIL NIL NIL NIL))
