("/home/acl2/books/rtl/rel9/arithmetic/predicate.lisp::PREDICATEP"
 (NIL NIL NIL (AND) NIL NIL NIL) (NIL NIL (CONSP) (MEMBER) NIL NIL NIL)
 ((TERM) NIL (CAR QUOTE) NIL NIL NIL NIL) ((TERM) NIL NIL NIL NIL NIL (<))
 ((INTEGERP POWER2P COMPLEX-RATIONALP RATIONALP BVECP) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
