("/home/acl2/books/tools/defined-const.lisp::DEFINED-CONST-FN"
 (NIL NIL NIL (LET) NIL NIL NIL)
 (((THMNAME
    (OR THMNAME
        (INTERN-IN-PACKAGE-OF-SYMBOL
         (CONCATENATE 'STRING (SYMBOL-NAME CONSTNAME) "-DEF") CONSTNAME))))
  NIL (SB-INT:QUASIQUOTE) NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL (WITH-OUTPUT))
 ((:OFF :ALL :ON ERROR) NIL NIL NIL (ENCAPSULATE) NIL NIL)
 ((NIL) NIL (LOCAL MAKE-EVENT) NIL NIL NIL NIL)
 (NIL NIL (SB-INT:QUASIQUOTE) NIL NIL NIL NIL)
 (NIL NIL (IN-THEORY IN-THEORY MEMOIZE MAKE-EVENT) NIL NIL (DEFUN DEFUN) NIL))
