("/home/acl2/books/std/system/acceptable-rewrite-rule-p.lisp::ACCEPTABLE-REWRITE-RULE-P1"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((NULL LST) T) NIL NIL NIL NIL)
 ((T) NIL NIL NIL NIL (MV-LET) NIL) (NIL NIL (DECLARE) (AND) NIL NIL (MSG))
 ((EQV LHS0 LHS RHS TTREE NIL NAME NIL ENS WRLD) NIL (CAAR CDAR NULL) NIL NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (IGNORE))
 ((LST LST EQV LHS0 LHS RHS TTREE MSG NAME ENS WRLD) NIL (CDR) NIL NIL NIL NIL)
 ((LST) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/system/acceptable-rewrite-rule-p.lisp::ACCEPTABLE-REWRITE-RULE-P"
 (NIL NIL NIL NIL NIL (ACCEPTABLE-REWRITE-RULE-P1) NIL)
 ((:SOME-PROPOSED-REWRITE-RULE ENS WRLD) NIL (UNPRETTYIFY) NIL NIL NIL NIL)
 (NIL NIL NIL (REMOVE-GUARD-HOLDERS) NIL NIL NIL)
 ((TERM WRLD) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
