("/home/acl2/books/centaur/fty/fty-parseutils.lisp::EXTRA-BINDER-NAMES->ACC-ALIST"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (CONS) NIL NIL NIL)
 ((NAMES) NIL NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (IF) NIL NIL)
 ((TYPE-NAME) NIL (CONSP CAR CDR) (CONS) NIL NIL NIL)
 ((NAMES NAMES) NIL (CAR CAR) (INTERN-IN-PACKAGE-OF-SYMBOL) NIL NIL NIL)
 ((NAMES NAMES TYPE-NAME) NIL NIL NIL (CAT) NIL NIL)
 (("->") NIL (SYMBOL-NAME SYMBOL-NAME) NIL NIL NIL NIL))
