("/home/acl2/books/misc/how-to-prove-thms.lisp::DUP"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (CONSP) (CONS) NIL NIL NIL)
 ((X) NIL (CAR) (CONS) NIL NIL NIL)
 ((X) NIL (CAR ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL NIL)
 ((X) NIL (CDR) NIL NIL NIL NIL) ((X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::APP"
 (NIL NIL NIL NIL (IF) NIL NIL) ((Y) NIL (CONSP) (CONS) NIL NIL NIL)
 ((X) NIL (CAR) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((X Y) NIL (CDR) NIL NIL NIL NIL) ((X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::MEMP"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (CONSP) NIL (IF) NIL NIL)
 ((X T) NIL NIL (EQUAL ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((E E) NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::REV"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (CONSP) (APP) NIL NIL NIL)
 ((X) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (CONS) NIL NIL NIL)
 ((NIL) NIL (CDR CAR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::REV1"
 (NIL NIL NIL NIL (IF) NIL NIL)
 ((A) NIL (CONSP) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((X) NIL (CDR) (CONS) NIL NIL NIL) ((X A) NIL (CAR) NIL NIL NIL NIL)
 ((X) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::PROPERP"
 (NIL NIL NIL NIL (IF) NIL NIL)
 (NIL NIL (CONSP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (EQUAL) NIL NIL NIL)
 ((X X NIL) NIL (CDR) NIL NIL NIL NIL) ((X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::MAPNIL"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (CONSP) (CONS) NIL NIL NIL)
 ((X NIL) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL NIL)
 (NIL NIL (CDR) NIL NIL NIL NIL) ((X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::SWAPTREE"
 (NIL NIL NIL NIL (IF) NIL NIL) ((X) NIL (CONSP) (CONS) NIL NIL NIL)
 ((X) NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 (NIL NIL (CDR CAR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::ZIPLISTS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (CONSP) (CONS) NIL NIL NIL)
 ((X) NIL NIL (CONS ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 (NIL NIL (CAR CAR CDR CDR) NIL NIL NIL NIL)
 ((X Y X Y) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::LOOKUP"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (CONSP) NIL (IF) NIL NIL)
 ((A) NIL (CDR) (EQUAL ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((X X) NIL (CAR CAR CDR) NIL NIL NIL NIL) ((A A) NIL (CAR) NIL NIL NIL NIL)
 ((A) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::FOUNDP"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (CONSP) NIL (IF) NIL NIL)
 ((A T) NIL NIL (EQUAL ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((X X) NIL (CAR CDR) NIL NIL NIL NIL) ((A) NIL (CAR) NIL NIL NIL NIL)
 ((A) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::SUBP"
 (NIL NIL NIL NIL (IF) NIL NIL) ((T) NIL (CONSP) NIL (IF) NIL NIL)
 ((X NIL) NIL NIL (MEMP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((Y Y) NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::INT"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (CONSP) NIL (IF) NIL NIL)
 ((X) NIL NIL (MEMP CONS ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((Y Y) NIL (CAR CAR CDR) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL)
 ((X X Y X) NIL (CDR) NIL NIL NIL NIL) ((X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::MEM"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (CONSP) NIL (IF) NIL NIL)
 ((X X) NIL NIL (EQUAL ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((E E) NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::LONESOMEP"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (NOT) (MEM) NIL NIL NIL)
 ((E LST) NIL NIL (MEM) NIL NIL NIL) ((E) NIL (CDR) NIL NIL NIL NIL)
 (NIL NIL NIL (MEM) NIL NIL NIL) ((E LST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::COLLECT-LONESOMEP"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (CONSP) NIL (IF) NIL NIL)
 ((A) NIL NIL (LONESOMEP CONS ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL)
 ((B B) NIL (CAR CAR CDR) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL)
 ((A A B A) NIL (CDR) NIL NIL NIL NIL) ((A) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::LEAVES"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL (CONSP) (APP CONS) NIL NIL NIL)
 ((X X NIL) NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::LONESOMES"
 (NIL NIL NIL (COLLECT-LONESOMEP) NIL NIL NIL)
 (NIL NIL (LEAVES LEAVES) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::TREECOPY"
 (NIL NIL NIL NIL (IF) NIL NIL) ((X) NIL (CONSP) (CONS) NIL NIL NIL)
 ((X) NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::LEAVES"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL (CONSP) (APP CONS) NIL NIL NIL)
 ((X X NIL) NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::SETEQP"
 (NIL NIL NIL (AND) NIL NIL NIL) (NIL NIL NIL (SUBP SUBP) NIL NIL NIL)
 ((X Y Y X) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::LIST-OF-ATOMSP"
 (NIL NIL NIL NIL (IF) NIL NIL) ((T) NIL (CONSP) (AND) NIL NIL NIL)
 ((X) NIL (NOT ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL NIL)
 (NIL NIL (CONSP CDR) NIL NIL NIL NIL) ((X) NIL (CAR) NIL NIL NIL NIL)
 ((X) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::NUMP"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL (CONSP) (AND EQUAL) NIL NIL NIL)
 ((X X NIL) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (EQUAL) NIL NIL NIL)
 ((NIL) NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::ADD"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL (CONSP MAPNIL) (CONS) NIL NIL NIL)
 ((X NIL Y) NIL NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((Y) NIL (CDR) NIL NIL NIL NIL) ((X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::MULT"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (CONSP) (ADD) NIL NIL NIL)
 ((X Y) NIL NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((Y) NIL (CDR) NIL NIL NIL NIL) ((X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::RAISE"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL (CONSP QUOTE) (MULT) NIL NIL NIL)
 ((Y X NIL) NIL NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((X) NIL (CDR) NIL NIL NIL NIL) ((Y) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::FACT"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL (CONSP QUOTE) (MULT) NIL NIL NIL)
 ((N N NIL) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL NIL)
 (NIL NIL (CDR) NIL NIL NIL NIL) ((N) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::FACT1"
 (NIL NIL NIL NIL (IF) NIL NIL)
 ((A) NIL (CONSP) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((N) NIL (CDR) (MULT) NIL NIL NIL) ((N N A) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/how-to-prove-thms.lisp::MC-FLATTEN"
 (NIL NIL NIL NIL (IF) NIL NIL)
 (NIL NIL (CONSP) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL CONS) NIL NIL NIL)
 ((X X A) NIL (CAR) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((X A) NIL (CDR) NIL NIL NIL NIL) ((X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
