("/home/acl2/books/clause-processors/join-thms.lisp::EV-MK-RULENAME"
 (NIL NIL NIL (INTERN-IN-PACKAGE-OF-SYMBOL) NIL NIL NIL)
 ((EV) NIL NIL NIL NIL (CONCATENATE) NIL)
 (("-") NIL (QUOTE SYMBOL-NAME SYMBOL-NAME) NIL NIL NIL NIL)
 ((STRING EV NAME) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/clause-processors/join-thms.lisp::EV-PAIR-RULENAMES"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (CONS) NIL NIL NIL)
 ((NAMES) NIL NIL (CONS ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((EV) NIL (CAR CDR) (EV-MK-RULENAME) NIL NIL NIL)
 ((NAMES EV NAMES) NIL (CAR) NIL NIL NIL NIL) ((NAMES) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
