("/home/acl2/books/misc/defattach-bang.lisp::DEFATTACH!-DEFUN"
 (NIL NIL NIL (NAME) NIL NIL NIL) ((CTX WRLD) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/defattach-bang.lisp::DEFATTACH!-EVENT"
 (NIL NIL NIL NIL (ARGS) NIL NIL)
 ((WRLD DEFS NEW-ARGS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/defattach-bang.lisp::DEFATTACH!-FN"
 (NIL NIL (SB-INT:QUASIQUOTE) NIL NIL NIL NIL)
 (NIL NIL (MAKE-EVENT) NIL NIL NIL NIL) (NIL NIL NIL (LET) NIL NIL NIL)
 (((EVENT (DEFATTACH!-EVENT ',ARGS (W STATE) NIL NIL))) NIL NIL (OR) NIL NIL
  NIL)
 ((EVENT) NIL NIL (CONS) NIL NIL NIL) (NIL NIL 'QUOTE NIL NIL NIL NIL)
 ((DEFATTACH ,ARGS) NIL NIL NIL NIL NIL NIL))
