("/home/acl2/books/misc/evalable-printing.lisp::QUOTE-AS-NEEDED"
 ((EXPR) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/evalable-printing.lisp::QUOTE-AS-NEEDED-LIST"
 ((EXPR-LST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/evalable-printing.lisp::QUOTE-AS-NEEDED-WITH-STOBJ"
 (NIL NIL NIL NIL (IF) NIL NIL)
 ((STOBJ STOBJ) NIL (QUOTE-AS-NEEDED) NIL NIL NIL NIL)
 ((VAL) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/evalable-printing.lisp::QUOTE-AS-NEEDED-WITH-STOBJ-LIST"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL NIL (OR CONS) NIL NIL NIL)
 (NIL NIL (ENDP ENDP)
  (QUOTE-AS-NEEDED-WITH-STOBJ ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL)
 ((VALX STOBJS) NIL (CAR CAR CDR CDR) NIL NIL NIL NIL)
 ((VALX STOBJS VALX STOBJS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/evalable-printing.lisp::GET-EVALABLE-PRINTING-ABSTRACTIONS"
 (NIL NIL NIL NIL (IF) NIL NIL)
 ((*DEFAULT-EVALABLE-PRINTING-ABSTRACTIONS*) NIL NIL
  (F-BOUNDP-GLOBAL F-GET-GLOBAL) NIL NIL NIL)
 ((STATE STATE) NIL 'QUOTE NIL NIL NIL NIL)
 ((EVALABLE-PRINTING-ABSTRACTIONS EVALABLE-PRINTING-ABSTRACTIONS) NIL NIL NIL
  NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/evalable-printing.lisp::LASTCDR"
 (NIL NIL NIL NIL (IF) NIL NIL)
 ((X) NIL (ATOM ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL NIL)
 ((X) NIL (CDR) NIL NIL NIL NIL) ((X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/evalable-printing.lisp::MAKE-EVALABLE-WITH-STOBJ-HOW"
 (NIL NIL NIL NIL (IF) NIL NIL)
 ((STOBJ STOBJ) NIL NIL (MAKE-EVALABLE-HOW) NIL NIL NIL)
 ((VAL ABSTRACTIONS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/evalable-printing.lisp::MAKE-EVALABLE-WITH-STOBJ-LIST-HOW"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL NIL (OR CONS) NIL NIL NIL)
 (NIL NIL (ENDP ENDP) NIL
  (MAKE-EVALABLE-WITH-STOBJ-HOW ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL)
 ((VALX STOBJS ABSTRACTIONS ABSTRACTIONS) NIL (CAR CAR CDR CDR) NIL NIL NIL
  NIL)
 ((VALX STOBJS VALX STOBJS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
