("/home/acl2/books/std/util/add-io-pairs.lisp::UPDATE-IO-LOOKUP-INIT"
 (NIL NIL (ARGS) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/add-io-pairs.lisp::UPDATE-IO-LOOKUP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ENDP KEYS) T) NIL NIL NIL NIL)
 ((VAL) NIL NIL (LET) NIL NIL NIL)
 (((PAIR (ASSOC-EQUAL (CAR KEYS) X))) NIL NIL (COND) NIL NIL NIL)
 (NIL NIL (PAIR T) NIL NIL NIL NIL)
 (NIL NIL NIL NIL (PUT-ASSOC-EQUAL ACONS) NIL NIL)
 ((X X) NIL (CAR CAR) (UPDATE-IO-LOOKUP-INIT)
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL))
("/home/acl2/books/std/util/add-io-pairs.lisp::UPDATE-IO-LOOKUP-LST"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ENDP LST) T) NIL NIL NIL NIL)
 ((X) NIL NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 (NIL NIL (CDR) (LET*) NIL NIL NIL)
 ((LST) NIL NIL ((PAIR (CAR LST))) (UPDATE-IO-LOOKUP) NIL NIL)
 ((KEYS VAL X) NIL (KEYS VAL) NIL NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL))
("/home/acl2/books/std/util/add-io-pairs.lisp::IO-LOOKUP-FN"
 (NIL NIL NIL (VAR) NIL NIL NIL) ((KEYS TESTS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/add-io-pairs.lisp::IO-PAIRS-ADD-INPUT"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ENDP LST) T) NIL NIL NIL NIL)
 ((NIL) NIL NIL (B*) NIL NIL NIL)
 ((((CONS (LIST INPUTS RESULT) REST) LST)) NIL NIL (CONS) NIL NIL NIL)
 (NIL NIL NIL (LIST ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((RESULT INPUT REST) NIL NIL (CONS) NIL NIL NIL)
 ((INPUT INPUTS) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/add-io-pairs.lisp::GET-IO-PAIRS-FN1"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ENDP FNS) T) NIL NIL NIL NIL)
 ((NIL) NIL NIL (APPEND) NIL NIL NIL)
 (NIL NIL NIL (LET) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 (((FN (CAR FNS)) TBL WRLD) NIL (CDR) (IO-PAIRS-ADD-INPUT) NIL NIL NIL)
 ((FN FNS) NIL NIL NIL (GET-IO-PAIRS-FN2-LST) NIL NIL)
 (NIL NIL (CDR CONSP) (FORMALS) NIL NIL NIL))
("/home/acl2/books/std/util/add-io-pairs.lisp::GET-IO-PAIRS-FN"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (NIL NIL NIL NIL (GET-IO-PAIRS-FN1) NIL
  ((TBL (TABLE-ALIST 'IO-PAIRS-TABLE WRLD))))
 ((FNS TBL WRLD) NIL (TBL-FNS ALLP BAD FNS -) NIL NIL NIL NIL)
 (NIL NIL (STRIP-CARS) (EQUAL AND) (COND AND) NIL NIL)
 ((TBL FNS BAD WARNP) NIL (QUOTE NOT ALLP BAD T) (SET-DIFFERENCE-EQ) NIL NIL
  (WARNING$-CW0))
 ((:ALL ALLP FNS TBL-FNS TBL-FNS FNS NIL
   "There ~#0~[is no I/O pair for the symbol~/are ~
                              no I/O pairs for the symbols~] ~&0."
   BAD)
  NIL 'DEFAULT-STATE-VARS (INTERSECTION-EQ) NIL NIL NIL)
 ((FNS TBL-FNS GET-IO-PAIRS T) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/add-io-pairs.lisp::MAYBE-KWOTE-LST"
 ((X) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/add-io-pairs.lisp::SHOW-IO-PAIRS-LST"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ENDP PAIRS) T) NIL NIL NIL NIL)
 (NIL NIL NIL (NEWLINE PPROGN) NIL NIL NIL)
 ((CHAN STATE) NIL NIL (B*) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL)
 ((CHAN WRLD STATE) NIL (CDR) NIL NIL NIL (FMS))
 (("~x0" CHAN STATE NIL PAIRS) NIL
  (FN/INPUTS FN INPUTS RESULT MVP QINPUTS QRESULT IO-PAIR LIST) NIL NIL NIL
  NIL)
 (NIL NIL (CAR CAR CDR CADR CDR MAYBE-KWOTE-LST SB-INT:QUASIQUOTE) (CONS) (IF)
  NIL NIL))
("/home/acl2/books/std/util/add-io-pairs.lisp::SHOW-IO-PAIRS-FN"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (NIL NIL NIL (PPROGN) NIL
  (((WHEN (AND (MEMBER-EQ :ALL FNS) (NOT (EQUAL FNS '(:ALL)))))
    (ER SOFT 'SHOW-IO-PAIRS
        "It is illegal to use :ALL with ~x0 except in the form ~x1."
        'SHOW-IO-PAIRS '(SHOW-IO-PAIRS :ALL))))
  NIL)
 (NIL NIL (WRLD CHAN ALLP PAIRS VALUE) (COND) NIL NIL NIL)
 ((:INVISIBLE) NIL (W STANDARD-CO (NULL PAIRS) T) (EQUAL) NIL (GET-IO-PAIRS-FN)
  NIL)
 ((STATE STATE FNS WRLD NIL STATE) NIL (QUOTE) (OR PPROGN) NIL NIL (FMS))
 ((:ALL FNS "There are no verified I/O pairs to display~#0~[~/ for the symbol ~
             ~v1~/ for any of the symbols ~v1~].~|"
   CHAN STATE NIL)
  NIL (QUOTE) (LIST) NIL (SHOW-IO-PAIRS-LST) (FMS))
 ((:ALL "Verified I/O pairs ((fn arg1 .. argn) result):~|" NIL CHAN STATE NIL
   PAIRS CHAN WRLD STATE)
  NIL NIL (CONS CONS) NIL NIL NIL))
("/home/acl2/books/std/util/add-io-pairs.lisp::SIMPLE-TRANS-EVAL-LST"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (NIL NIL (VALUE) NIL (((WHEN (ENDP LST)) (VALUE NIL))) NIL NIL)
 (NIL NIL (TERM (ER (CONS ?TTERM VAL)) (ER REST)) (CONS) NIL NIL NIL)
 ((VAL REST) NIL (CAR) NIL NIL NIL NIL)
 ((LST TERM NIL NIL CTX WRLD STATE T CALL CTX WRLD STATE) NIL (CDR 1+) NIL
  (MSG) NIL NIL)
 (("The ~n0 argument of the call ~x1" CALL LST I) NIL (LIST) NIL NIL NIL NIL)
 ((I) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/add-io-pairs.lisp::ADD-IO-PAIRS-TRANSLATE-TUPLES-1"
 (NIL NIL NIL (B*) NIL NIL NIL) (NIL NIL (VALUE) NIL NIL NIL NIL)
 (NIL NIL
  (TUPLE
   (WHEN
       (NOT
        (AND (CONSP TUPLE) (CONSP (CAR TUPLE)) (CONSP (CDR TUPLE))
             (NULL (CDDR TUPLE)))))
   (LIST (CONS FN2 ACTUALS) RESULT) (WHEN (NOT (EQ FN2 FN)))
   (WHEN (NOT (= (LENGTH ACTUALS) ARITY-IN))) (ER INPUTS) (ER -)
   (ER (CONS ? OUTPUT)) IO-DOUBLET (ER IO-DOUBLET-LST))
  (CONS) NIL NIL NIL)
 ((TUPLE IO-DOUBLET IO-DOUBLET-LST) NIL (CAR) (B* LIST) NIL (ER TRANS-EVAL)
  (ER))
 ((TUPLES SOFT CTX
   "An I/O tuple must be of the form ((fn x1 ... xk) result), but ~
             the following is not of that form:~|~x0"
   TUPLE SOFT CTX
   "It is illegal to specify more than one function symbol in a call ~
             of add-io-pairs, but both ~x0 and ~x1 were specified."
   FN FN2 SOFT CTX
   "The I/O pair ~x0 specifies ~x1 inputs, but the function symbol ~
             ~x2 expects ~x3 inputs."
   TUPLE FN ARITY-IN ACTUALS CTX WRLD STATE RESULT CTX STATE T INPUTS OUTPUT FN
   ARITY-IN STOBJS-OUT CTX WRLD STATE)
  (1) (LENGTH VALUE CDR) (CONS)
  (((MV ERP ?TRANS BINDINGS STATE)
    (TRANSLATE1 RESULT :STOBJS-OUT '((:STOBJS-OUT . :STOBJS-OUT)) T CTX WRLD
                STATE)))
  NIL NIL)
 ((ACTUALS FN ACTUALS NIL TUPLES) NIL
  ((WHEN ERP) RESULT-STOBJS-OUT
   (WHEN (NOT (EQUAL STOBJS-OUT RESULT-STOBJS-OUT))))
  NIL NIL NIL NIL)
 (NIL NIL (SILENT-ERROR) (TRANSLATE-DEREF) NIL NIL NIL))
("/home/acl2/books/std/util/add-io-pairs.lisp::ADD-IO-PAIRS-TRANSLATE-TUPLES"
 (NIL NIL NIL NIL (TUPLES) NIL NIL) ((CTX WRLD STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/add-io-pairs.lisp::ADD-IO-PAIRS-DCLS"
 (NIL NIL (FN) NIL NIL NIL NIL) ((WRLD) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/add-io-pairs.lisp::FORMAL-MV"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ZP N) T) NIL NIL NIL NIL)
 (NIL NIL NIL (LET*) (LIST) NIL NIL)
 (NIL NIL (QUOTE REVERSE SB-INT:QUASIQUOTE) NIL NIL ((XI (PACKN (LIST 'X I))))
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL))
 ((LET* BINDINGS
    NEXT-EXPR)
  NIL (MV XI-BINDING AI AI-BINDING NEXT-EXPR 1- 1+) (CONS) (LIST*) NIL NIL)
 ((,@(REVERSE VARS) N I AI VARS AI-BINDING XI-BINDING BINDINGS) NIL (PACKN)
  (LIST LIST LIST) NIL NIL NIL)
 ((XI EXPR AI XI) NIL (QUOTE) (LIST LIST) NIL NIL NIL))
("/home/acl2/books/std/util/add-io-pairs.lisp::PUSH-IO-PAIRS-LENIENCE-FN"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ENDP FNS) T) NIL NIL NIL NIL)
 ((NIL) NIL NIL (CONS) NIL NIL NIL)
 (NIL NIL `ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL NIL NIL NIL NIL)
 (NIL NIL (CDR) NIL (TABLE) NIL NIL)
 ((IO-PAIRS-LENIENCE-TABLE FNS) NIL (QUOTE) (CONS) NIL NIL NIL)
 ((,(CAR FNS) NIL) NIL (CDR) NIL NIL NIL NIL))
("/home/acl2/books/std/util/add-io-pairs.lisp::POP-IO-PAIRS-LENIENCE-FN"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ENDP FNS) T) NIL NIL NIL NIL)
 ((NIL) NIL NIL (CONS) NIL NIL NIL)
 (NIL NIL `ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL NIL NIL NIL NIL)
 (NIL NIL (CDR) NIL (TABLE) NIL NIL)
 ((IO-PAIRS-LENIENCE-TABLE FNS) NIL 'CDR NIL NIL NIL NIL)
 ((,(CAR FNS)) NIL (CDR) NIL NIL NIL NIL))
("/home/acl2/books/std/util/add-io-pairs.lisp::CHECK-IO-PAIRS-LENIENCE-FN"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (NIL NIL (VALUE) NIL NIL NIL ((WRLD (W STATE))))
 (NIL NIL
  (LENIENCE (WHEN LENIENCE) CURRENT-ENTRY CTX
   (WHEN (NOT (EQUAL OLD-ENTRY CURRENT-ENTRY))) QUOTE)
  NIL NIL NIL NIL)
 ((CALLER) NIL (CDR VALUE CDR VALUE-TRIPLE) (B*) NIL NIL NIL)
 ((:INVISIBLE) NIL (QUOTE) (ASSOC-EQ ASSOC-EQ)
  ((BOOK (CAR (GLOBAL-VAL 'INCLUDE-BOOK-PATH WRLD))) WITH-OUTPUT!) NIL NIL)
 ((FN FN :ON ERROR) NIL (VALUE-TRIPLE STR NUM2 STR4) (TABLE-ALIST TABLE-ALIST)
  NIL NIL NIL)
 ((WRLD :INVISIBLE WRLD "ACL2 is encountering a call of ~x0 on function symbol ~
                    ~#2~[~x1 while attempting to include the book ~
                    ~x3.~|~/~x1.  ~]But the existing list of I/O pairs for ~
                    ~x1 is different from ~@4.  See :DOC merge-io-pairs for ~
                    how to avoid this ~@5."
   SOFT CTX STR CALLER FN NUM2 BOOK STR4 "error")
  NIL 'QUOTE NIL (IF IF) NIL NIL))
("/home/acl2/books/std/util/add-io-pairs.lisp::ADD-IO-PAIRS-EVENTS"
 (NIL NIL NIL (B*) NIL NIL NIL) (NIL NIL (SB-INT:QUASIQUOTE) NIL NIL NIL NIL)
 (NIL NIL
  (NEW-ENTRY SUM MAX SUFFIX1 THM-NAME SUFFIX2 NEW-FN FORMALS IO-LOOKUP-VAR
   LOOKUP-RESULT0 STOBJS-OUT LOOKUP-RESULT)
  NIL NIL NIL
  ((CHECK-IO-PAIRS-LENIENCE ,FN ,OLD-ENTRY
    ,(IF (EQ IO-DOUBLET-LST :SKIP)
         'INSTALL-IO-PAIRS
         'ADD-IO-PAIRS))))
 ((,@(AND (NOT (EQ IO-DOUBLET-LST :SKIP))
          `((TABLE IO-PAIRS-TABLE ',FN
                   (LET ((OLD-ENTRY
                          (CDR
                           (ASSOC-EQ ',FN
                                     (TABLE-ALIST 'IO-PAIRS-TABLE WORLD)))))
                     (UPDATE-IO-LOOKUP-LST ',IO-DOUBLET-LST OLD-ENTRY))))))
  NIL
  (CHECK-SUM-OBJ MAX-ABSOLUTE-EVENT-NUMBER CHECK-SUM-OBJ CHECK-SUM-OBJ
                 . `UNMEMOIZE)
  (ADD-SUFFIX ADD-SUFFIX FORMALS STOBJS-OUT)
  (IF IF
      ENCAPSULATE
      MEMOIZE)
  (GENVAR DEFUN) NIL)
 ((OLD-ENTRY NEW-ENTRY WRLD FN FN FN WRLD FN "IO-LOOKUP-VAR" FORMALS FN WRLD
   LOOKUP-RESULT0 ,NEW-FN ,FORMALS ,@(ADD-IO-PAIRS-DCLS FN WRLD) NIL :INVOKE)
  (0) (CAR CDR LOCAL QUOTE QUOTE QUOTE)
  (EQ UPDATE-IO-LOOKUP-LST COERCE COERCE LET*) NIL (LIST* LIST*)
  (FORMAL-MV DEFTHM))
 ((IO-DOUBLET-LST :SKIP IO-DOUBLET-LST OLD-ENTRY FN SUM MAX FN SUM MAX
   ,IO-LOOKUP-VAR STOBJS-OUT LOOKUP-RESULT0 NIL NIL ,THM-NAME
   ,@(AND HINTS `(:HINTS ,HINTS)) :RULE-CLASSES NIL ,FN ,FN ,NEW-FN)
  (0) (QUOTE QUOTE QUOTE QUOTE LENGTH (,IO-LOOKUP-VAR ',NEW-ENTRY) IN-THEORY)
  (EXPLODE-ATOM EXPLODE-ATOM EQUAL) (IF) NIL NIL)
 ((DEFTHM SUFFIX1 STRING DEFUN SUFFIX2 STRING STOBJS-OUT ,IO-LOOKUP-VAR
          ,(IF DEBUG
               `(PROG2$
                 (CW "; DEBUG: Found io-pair for input list ~x0.~|"
                     (LIST ,@FORMALS))
                 ,LOOKUP-RESULT)
               LOOKUP-RESULT))
  (10 10) (,IO-LOOKUP-VAR ,FN ,FN ,NEW-FN) (ENABLE) NIL NIL NIL))
("/home/acl2/books/std/util/add-io-pairs.lisp::REMOVE-ASSOC-EQ-LST"
 (NIL NIL (LST) NIL NIL NIL NIL) ((ALIST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/add-io-pairs.lisp::REMOVE-IO-PAIRS-EVENT"
 (NIL NIL NIL (B*) NIL NIL NIL) (NIL NIL (VALUE) NIL NIL NIL NIL)
 (NIL NIL
  ((WHEN (AND (MEMBER-EQ :ALL FNS) (NOT (EQUAL FNS '(:ALL))))) WRLD TBL TBL-FNS
   ALLP BAD FNS (ER -) SB-INT:QUASIQUOTE)
  NIL NIL NIL NIL)
 (NIL NIL (W STRIP-CARS) (TABLE-ALIST EQUAL AND PROGN) (COND IF) NIL (ER))
 ((SOFT "It is illegal to use :ALL with ~x0 except in the form ~x1." STATE WRLD
   TBL FNS BAD ,@(PAIRLIS-X1 'UNMEMOIZE (PAIRLIS$ (KWOTE-LST FNS) NIL)))
  NIL (QUOTE QUOTE QUOTE QUOTE QUOTE NOT ALLP BAD T VALUE) (SET-DIFFERENCE-EQ)
  (WITH-OUTPUT!) (TABLE) NIL)
 ((SHOW-IO-PAIRS REMOVE-IO-PAIRS IO-PAIRS-TABLE :ALL ALLP FNS TBL-FNS TBL-FNS
   FNS :STACK :POP NIL IO-PAIRS-TABLE NIL :CLEAR)
  NIL (REMOVE-IO-PAIRS) (INTERSECTION-EQ PPROGN REMOVE-ASSOC-EQ-LST) NIL NIL
  NIL)
 ((:ALL FNS TBL-FNS) NIL (VALUE QUOTE) (TABLE-ALIST) NIL (WARNING$) NIL))
("/home/acl2/books/std/util/add-io-pairs.lisp::MERGE-IO-PAIRS-FN"
 (NIL NIL (FNS) NIL NIL NIL NIL) ((EVENTS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
