("/home/acl2/books/misc/equal-by-g-help.lisp::G-BADGUY"
 (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL
  ((ATOM X) (ATOM Y) (EQUAL (CAR X) (CAR Y)) (<< (CAAR X) (CAAR Y))
   (EQUAL (CAAR X) (CAAR Y)) T)
  NIL NIL NIL NIL)
 (NIL NIL NIL (CONS ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL CONS CONS CONS)
  (IF) NIL NIL)
 ((NIL :EXTRA-IN-X :EXTRA-IN-X :MISMATCH :EXTRA-IN-Y) NIL
  (ATOM CAR CDR CDR CAR CAR CAR) (CONS) NIL NIL NIL)
 ((Y :EXTRA-IN-Y X X Y X X Y) NIL (CAR) NIL NIL NIL NIL)
 ((Y) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/equal-by-g-help.lisp::G-WORSEGUY"
 (NIL NIL NIL (G-BADGUY) NIL NIL NIL)
 (NIL NIL (ACL2->RCD ACL2->RCD) NIL NIL NIL NIL)
 ((X Y) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
