("/home/acl2/books/misc/defattach-example.lisp::FOLD-ABST"
 (NIL NIL NIL NIL (IF) NIL NIL) ((ROOT) NIL (CONSP) (ABST) NIL NIL NIL)
 ((X) NIL (CAR) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((X ROOT) NIL (CDR) NIL NIL NIL NIL) ((X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/defattach-example.lisp::MULT"
 (NIL NIL NIL (*) NIL NIL NIL) (NIL NIL (FIX FIX) NIL NIL NIL NIL)
 ((X Y) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/defattach-example.lisp::FOLD-MULT"
 (NIL NIL NIL NIL (IF) NIL NIL) ((ROOT) NIL (CONSP) (MULT) NIL NIL NIL)
 ((X) NIL (CAR) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((X ROOT) NIL (CDR) NIL NIL NIL NIL) ((X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/defattach-example.lisp::ADD"
 (NIL NIL NIL (+) NIL NIL NIL) (NIL NIL (FIX FIX) NIL NIL NIL NIL)
 ((X Y) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
