("/home/acl2/books/arithmetic-5/lib/basic-ops/normalize.lisp::FACTORS-OTHER-THAN-DENOMINATOR"
 (NIL NIL (ADDEND) NIL NIL NIL NIL) ((DENOMINATOR) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/normalize.lisp::NUMBER-OF-ADDENDS"
 ((SUM) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/normalize.lisp::FIND-DENOMINATORS-WITH-SUMS"
 (NIL NIL NIL (ADDEND) NIL NIL NIL)
 ((DENOMINATOR-LIST NUMBER-OF-ADDENDS-IN-SUM) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/normalize.lisp::REMAINDER-AAA"
 (NIL NIL NIL NIL (SUM) NIL NIL)
 ((FACTORS TO-BE-FOUND REMAINDER) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/normalize.lisp::NORMALIZE-TERMS-SUCH-AS-A/A+B-+-B/A+B-FN-2"
 (NIL NIL NIL (DENOMINATOR) NIL NIL NIL)
 ((ADDEND REST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/normalize.lisp::NORMALIZE-TERMS-SUCH-AS-A/A+B-+-B/A+B-FN-1"
 (NIL NIL NIL (DENOMINATOR-LIST) NIL NIL NIL)
 ((ADDEND REST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/normalize.lisp::NORMALIZE-TERMS-SUCH-AS-A/A+B-+-B/A+B-FN"
 (NIL NIL (X) NIL NIL NIL NIL) ((Y) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/normalize.lisp::DISTRIBUTE-*"
 (NIL NIL (X) NIL NIL NIL NIL) ((Y) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/normalize.lisp::NORMALIZE-TERMS-SUCH-AS-1/AX+BX-FN"
 ((SUM) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/normalize.lisp::FIND-MATCHING-ADDEND"
 (NIL NIL NIL NIL (TO-MATCH) NIL NIL) ((X MFC STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/normalize.lisp::FIND-MATCHING-FACTOR-GATHER-EXPONENTS"
 (NIL NIL NIL NIL (TO-MATCH) NIL NIL) ((X MFC STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/normalize.lisp::FIND-MATCHING-FACTOR-SCATTER-EXPONENTS"
 (NIL NIL NIL NIL (TO-MATCH) NIL NIL) ((X MFC STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
