("/home/acl2/books/misc/simplify-defuns.lisp::SIMPLIFY-TERM1"
 (NIL NIL NIL (PROG2$) NIL NIL NIL)
 (NIL NIL (SEMI-INITIALIZE-BRR-WORMHOLE) (LET*) NIL NIL NIL)
 ((STATE) NIL NIL (ER-LET*) ((ENS (ENS STATE))) NIL NIL)
 (((PAIR
    (FIND-APPLICABLE-HINT-SETTINGS *INITIAL-CLAUSE-ID* CURRENT-CLAUSE NIL
                                   SAVED-PSPV CTX THINTS WRLD NIL STATE)))
  NIL (SAVED-PSPV NEW-LIT CURRENT-CLAUSE) (LET) NIL NIL NIL)
 (NIL NIL ((HINT-SETTINGS (CAR PAIR))) NIL (FCONS-TERM* ADD-LITERAL MV-LET) NIL
  NIL)
 ((ENS WRLD STATE :DISPLAYED-GOAL TERM :USER-SUPPLIED-TERM TERM :ORIG-HINTS
       THINTS TERM NEW-LIT T)
  NIL (QUOTE DUMB-NEGATE-LIT-LST THINTS HINT-SETTINGS)
  (FCONS-TERM* COND ER-LET*) NIL NIL NIL)
 ((EQUAL HYPS STATE
         (PSPV
          (LOAD-HINT-SETTINGS-INTO-PSPV T HINT-SETTINGS SAVED-PSPV NIL WRLD CTX
                                        STATE)))
  NIL (QUOTE QUOTE CDR (NULL HINT-SETTINGS) T) (COND) NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::SIMPLIFY-TERM*"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL (ZP VALUE) (ER-LET*) NIL NIL NIL)
 ((REMAINING-ITERS
   (TERM-TTREE
    (SIMPLIFY-TERM1 TTREE TERM HYPS EQUIV THINTS PROVE-ASSUMPTIONS CTX WRLD
     STATE)))
  NIL NIL NIL (LIST* IF) NIL NIL)
 ((TERM T TTREE) NIL (VALUE) (EQUAL) NIL NIL NIL)
 ((TERM HYPS EQUIV THINTS PROVE-ASSUMPTIONS CTX WRLD STATE) NIL
  (CAR 1- CDR CAR) NIL (LIST*) NIL NIL)
 ((TERM-TTREE TERM NIL TTREE REMAINING-ITERS TERM-TTREE TERM-TTREE) NIL NIL NIL
  NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::SIMPLIFY-TERM"
 (NIL NIL NIL (STATE-GLOBAL-LET*) NIL NIL NIL)
 (((INHIBIT-OUTPUT-LST
    (IF INHIBIT-OUTPUT
        (UNION-EQ '(PROOF-TREE PROVE) (@ INHIBIT-OUTPUT-LST))
        (@ INHIBIT-OUTPUT-LST))))
  NIL NIL (LET) NIL NIL NIL)
 (((NAME-TREE 'SIMPLIFY-TERM)) NIL NIL (ER-LET*) NIL NIL NIL)
 (NIL NIL NIL ((THINTS (TRANSLATE-HINTS NAME-TREE HINTS CTX WRLD STATE))) NIL
  NIL NIL)
 ((REPEAT-LIMIT NIL TERM HYPS EQUIV THINTS PROVE-ASSUMPTIONS CTX WRLD STATE)
  NIL (THYPS TERM) NIL NIL NIL NIL)
 (NIL NIL NIL NIL (IF IF) NIL NIL)
 ((TRANSLATE-FLG TRANSLATE-FLG) NIL (VALUE VALUE) NIL NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::STRIP-LEADING-PERCENT-FROM-SYMBOL"
 (NIL NIL NIL (LET*) NIL NIL NIL)
 (NIL NIL ((NAME (SYMBOL-NAME SYM))) NIL (IF) NIL NIL)
 ((SYM) NIL (LEN) (AND INTERN-IN-PACKAGE-OF-SYMBOL) NIL NIL NIL)
 ((SYM) NIL (LENGTH NOT) (EQ) (SUBSEQ) NIL NIL)
 ((NAME #\% NAME LEN) (1) NIL (INT= CHAR) NIL NIL NIL)
 ((LEN NAME) (0 0) NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::STRIP-LEADING-PERCENT-FROM-SYMBOL-LIST"
 (NIL NIL NIL NIL (IF) NIL NIL)
 ((ACC) NIL (ENDP) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((SYM-LIST) NIL (CDR) (CONS) NIL NIL NIL)
 ((SYM-LIST ACC) NIL (STRIP-LEADING-PERCENT-FROM-SYMBOL) NIL NIL NIL NIL)
 (NIL NIL (CAR) NIL NIL NIL NIL) ((SYM-LIST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::PERCENTIFY"
 (NIL NIL NIL NIL (CONCATENATE) NIL NIL)
 (("%" NAME) NIL (QUOTE) NIL NIL NIL NIL) ((STRING) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::SUBLIS-FN!"
 (NIL NIL NIL NIL (MV-LET) NIL NIL)
 (NIL NIL (ERP) (ASSERT$) (SUBLIS-FN) NIL NIL)
 ((NEW-TERM ALIST TERM NIL NEW-TERM) NIL (NULL) NIL NIL NIL NIL)
 ((ERP) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::%F-IS-F-LEMMAS-REV"
 (NIL NIL NIL (LET*) NIL NIL NIL) (NIL NIL (SB-INT:QUASIQUOTE) NIL NIL NIL NIL)
 (NIL NIL
  (F-NAME %%F-NAME %%F F-BODY-IS-%F-BODY_S %%F-IS-F F-IS-%F NEW-THEORY RECP
   FORMALS %%F-FORMALS %F-FORMALS F-FORMALS EQUAL-BODIES)
  ((LOCAL
    (DEFTHEORY ,NEW-THEORY
               (UNION-THEORIES '(,F-IS-%F) (THEORY ',OLD-THEORY)))))
  NIL NIL NIL)
 ((,@(COND
      (RECP
       `((LOCAL
          (DEFTHM ,%%F-IS-F (EQUAL ,%%F-FORMALS ,F-FORMALS) :HINTS
                  (("Goal" :IN-THEORY
                    (UNION-THEORIES '((:INDUCTION ,%%F)) (THEORY ',OLD-THEORY))
                    :DO-NOT '(PREPROCESS) :EXPAND (,%%F-FORMALS ,F-FORMALS)
                    :INDUCT T))))
         (LOCAL
          (DEFUN ,%%F ,FORMALS
            ,@(CDR FORMALS-DECLS)
            ,(UNTRANSLATE (SUBLIS-FN! (LIST (CONS %F %%F)) TRANSLATED-NEW-BODY)
                          NIL WRLD)))))
      (EQUAL-BODIES NIL)
      (T
       `((LOCAL
          (DEFTHM ,F-BODY-IS-%F-BODY_S
                  (EQUAL ,UNTRANSLATED-NEW-BODY ,ORIG-BODY) :HINTS
                  (("Goal" :DO-NOT '(PREPROCESS))) :RULE-CLASSES NIL))))))
  NIL (SYMBOL-NAME PERCENTIFY CAR)
  (INTERN-IN-PACKAGE-OF-SYMBOL INTERN-IN-PACKAGE-OF-SYMBOL
                               INTERN-IN-PACKAGE-OF-SYMBOL
                               INTERN-IN-PACKAGE-OF-SYMBOL INTERN CONS CONS
                               CONS AND)
  NIL (DEFTHM) (GETPROP))
 ((F %F-NAME %%F-NAME %F %F %F %F "ACL2" %F NIL WRLD FORMALS-DECLS %%F FORMALS
   %F FORMALS F FORMALS ,F-IS-%F :HINTS
   ,(IF RECP
        `("Goal" :BY (:FUNCTIONAL-INSTANCE ,%%F-IS-F (,%%F ,%F)) :DO-NOT
          '(PREPROCESS) :EXPAND (,%F-FORMALS))
        `("Goal" :EXPAND
          ((:FREE ,FORMALS ,%F-FORMALS) (:FREE ,FORMALS ,F-FORMALS)) :IN-THEORY
          (THEORY ',OLD-THEORY) :DO-NOT '(PREPROCESS)
          ,@(AND (NOT EQUAL-BODIES) `(:USE ,F-BODY-IS-%F-BODY_S)))))
  NIL (QUOTE QUOTE NOT) (EQUAL EQUAL) (CONCATENATE) (CONCATENATE CONCATENATE)
  (CONCATENATE))
 ((F-NAME "-BODY-IS-" %F-NAME "-BODY_S" %%F-NAME "-IS-" F-NAME F-NAME "-IS-"
   %F-NAME "THEORY-" RECURSIVEP CURRENT-ACL2-WORLD RECP UNTRANSLATED-NEW-BODY
   ORIG-BODY ,F-FORMALS ,%F-FORMALS)
  NIL (QUOTE QUOTE QUOTE QUOTE) (COERCE) NIL NIL NIL)
 ((STRING STRING STRING STRING) NIL (QUOTE) (EXPLODE-ATOM) NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::GET-STATE-VALUE"
 (NIL NIL NIL NIL (IF) NIL NIL)
 ((NIL) NIL NIL (F-BOUNDP-GLOBAL F-GET-GLOBAL) NIL NIL NIL)
 ((SYM STATE SYM STATE) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::SIMPLIFY-REPEAT-LIMIT"
 (NIL NIL NIL (OR) NIL NIL NIL) (NIL (3) NIL (GET-STATE-VALUE) NIL NIL NIL)
 ((STATE) NIL (QUOTE) NIL NIL NIL NIL)
 ((ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::SIMPLIFY-INHIBIT"
 (NIL NIL NIL (LET) NIL NIL NIL)
 (((VAL (GET-STATE-VALUE 'SIMPLIFY-INHIBIT STATE))) NIL NIL NIL NIL (CASE) NIL)
 ((VAL) NIL ((T) (NIL) OTHERWISE) NIL NIL NIL NIL)
 ((NIL VAL) NIL (QUOTE) NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL (PROVE))
 ((PROOF-TREE WARNING OBSERVATION EVENT SUMMARY) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::SIMPLIFY-DEFUN"
 (NIL NIL NIL (LET*) NIL NIL NIL) (NIL NIL NIL ((FN (CADR DEF))) (IF) NIL NIL)
 (NIL NIL (NEW-FN ORIG-BODY) (EQ) (MV-LET) NIL NIL)
 ((NEW-FN FN NIL NIL LEMMAS COUNTER OLD-THEORY STATE) NIL
  (STRIP-LEADING-PERCENT-FROM-SYMBOL CAR) (ERP PPROGN) (IF) NIL NIL)
 ((FN SIMP STATE ERP) NIL (LAST) (LET*) NIL (MV-LET) (FMS))
 ((DEF "~x0" *STANDARD-CO* STATE NIL T ORIG-BODY NIL NIL T WRLD STATE) NIL
  (LIST SIMPLIFY-REPEAT-LIMIT SIMPLIFY-INHIBIT QUOTE QUOTE DECLARE) (ERP) NIL
  (ER) NIL)
 ((STATE STATE EQUAL ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL VAL STATE SOFT
   "Simplification failed for the definition of ~x0." FN T NIL NIL COUNTER
   OLD-THEORY STATE NIL NEW-COUNTER NEW-THEORY STATE)
  NIL
  (QUOTE UNTRANSLATED-NEW-BODY NEW-BODY-STRIPPED UNTRANSLATED-NEW-BODY-STRIPPED
   FORMALS-DECLS NEW-LEMMAS FIRST-NEW-LEMMA NEW-THEORY-P NEW-THEORY NEW-COUNTER
   SB-INT:QUASIQUOTE)
  (CONS IGNORE APPEND) NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::MUT-REC-FORMALS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((FORMALS) NIL (ENDP) (LET*) NIL NIL NIL)
 ((DEFS) NIL NIL ((DEF (CAR DEFS)) AND) NIL NIL NIL)
 ((FORMALS-OKP) NIL (NEW-FORMALS FORMALS-OKP)
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((NEW-FORMALS) NIL (CDR) (AND) (IF) NIL NIL)
 ((FORMALS DEFS) NIL (TRUE-LISTP CADDR) (EQUAL) (AND) NIL NIL)
 ((DEF DEF FORMALS NEW-FORMALS NEW-FORMALS) NIL (CONSP NULL) NIL NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::F-IS-%F-LIST"
 (NIL NIL NIL NIL (IF) NIL NIL)
 ((ACC) NIL (ENDP) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 ((DEFS FORMALS) NIL (CDR) (LET*) NIL NIL NIL)
 ((DEFS) NIL ((%F (CADAR DEFS))) NIL (IF) NIL NIL)
 ((ACC) NIL (F) (EQ CONS) NIL NIL NIL)
 ((%F F ACC) NIL (STRIP-LEADING-PERCENT-FROM-SYMBOL SB-INT:QUASIQUOTE) NIL NIL
  NIL NIL)
 ((%F) NIL NIL (EQUAL) NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::F-IS-%F-BASE-LEMMAS"
 (NIL NIL NIL NIL (IF) NIL NIL)
 ((ACC) NIL (ENDP) NIL NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL)
 ((F-IS-%F-LIST FORMALS ZP-FORMALS) NIL (CDR) (CONS) NIL NIL NIL)
 ((F-IS-%F-LIST ACC) NIL NIL (LET*) NIL NIL NIL)
 (NIL NIL (SB-INT:QUASIQUOTE) NIL ((EQUALITY (CAR F-IS-%F-LIST))) NIL NIL)
 (NIL NIL (F %F LEMMA-NAME LOCAL) NIL NIL NIL NIL)
 (NIL NIL (CAR CAR) (INTERN) NIL (DEFTHM) NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::F-IS-%F-INDUCTION-STEP-LEMMAS"
 (NIL NIL NIL NIL (IF) NIL NIL)
 ((ACC) NIL (ENDP) NIL NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL)
 ((F-IS-%F-LIST FORMALS HYP) NIL (CDR) (CONS) NIL NIL NIL)
 ((F-IS-%F-LIST ACC) NIL NIL (LET*) NIL NIL NIL)
 (NIL NIL (SB-INT:QUASIQUOTE) NIL NIL NIL ((EQUALITY (CAR F-IS-%F-LIST))))
 (NIL NIL (F %F LEMMA-NAME F-FORMALS %F-FORMALS LOCAL) NIL NIL NIL NIL)
 (NIL NIL (CAR CAR) (INTERN CONS CONS) NIL (DEFTHM) NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::F-IS-%F-LEMMAS-MUT-REC"
 (NIL NIL NIL NIL (IF) NIL NIL)
 ((ACC) NIL (ENDP) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 ((F-IS-%F-LIST FORMALS) NIL (CDR) (CONS) NIL NIL NIL)
 ((F-IS-%F-LIST ACC) NIL NIL (LET*) NIL NIL NIL)
 (NIL NIL (SB-INT:QUASIQUOTE) NIL ((EQUALITY (CAR F-IS-%F-LIST))) NIL NIL)
 (NIL NIL (F %F LEMMA-NAME) NIL NIL (DEFTHM) NIL)
 ((,LEMMA-NAME :HINTS ("Goal" :DO-NOT '(PREPROCESS))) NIL (CAR CAR)
  (INTERN EQUAL) NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::MUTUAL-RECURSION-LEMMAS"
 (NIL NIL NIL (LET*) NIL NIL NIL) (NIL NIL (SB-INT:QUASIQUOTE) NIL NIL NIL NIL)
 (NIL NIL
  (%%P %%P-FORMALS %%P-PROPERTY %%P-BASE %%P-INDUCTION-STEP NOT-ZP-FORMAL
   FORMAL %%P-FORMAL-MINUS-1 INDUCTION-HYP %%P-HOLDS %%P-IMPLIES-F-IS-%F-THEORY
   NEW-THEORY)
  NIL NIL NIL NIL)
 (NIL NIL
  (SB-INT:QUASIQUOTE CAR SB-INT:QUASIQUOTE SB-INT:QUASIQUOTE LOCAL LOCAL LOCAL
   LOCAL LOCAL LOCAL)
  (INTERN CONS INTERN INTERN INTERN INTERN INTERN INTERN) (ENCAPSULATE) NIL
  NIL)
 ((%%P-NAME "ACL2" %%P FORMALS "ACL2" "ACL2" "ACL2" FORMALS "ACL2" "ACL2"
   "ACL2" NIL ,@(F-IS-%F-LEMMAS-MUT-REC F-IS-%F-LIST FORMALS NIL))
  NIL (NOT ,%%P LOCAL) (AND DEFTHEORY)
  (CONCATENATE CONCATENATE CONCATENATE CONCATENATE CONCATENATE CONCATENATE)
  (DEFTHM ENCAPSULATE DEFTHM DEFUN) (ENCAPSULATE))
 ((%%P-NAME "-PROPERTY" %%P-NAME "-BASE" %%P-NAME "-INDUCTION_STEP"
   ,NOT-ZP-FORMAL ,%%P-FORMAL-MINUS-1 %%P-NAME "-HOLDS" %%P-NAME
   "-IMPLIES-F-IS-%F-THEORY" "THEORY-" ,%%P-HOLDS ,%%P-FORMALS :HINTS
   ("Goal" :INDUCT (%%SUB1-INDUCTION ,@FORMALS) :DO-NOT '(PREPROCESS)
    :IN-THEORY
    (UNION-THEORIES
     '(,%%P-BASE ,%%P-INDUCTION-STEP (:INDUCTION %%SUB1-INDUCTION))
     (THEORY 'MINIMAL-THEORY)))
   NIL ,@(F-IS-%F-INDUCTION-STEP-LEMMAS F-IS-%F-LIST FORMALS INDUCTION-HYP NIL)
   NIL ,@(F-IS-%F-BASE-LEMMAS F-IS-%F-LIST FORMALS `(ZP ,@FORMALS) NIL)
   ,%%P-IMPLIES-F-IS-%F-THEORY ,%%P-PROPERTY :HINTS
   ("Goal" :IN-THEORY (UNION-THEORIES '(,%%P) (THEORY 'MINIMAL-THEORY))) ,%%P
   ,FORMALS)
  NIL
  (QUOTE QUOTE QUOTE ZP 1- QUOTE QUOTE QUOTE IN-THEORY LOCAL LOCAL LOCAL
   DECLARE %%AND-TREE)
  (COERCE UNION-THEORIES IMPLIES) NIL (DEFTHM DEFTHM) NIL)
 ((STRING STRING STRING ,@FORMALS ,FORMAL STRING STRING STRING
          ,%%P-INDUCTION-STEP :INSTRUCTIONS ,%%P-BASE :INSTRUCTIONS
          ,@F-IS-%F-LIST)
  NIL (QUOTE IN-THEORY DEFLABEL IN-THEORY THEORY ,%%P %%AND-TREE)
  (EXPLODE-ATOM UNION-THEORIES IMPLIES :PROMOTE IMPLIES :PROMOTE
                SET-DIFFERENCE-THEORIES XARGS)
  NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::MY-TRANSLATE-RULE-CLASS-ALIST"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((NULL ALIST) T) NIL NIL NIL NIL)
 (NIL NIL (VALUE) (ER-LET*) NIL NIL NIL)
 (((VAL
    (CASE (CAR ALIST)
      (:COROLLARY (VALUE COROLLARY))
      (:HINTS (VALUE NIL))
      (:INSTRUCTIONS (VALUE NIL))
      (:OTF-FLG (VALUE (CADR ALIST)))
      (:TRIGGER-FNS
       (VALUE
        (REVERSE (STRIP-LEADING-PERCENT-FROM-SYMBOL-LIST (CADR ALIST) NIL))))
      (:TRIGGER-TERMS
       (ER-LET*
        ((TERMS (TRANSLATE-TERM-LST (CADR ALIST) T T T CTX WRLD STATE)))
        (VALUE (STRIP-PERCENTS-LST TERMS NIL))))
      (:TYPED-TERM
       (ER-LET* ((TERM (TRANSLATE (CADR ALIST) T T T CTX WRLD STATE)))
                (VALUE (STRIP-PERCENTS TERM))))
      (:BACKCHAIN-LIMIT-LST (VALUE (CADR ALIST)))
      (:MATCH-FREE (VALUE (CADR ALIST)))
      (:CLIQUE
       (LET ((CLIQUE
              (COND ((NULL (CADR ALIST)) NIL)
                    ((ATOM (CADR ALIST))
                     (STRIP-LEADING-PERCENT-FROM-SYMBOL (CADR ALIST)))
                    (T
                     (STRIP-LEADING-PERCENT-FROM-SYMBOL-LIST (CADR ALIST)
                      NIL)))))
         (VALUE CLIQUE)))
      (:TYPE-SET (VALUE (CADR ALIST)))
      (OTHERWISE
       (ER SOFT CTX "The key ~x0 is not yet implemented for rule class ~
                   translation."
           (CAR ALIST))))))
  NIL NIL (ALIST-TO-KEYWORD-ALIST) NIL NIL NIL)
 ((SEEN NIL TOKEN ORIG-NAME COROLLARY CTX WRLD STATE) NIL (CDDR) NIL (IF) NIL
  NIL)
 ((ALIST VAL SEEN) NIL NIL (LET) NIL NIL NIL)
 (((NEW-SEEN (CONS (CONS (CAR ALIST) VAL) SEEN))) NIL NIL NIL (IF) NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::MY-TRANSLATE-RULE-CLASS1"
 (NIL NIL NIL (LET) NIL NIL NIL)
 (((ORIG-COROLLARY (CADR (ASSOC-KEYWORD :COROLLARY (CDR CLASS))))) NIL NIL
  (ER-LET*) NIL NIL NIL)
 (NIL NIL
  ((COROLLARY
    (COND (ORIG-COROLLARY (TRANSLATE ORIG-COROLLARY T T T CTX WRLD STATE))
          (T (VALUE NIL))))
   VALUE)
  NIL NIL NIL NIL)
 (NIL NIL (ALIST) (CONS) NIL NIL NIL) ((ALIST) NIL (CAR) NIL NIL NIL NIL)
 ((NIL NAME CTX WRLD STATE CLASS) NIL (CAR CDR) (AND) NIL NIL NIL)
 ((CLASS CLASS COROLLARY) NIL NIL NIL (UNTRANSLATE) NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::MY-TRANSLATE-RULE-CLASS"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((SYMBOLP X) T) NIL NIL NIL NIL)
 (NIL NIL (VALUE) NIL NIL NIL (MY-TRANSLATE-RULE-CLASS1))
 ((X NAME X CTX WRLD STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::MY-TRANSLATE-RULE-CLASSES1"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM CLASSES) T) NIL NIL NIL NIL)
 (NIL NIL (VALUE) (ER-LET*) NIL NIL NIL)
 ((NIL) NIL
  ((CLASS (MY-TRANSLATE-RULE-CLASS NAME (CAR CLASSES) CTX WRLD STATE)) VALUE)
  NIL NIL NIL NIL)
 (NIL NIL (RST) (CONS) NIL NIL NIL)
 ((CLASS RST) NIL NIL NIL NIL NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL))
 ((NAME CTX WRLD STATE) NIL (CDR) NIL NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::MY-TRANSLATE-RULE-CLASSES"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM CLASSES) T) NIL NIL NIL NIL)
 (NIL NIL (VALUE) NIL NIL NIL (MY-TRANSLATE-RULE-CLASSES1))
 ((CLASSES NAME CLASSES CTX WRLD STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::STRIP-PERCENTS-FROM-LEMMA"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((LEMMA) NIL ((DEFTHM NAME FORMULA . OTHER) &) NIL NIL NIL NIL)
 (NIL NIL (VALUE) (COND) NIL NIL NIL)
 ((NIL) NIL ((MEMBER-EQ DEFTHM '(DEFTHM DEFTHMD)) T) NIL NIL NIL NIL)
 (NIL NIL (VALUE) (LET) NIL NIL NIL)
 (((NEW-NAME (STRIP-LEADING-PERCENT-FROM-SYMBOL NAME)) NIL) NIL NIL NIL (IF)
  NIL NIL)
 (NIL NIL (VALUE) (EQ LET) NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::STRIP-PERCENTS-FROM-LEMMAS"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL (ENDP VALUE) (ER-LET*) NIL NIL NIL)
 ((LEMMAS (NEW-LEMMA (STRIP-PERCENTS-FROM-LEMMA (CAR LEMMAS) CTX WRLD STATE)))
  NIL (REVERSE) NIL NIL NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL))
 ((ACC CTX WRLD STATE) NIL (CDR) NIL (IF) NIL NIL)
 ((LEMMAS NEW-LEMMA ACC) NIL NIL (CONS) NIL NIL NIL)
 ((NEW-LEMMA ACC) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::SIMPLIFY-DEFUNS"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ENDP DEFS) T) NIL NIL NIL NIL)
 (NIL NIL NIL (LET) (MV-LET) NIL NIL)
 (((FORMALS (MUT-REC-FORMALS ALL-DEFS NIL))) NIL NIL NIL (IF IF) NIL (ERP))
 ((FORMALS DEF NEW-LEMMAS COUNTER NEW-THEORY STATE LEMMAS COUNTER OLD-THEORY
           ENS WRLD STATE ERP)
  NIL 'CAR (LET*) NIL (MV-LET) NIL)
 ((MUT-REC DEFS T NIL NIL COUNTER NEW-THEORY STATE ALL-DEFS NEW-LEMMAS COUNTER
   NEW-THEORY ENS WRLD STATE)
  NIL
  ((NEW-LEMMAS
    (MUTUAL-RECURSION-LEMMAS FORMALS (F-IS-%F-LIST ALL-DEFS FORMALS NIL)
     COUNTER OLD-THEORY))
   DECLARE CDR)
  (ERP) (IF) (ER) NIL)
 ((NIL STATE VAL STATE SOFT
   "Did not find a unique singleton list of formals for the ~
                     mutual-recursion nest starting with:~%~x0."
   T NIL NIL COUNTER OLD-THEORY STATE DEFS DEF ACC)
  NIL (NEW-DEFTHEORY 1+ CADR QUOTE CAR) (CONS APPEND IGNORE CONS) NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::SIMPLIFY-FORM"
 (NIL NIL NIL (LET) NIL NIL NIL)
 (((CAR-FORM (AND (CONSP FORM) (CAR FORM)))) NIL NIL NIL NIL NIL (CASE))
 ((CAR-FORM) NIL ((DEFUN DEFUND) MUTUAL-RECURSION DEFUNS OTHERWISE) NIL NIL NIL
  NIL)
 (NIL NIL NIL NIL NIL (MV-LET) NIL)
 ((NIL FORM LEMMAS COUNTER OLD-THEORY ENS WRLD STATE NIL LEMMAS COUNTER
   OLD-THEORY ENS WRLD STATE NIL NIL LEMMAS COUNTER OLD-THEORY STATE)
  NIL (CDR CDR DECLARE) (ERP) (ER) NIL NIL)
 ((FORM FORM VAL STATE SOFT "Simplify-form does not yet handle DEFUNS, but it ~
                           could."
   T NIL NIL COUNTER OLD-THEORY STATE)
  NIL (QUOTE) (IGNORE) NIL NIL NIL)
 ((ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL ERP VAL) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::SIMPLIFY-FORMS"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ENDP FORMS) T) NIL NIL NIL NIL)
 (NIL NIL NIL (PPROGN) (MV-LET) NIL NIL)
 (NIL NIL NIL (NEWLINE) (COND) (MV) (ERP))
 ((*STANDARD-CO* STATE NIL STATE SIMP-FORM LEMMAS NEW-COUNTER NEW-THEORY STATE
   LEMMAS COUNTER OLD-THEORY ENS WRLD STATE)
  NIL (REVERSE CAR ERP SIMP-FORM T) NIL (CASE-MATCH) NIL NIL)
 ((DEFS LEMMAS FORMS) NIL ((('LOCAL ('DEFTHEORY . &)) . &) &) NIL NIL (MV) NIL)
 ((LEMMAS T NIL NIL STATE LEMMAS NEW-COUNTER NEW-THEORY ENS WRLD STATE DEFS
   LEMMAS NEW-COUNTER NEW-THEORY ENS WRLD STATE)
  NIL (CDR CDR CDR) (CONS) NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::FINAL-DEFTHEORY-1"
 (NIL NIL NIL NIL NIL (COND) NIL)
 (NIL NIL
  ((ENDP LEMMAS) (EQ (CAAR LEMMAS) 'DEFTHM) (EQ (CAAR LEMMAS) 'ENCAPSULATE) T)
  NIL NIL NIL NIL)
 ((ACC) NIL NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL)
 ((ACC) NIL (CDR CDR CDR) (CONS ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL NIL)
 ((LEMMAS ACC LEMMAS ACC LEMMAS) NIL (CADAR CDDAR) NIL NIL NIL NIL)
 ((LEMMAS LEMMAS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::FINAL-DEFTHEORY"
 (NIL NIL (SB-INT:QUASIQUOTE) NIL NIL NIL NIL)
 (NIL NIL NIL (DEFTHEORY) NIL NIL NIL)
 ((%-REMOVAL-THEORY) NIL NIL (UNION-THEORIES) NIL NIL NIL)
 (NIL NIL 'THEORY NIL NIL NIL NIL)
 ((,(FINAL-DEFTHEORY-1 LEMMAS NIL)) NIL (QUOTE) NIL NIL NIL NIL)
 ((MINIMAL-THEORY) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::INITIAL-EQUALITY-EVENTS"
 (NIL NIL (IN-DEFS) NIL NIL NIL NIL) ((OUT-DEFS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::WRITE-LEMMA-FILE"
 (NIL NIL NIL (ER-LET*) NIL NIL NIL)
 (NIL NIL ((IN-LEMMAS (READ-LIST INFILE CTX STATE))) NIL NIL (WRITE-LIST) NIL)
 ((OUTFILE CTX STATE) NIL (OUT-LEMMAS) (CONS) NIL NIL NIL)
 (NIL NIL (CAR) (APPEND) NIL NIL (STRIP-PERCENTS-FROM-LEMMAS))
 ((IN-LEMMAS NIL CTX STATE IN-LEMMAS INITIAL-EVENTS OUT-LEMMAS) NIL (W) NIL NIL
  NIL NIL)
 ((STATE) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::WRITE-LEMMA-FILES"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL (ENDP) NIL (MV) (MV-LET) NIL)
 ((THM-FILE-PAIRS ERP NIL STATE) NIL (DECLARE) (ERP) NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (WRITE-LEMMA-FILE))
 ((VAL STATE CTX STATE ERP CTX STATE) NIL (CAAR CADAR CDDAR IGNORE CDR) NIL NIL
  NIL NIL)
 ((THM-FILE-PAIRS THM-FILE-PAIRS THM-FILE-PAIRS VAL THM-FILE-PAIRS) NIL NIL NIL
  NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/simplify-defuns.lisp::TRANSFORM-DEFUNS-FN"
 (NIL NIL NIL (LET) NIL NIL NIL)
 (NIL NIL ((CTX 'TRANSFORM-DEFUNS)) NIL (MV-LET) NIL NIL)
 (NIL NIL (FIRST-LEMMA) (ERP) (READ-LIST IF) NIL NIL)
 ((IN-DEFS STATE IN-DEFS-FILE CTX STATE ERP) NIL 'SILENT-ERROR NIL (MV-LET) NIL
  NIL)
 ((STATE) NIL (LOCAL) NIL (ERP IF IF) NIL NIL)
 ((OUT-DEFS LEMMAS STATE ERP) NIL (SILENT-ERROR) (DEFTHEORY OR) (ER-PROGN) (MV)
  NIL)
 ((THEORY-0 OUT-DEFS-FILE EQUALITIES-FILE IN-DEFS NIL STATE NIL NIL NIL STATE
   STATE)
  (0) (THEORY LIST QUOTE ENS W) NIL (IF IF) (WRITE-LEMMA-FILES) NIL))
