("/home/acl2/books/xdoc/book-thms.lisp::NEWLY-DEFINED-TOP-LEVEL-THMS-REC"
 (NIL NIL NIL NIL NIL NIL (COND))
 (NIL NIL
  ((ENDP TRIPS)
   (AND (EQ (CAAR TRIPS) 'INCLUDE-BOOK-PATH) (EQ (CADAR TRIPS) 'GLOBAL-VALUE))
   (NOT COLLECT-P)
   (EQ (CADAR TRIPS)
       (IF TRANSLATED-P
           'THEOREM
           'UNTRANSLATED-THEOREM))
   T)
  NIL NIL NIL NIL)
 ((ACC) NIL NIL NIL NIL NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL))
 ((FULL-BOOK-NAME ACC TRANSLATED-P NIL FULL-BOOK-NAME ACC TRANSLATED-P
   COLLECT-P FULL-BOOK-NAME TRANSLATED-P COLLECT-P FULL-BOOK-NAME ACC
   TRANSLATED-P)
  NIL (CDR CDR CDR CDR) (EQUAL) (ACONS) NIL NIL)
 ((TRIPS FULL-BOOK-NAME TRIPS TRIPS ACC TRIPS) NIL (CAR CAAR CDDAR) NIL NIL NIL
  NIL)
 ((TRIPS TRIPS) NIL (CDDAR) NIL NIL NIL NIL) ((TRIPS) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/xdoc/book-thms.lisp::REVERSED-WORLD-SINCE-EVENT"
 (NIL NIL NIL (COND) NIL NIL NIL)
 (NIL NIL
  ((OR (ENDP WRLD)
       (LET ((TRIP (CAR WRLD)))
         (AND (EQ (CAR TRIP) 'EVENT-LANDMARK) (EQ (CADR TRIP) 'GLOBAL-VALUE)
              (EQUAL (ACCESS-EVENT-TUPLE-FORM (CDDR TRIP)) EV))))
   T)
  NIL NIL NIL NIL)
 ((ACC) NIL NIL NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 ((EV) NIL (CDR) (CONS) NIL NIL NIL) ((WRLD ACC) NIL (CAR) NIL NIL NIL NIL)
 ((WRLD) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/xdoc/book-thms.lisp::REVERSED-WORLD-SINCE-BOOT-STRAP"
 (NIL NIL NIL NIL (REVERSED-WORLD-SINCE-EVENT) NIL NIL)
 ((WRLD NIL) NIL (QUOTE) NIL NIL NIL NIL)
 ((EXIT-BOOT-STRAP-MODE) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/xdoc/book-thms.lisp::BOOK-THMS-FN"
 (NIL NIL NIL (BOOK-NAME) NIL NIL NIL)
 ((TRANSLATED-P STATE) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/xdoc/book-thms.lisp::THEOREMS-INTRODUCED-IN"
 (NIL NIL (BOOK-NAME) NIL NIL NIL NIL) ((STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/xdoc/book-thms.lisp::NEW-FORMULA-INFO1"
 (NIL NIL NIL (LET) NIL NIL NIL) (NIL NIL ((NAME (CAR TRIP))) NIL NIL NIL NIL)
 (NIL NIL
  (PROP CADR THEOREM UNNORMALIZED-BODY CONSTRAINT-LST DEFCHOOSE-AXIOM
   GLOBAL-VALUE T)
  NIL NIL NIL NIL)
 ((TRIP ACC) NIL (CDDR) (CONS COND COND CONS) (IF) NIL NIL)
 ((TRIP ACC ACC ACC) NIL
  ((EQ (GETPROP NAME 'CONSTRAINT-LST T 'CURRENT-ACL2-WORLD WRLD) T) T
   (AND PROP (SYMBOLP PROP)) T)
  (AND LET) (LIST LIST) NIL NIL)
 ((NAME :THEOREM PROP ACC ACC NAME :DEFCHOOSE
   (FORM (ACCESS-EVENT-TUPLE-FORM PROP)))
  NIL NIL (CONS CONS EQ EQ) (UNTRANSLATE IF) NIL NIL)
 ((ACC ACC PROP T WRLD NAME ACC) NIL (QUOTE ACCESS-EVENT-TUPLE-TYPE QUOTE)
  (CONS) (LIST LIST) (AND) NIL))
("/home/acl2/books/xdoc/book-thms.lisp::NEW-FORMULA-INFO"
 (NIL NIL NIL NIL (IF) NIL NIL) ((ACC) NIL (ENDP) (LET) NIL NIL NIL)
 ((TRIPS (ACC (NEW-FORMULA-INFO1 (CAR TRIPS) WRLD ACC))) NIL NIL NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 ((WRLD ACC) NIL (CDR) NIL NIL NIL NIL) ((TRIPS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
