("/home/acl2/books/arithmetic/factorial.lisp::FACTORIAL"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL (1) (ZP) (*) NIL NIL NIL)
 ((N N) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL NIL)
 (NIL NIL (1-) NIL NIL NIL NIL) ((N) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
