("/home/acl2/books/misc/int-division.lisp::INTEGER-QUOTIENT"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL NIL (AND) (IF) NIL NIL)
 (NIL NIL (INTEGERP INTEGERP) (EQUAL) (IF IF) NIL NIL)
 ((A B A NIL NIL) (0 1) (INTEGERP) (EQUAL /) NIL NIL NIL)
 ((B B A) (0) NIL (/) NIL NIL NIL) ((B A) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/int-division.lisp::DIVIDES"
 (NIL NIL NIL NIL (AND) NIL NIL)
 (NIL NIL (INTEGERP INTEGERP) (EQUAL) NIL NIL NIL)
 ((A B B) NIL NIL (*) NIL NIL NIL) ((A) NIL NIL (INTEGER-QUOTIENT) NIL NIL NIL)
 ((A B) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
