("/home/acl2/books/make-event/acl2x-help.lisp::ACL2X-REPLACE-FN"
 (NIL NIL (SB-INT:QUASIQUOTE) NIL NIL NIL NIL)
 (NIL NIL (MAKE-EVENT) NIL NIL NIL NIL) (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL
  ((NOT (F-GET-GLOBAL 'CERTIFY-BOOK-INFO STATE))
   (NOT (F-GET-GLOBAL 'WRITE-ACL2X STATE)) T)
  NIL NIL NIL NIL)
 (NIL NIL (QUOTE QUOTE QUOTE) NIL NIL NIL NIL)
 ((,OUTSIDE-CERTIFICATION ,SINGLE-PASS) NIL NIL (PROGN) NIL NIL NIL)
 ((,PASS1) NIL (VALUE-TRIPLE) NIL NIL NIL NIL))
("/home/acl2/books/make-event/acl2x-help.lisp::ACL2X-EXPANSION-ALIST-REPLACEMENT1"
 (NIL NIL NIL (ALIST) NIL NIL NIL) ((ACC STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/make-event/acl2x-help.lisp::ACL2X-EXPANSION-ALIST-REPLACEMENT"
 (NIL NIL (ALIST) NIL NIL NIL NIL) ((STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
