("/home/acl2/books/arithmetic-5/lib/basic-ops/mini-theories.lisp::PREDICATE-P"
 (NIL NIL NIL (AND) NIL NIL NIL) (NIL NIL (CONSP) (MEMBER) NIL NIL NIL)
 ((TERM) NIL (CAR QUOTE) NIL NIL NIL NIL) ((TERM) NIL NIL NIL NIL (EQUAL) NIL)
 ((< INTEGERP RATIONALP COMPLEX-RATIONALP) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
