("/home/acl2/books/tools/remove-hyps.lisp::REMOVE-HYPS-FORMULA-STEPS"
 (NIL NIL NIL (MIN) NIL NIL NIL)
 ((*DEFAULT-STEP-LIMIT*) NIL NIL (+) NIL NIL NIL)
 (NIL (1000) NIL (*) NIL NIL NIL) ((STEPS) (3) NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/remove-hyps.lisp::DUMB-IMPLICATE"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL ((NULL HYPS) (NULL (CDR HYPS)) T) NIL NIL NIL NIL)
 ((CONCL) NIL `SB-INT:QUASIQUOTE NIL NIL NIL NIL)
 (NIL NIL NIL (IMPLIES IMPLIES) NIL NIL NIL)
 ((,(CAR HYPS) ,CONCL ,CONCL) NIL (AND) NIL NIL NIL NIL)
 ((,@HYPS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/remove-hyps.lisp::MAKE-DEFTHM"
 (NIL NIL NIL (LET*) NIL NIL NIL)
 (NIL NIL ((FORM0 (DUMB-IMPLICATE HYPS CONCL))) NIL (IF) NIL NIL)
 (NIL NIL (FORM NULL SB-INT:QUASIQUOTE) (ASSERT$) NIL NIL NIL)
 ((NAME) NIL (SB-INT:QUASIQUOTE) (EQ) (IF ,DEFT) NIL NIL)
 ((BINDINGS FORM0 DEFT ,NAME ,FORM ,@KWD-ALIST) NIL `QUOTE (THM) NIL NIL NIL)
 ((THM ,FORM ,@KWD-ALIST) NIL NIL NIL (,LET/LET*) NIL NIL)
 ((,BINDINGS ,FORM0) NIL (DECLARE) NIL NIL NIL NIL))
("/home/acl2/books/tools/remove-hyps.lisp::EVENT-STEPS"
 (NIL NIL NIL (LET) NIL NIL NIL)
 (((NEW-FORM
    `(WITH-OUTPUT :STACK :PUSH :OFF :ALL :GAG-MODE NIL
                  (PROGN
                   (MAKE-EVENT
                    (PPROGN (F-PUT-GLOBAL 'OUR-STEPS NIL STATE)
                            (VALUE '(VALUE-TRIPLE NIL))))
                   ,(IF VERBOSE-P
                        `(WITH-OUTPUT :STACK :POP ,FORM)
                        FORM)
                   (MAKE-EVENT
                    (PPROGN
                     (F-PUT-GLOBAL 'OUR-STEPS (OR (LAST-PROVER-STEPS STATE) 1)
                                   STATE)
                     ,@EXTRA-FORMS (VALUE '(VALUE-TRIPLE NIL))))
                   (DEFCONST *BAD*)))))
  NIL NIL (ER-PROGN) NIL NIL NIL)
 (NIL NIL (VALUE) NIL NIL (TRANS-EVAL) NIL)
 ((NEW-FORM STATE T) NIL (QUOTE) (F-GET-GLOBAL) NIL NIL NIL)
 ((ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL STATE) NIL (QUOTE) NIL NIL NIL NIL)
 ((OUR-STEPS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/remove-hyps.lisp::REMOVE-HYPS-FORMULA-1"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL
  ((ENDP REST-HYPS)
   (AND (CONSP (CAR REST-HYPS))
        (MEMBER-EQ (CAAR REST-HYPS) '(SYNTAXP BIND-FREE SYNP)))
   T)
  NIL NIL NIL NIL)
 (NIL NIL (VALUE) (LET) NIL NIL NIL)
 ((NAME CONCL KWD-ALIST LET/LET* BINDINGS STEPS VERBOSE-P STATE
   (FORM
    `(WITH-PROVER-STEP-LIMIT ,STEPS
                             ,(MAKE-DEFTHM 'DEFTHM NAME
                               (REVAPPEND REV-INIT-HYPS (CDR REST-HYPS)) CONCL
                               KWD-ALIST LET/LET* BINDINGS))))
  NIL (REVERSE CDR) (CONS ER-LET*) NIL NIL NIL)
 ((REV-INIT-HYPS REV-INIT-HYPS REST-HYPS
   (EVENT-STEPS (EVENT-STEPS FORM VERBOSE-P NIL STATE)))
  NIL (CAR) NIL NIL NIL NIL)
 ((REST-HYPS NAME CONCL KWD-ALIST LET/LET* BINDINGS STEPS VERBOSE-P STATE) NIL
  (CDR) (COND) NIL NIL NIL)
 ((REST-HYPS) NIL ((NULL EVENT-STEPS) T) NIL NIL NIL NIL))
("/home/acl2/books/tools/remove-hyps.lisp::REMOVE-HYPS-FORMULA"
 (NIL NIL NIL NIL (DO-PROOFS?) NIL NIL) ((T NIL) NIL NIL NIL (MV-LET) NIL NIL)
 (NIL NIL NIL (THMP ASSERT$ ER-LET*) NIL NIL NIL)
 ((NAME2 KWD-ALIST+
   (STEPS
    (EVENT-STEPS
     (IF THMP
         `(DEFTHM ,NAME2 ,@(CDR FORM) :RULE-CLASSES NIL)
         FORM)
     VERBOSE-P NIL STATE)))
  NIL NIL (IFF COND) (IF) NIL NIL)
 (NIL NIL (NULL NULL (NULL STEPS) T) (EQ) (MV MV) NIL NIL)
 ((NAME NAME T NIL NAME KWD-ALIST) NIL (CAR QUOTE)
  (GEN-NEW-NAME APPEND ER-LET*) (ER) NIL NIL)
 ((FORM THM KWD-ALIST SOFT CTX "Original theorem failed!"
   (FINAL-HYPS
    (REMOVE-HYPS-FORMULA-1 NAME2 NIL HYPS CONCL KWD-ALIST+ LET/LET* BINDINGS
     (REMOVE-HYPS-FORMULA-STEPS STEPS) VERBOSE-P STATE)))
  NIL (QUOTE W QUOTE VALUE) NIL NIL NIL NIL))
("/home/acl2/books/tools/remove-hyps.lisp::REMOVE-HYPS-FN"
 (NIL NIL (SB-INT:QUASIQUOTE) NIL NIL NIL NIL)
 (NIL NIL (MAKE-EVENT) NIL NIL NIL NIL) (NIL NIL NIL (ER-LET*) NIL NIL NIL)
 (NIL NIL
  ((NEW-FORM
    (REMOVE-HYPS-FORMULA ',FORM ',NAME ',HYPS ',CONCL ',KWD-ALIST ',LET/LET*
     ',BINDINGS ',VERBOSE-P 'REMOVE-HYPS STATE)))
  (PPROGN) NIL NIL NIL)
 (NIL NIL (THMP VALUE) (COND) NIL NIL NIL)
 (NIL NIL (VALUE (NULL NEW-FORM) T) NIL (IF) NIL NIL)
 ((THMP) NIL (QUOTE) (EQ) NIL NIL (FMS FMS)))
