("/home/acl2/books/std/util/defredundant.lisp::GET-EVENT-TUPLE"
 (NIL NIL NIL (B*) NIL NIL NIL) (NIL NIL NIL (COND) NIL NIL NIL)
 (NIL NIL
  (EV-WORLD (UNLESS (CONSP EV-WORLD)) LANDMARK
   (UNLESS
       (AND (CONSP LANDMARK) (EQ (FIRST LANDMARK) 'EVENT-LANDMARK)
            (EQ (SECOND LANDMARK) 'GLOBAL-VALUE)))
   TUPLE FORM (AND (CONSP FORM) (EQ (CAR FORM) 'VERIFY-TERMINATION-BOOT-STRAP))
   T)
  NIL NIL NIL NIL)
 ((TUPLE) NIL (CAR CDDR ACCESS-EVENT-TUPLE-FORM)
  (DECODE-LOGICAL-NAME RAISE RAISE ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL)
 ((NAME WORLD "Not a logical name: ~x0." NAME EV-WORLD
   "Expected (EVENT-LANDMARK GLOBAL-VALUE . <event-tuple>) but found ~x0."
   LANDMARK LANDMARK TUPLE NAME)
  NIL (SCAN-TO-EVENT) NIL NIL NIL NIL)
 (NIL NIL (CDR) NIL NIL NIL NIL) ((EV-WORLD) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defredundant.lisp::RUNES-TO-E/DS"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (NIL NIL NIL NIL NIL
  (((WHEN (ATOM RUNES)) (MV ENABLES DISABLES))
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL)
 ((ENABLES STATE) NIL (RUNE1 ENS ENABLED1 (WHEN ENABLED1) CDR) (CONS) NIL NIL
  NIL)
 ((RUNES RUNE1 DISABLES) NIL (CAR ENS ACTIVE-RUNEP) NIL NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL)
 ((RUNES STATE RUNE1 DISABLES STATE) NIL (CDR) (CONS) NIL NIL NIL)
 ((RUNES RUNE1 ENABLES) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defredundant.lisp::NAME-TO-E/DS"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (NIL NIL
  ((RUNIC-MAPPING-PAIRS
    (GETPROP NAME 'RUNIC-MAPPING-PAIRS NIL 'CURRENT-ACL2-WORLD (W STATE))))
  NIL NIL (RUNES-TO-E/DS) NIL)
 ((RUNES NIL NIL STATE) NIL (RUNES) NIL NIL NIL NIL)
 (NIL NIL (STRIP-CDRS) NIL NIL NIL NIL)
 ((RUNIC-MAPPING-PAIRS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defredundant.lisp::NAMES-TO-E/DS"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (NIL NIL NIL (((WHEN (ATOM NAMES)) (MV NIL NIL)) MV) NIL NIL NIL)
 (NIL NIL ((MV ES1 DS1) (MV ES2 DS2)) (APPEND APPEND) NIL NIL NIL)
 ((ES1 ES2 DS1 DS2) NIL NIL
  (NAME-TO-E/DS ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((STATE STATE) NIL (CAR CDR) NIL NIL NIL NIL)
 ((NAMES NAMES) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defredundant.lisp::REDUNDANT-CLEAN-UP-XARGS"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (NIL NIL NIL NIL (LIST*) ((?__FUNCTION__ 'REDUNDANT-CLEAN-UP-XARGS)) NIL)
 ((KWD VAL) NIL
  ((WHEN (ATOM X)) (WHEN (ATOM (CDR X))) (LIST* KWD VAL REST)
   (WHEN
       (MEMBER KWD
               '(:MEASURE :MODE :VERIFY-GUARDS :GUARD-DEBUG :GUARD-HINTS :HINTS
                 :OTF-FLG)))
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 ((NIL X REST) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (RAISE) NIL NIL
  NIL)
 (("Invalid xargs... ~x0" X REST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defredundant.lisp::REDUNDANT-CLEAN-UP-DECL-ARGS"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (NIL NIL NIL (RAISE) NIL NIL ((?__FUNCTION__ 'REDUNDANT-CLEAN-UP-DECL-ARGS)))
 (("Bad form in declare: ~x0" X) NIL
  ((WHEN (ATOM X)) (CONS ARG1 REST) (UNLESS (CONSP ARG1))
   (WHEN (MEMBER-EQ (CAR ARG1) '(TYPE IGNORE IGNORABLE IRRELEVANT OPTIMIZE)))
   (WHEN (EQ (CAR ARG1) 'XARGS)))
  NIL NIL NIL NIL)
 ((NIL X) NIL NIL (RAISE CONS CONS) NIL NIL NIL)
 (("Bad form in declare: ~x0" X ARG1) NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  (CONS) NIL NIL NIL)
 ((REST REST) NIL 'REDUNDANT-CLEAN-UP-XARGS NIL NIL NIL NIL)
 ((XARGS) NIL (CDR) NIL NIL NIL NIL))
("/home/acl2/books/std/util/defredundant.lisp::REDUNDANT-CLEAN-UP-DECLS"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (NIL NIL NIL (CONS) NIL NIL ((?__FUNCTION__ 'REDUNDANT-CLEAN-UP-DECLS)))
 (NIL NIL
  ((WHEN (ATOM X)) (CONS DECL1 REST) (WHEN (STRINGP DECL1))
   (UNLESS (AND (CONSP DECL1) (EQ (CAR DECL1) 'DECLARE))) DECL1-ARGS
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  (CONS) NIL NIL NIL)
 ((NIL X REST) NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL CDR QUOTE
   REDUNDANT-CLEAN-UP-DECL-ARGS)
  (RAISE) NIL NIL NIL)
 ((REST "Bad declaration ~x0" X DECL1 DECLARE DECL1-ARGS) NIL NIL NIL NIL NIL
  NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defredundant.lisp::REDUNDANT-CLEAN-UP-DEFUNS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (CONS) NIL NIL NIL)
 ((FORMS) NIL NIL NIL
  (REDUNDANT-CLEAN-UP-DEFUN ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 ((FORCE-PROGRAMP STATE FORCE-PROGRAMP STATE) NIL (CAR CDR) NIL NIL NIL NIL)
 ((FORMS FORMS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defredundant.lisp::REDUNDANT-DEFUN"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (NIL NIL (SB-INT:QUASIQUOTE) NIL NIL ((?__FUNCTION__ 'REDUNDANT-DEFUN)) NIL)
 (NIL NIL (FORM CLEANED-UP-FORM FN (MV ENABLES DISABLES))
  ((VALUE-TRIPLE (CW "Defun: ~x0.~%" ',FN))) NIL NIL NIL)
 ((,CLEANED-UP-FORM) NIL (ACCESS-EVENT-TUPLE-FORM SECOND IN-THEORY) NIL
  (REDUNDANT-CLEAN-UP-DEFUN IF) NIL NIL)
 ((EVENT-TUPLE FORM FORCE-PROGRAMP STATE FORM FORCE-PROGRAMP) NIL NIL
  (MV NAME-TO-E/DS E/D) NIL NIL NIL)
 ((NIL NIL FN STATE ,ENABLES ,DISABLES) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defredundant.lisp::REDUNDANT-CLEAN-DEFTHM-KWDARGS"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (NIL NIL NIL NIL (LIST*) ((?__FUNCTION__ 'REDUNDANT-CLEAN-DEFTHM-KWDARGS))
  NIL)
 ((KWD VAL) NIL
  ((WHEN (ATOM KWDARGS)) (WHEN (ATOM (CDR KWDARGS))) (LIST* KWD VAL REST)
   (WHEN
       (OR (EQ KWD :OTF-FLG) (EQ KWD :DOC) (EQ KWD :HINTS)
           (EQ KWD :INSTRUCTIONS)))
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 ((NIL KWDARGS REST) NIL (RAISE ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL NIL NIL)
 (("odd number of elements in (:kwd val) list?" REST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defredundant.lisp::REDUNDANT-DEFTHM"
 (NIL NIL (EVENT-TUPLE) NIL NIL NIL NIL) ((STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defredundant.lisp::REDUNDANT-DEFMACRO"
 (NIL NIL (EVENT-TUPLE) NIL NIL NIL NIL) ((STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defredundant.lisp::REDUNDANT-DEFCONST"
 (NIL NIL (EVENT-TUPLE) NIL NIL NIL NIL) ((STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defredundant.lisp::REDUNDANT-DEFSTOBJ"
 (NIL NIL (EVENT-TUPLE) NIL NIL NIL NIL) ((STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defredundant.lisp::REDUNDANT-ENCAPSULATE"
 (NIL NIL (EVENT-TUPLE) NIL NIL NIL NIL) ((STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defredundant.lisp::REDUNDANT-EVENT1"
 (NIL NIL NIL (B*) NIL NIL NIL) (NIL NIL NIL NIL (RAISE) NIL NIL)
 (("For ~x0: unsupported event type: ~x1" NAME TYPE) NIL
  (WORLD EVENT-TUPLE FORM (UNLESS (CONSP FORM)) TYPE (WHEN (EQ TYPE 'DEFTHM))
   (WHEN (EQ TYPE 'DEFCONST)) (WHEN (EQ TYPE 'DEFUN))
   (WHEN (EQ TYPE 'DEFMACRO)) (WHEN (EQ TYPE 'MUTUAL-RECURSION))
   (WHEN (EQ TYPE 'DEFSTOBJ)) (WHEN (EQ TYPE 'ENCAPSULATE)))
  NIL NIL NIL NIL)
 (NIL NIL (W ACCESS-EVENT-TUPLE-FORM CAR)
  (GET-EVENT-TUPLE REDUNDANT-DEFTHM REDUNDANT-DEFCONST REDUNDANT-DEFMACRO
   REDUNDANT-DEFSTOBJ REDUNDANT-ENCAPSULATE)
  (RAISE REDUNDANT-DEFUN REDUNDANT-MUTREC) NIL NIL)
 ((STATE NAME WORLD EVENT-TUPLE
   "For ~x0: expected a valid event form, but found ~x1." NAME FORM FORM
   EVENT-TUPLE STATE EVENT-TUPLE STATE EVENT-TUPLE FORCE-PROGRAMP STATE
   EVENT-TUPLE STATE EVENT-TUPLE FORCE-PROGRAMP STATE EVENT-TUPLE STATE
   EVENT-TUPLE STATE)
  NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defredundant.lisp::REDUNDANT-EVENTS1"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (APPEND) NIL NIL NIL)
 ((NAMES) NIL NIL NIL
  (REDUNDANT-EVENT1 ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 ((FORCE-PROGRAMP STATE FORCE-PROGRAMP STATE) NIL (CAR CDR) NIL NIL NIL NIL)
 ((NAMES NAMES) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defredundant.lisp::FIND-MACRO-ALIASES-FOR-DEFUN"
 (NIL NIL NIL (B*) NIL NIL NIL)
 ((NIL) NIL NIL NIL NIL ((__FUNCTION__ 'FIND-MACRO-ALIASES-FOR-DEFUN)) NIL)
 (NIL NIL
  ((UNLESS
       (AND (CONSP FORM) (OR (EQ (CAR FORM) 'DEFUN) (EQ (CAR FORM) 'DEFUND))))
   NAME ALIAS (WHEN ALIAS))
  NIL NIL NIL NIL)
 (NIL NIL (SECOND CAR LIST) (RAISE) NIL NIL NIL)
 (("Expected a defun form, not ~x0." FORM FORM ALIAS) NIL NIL (RASSOC) NIL NIL
  NIL)
 ((NAME) NIL NIL (TABLE-ALIST) NIL NIL NIL)
 ((WORLD) NIL (QUOTE) NIL NIL NIL NIL))
("/home/acl2/books/std/util/defredundant.lisp::FIND-MACRO-ALIASES-FOR-DEFUNS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (APPEND) NIL NIL NIL)
 ((FORMS) NIL NIL
  (FIND-MACRO-ALIASES-FOR-DEFUN ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL NIL)
 ((WORLD WORLD) NIL (CAR CDR) NIL NIL NIL NIL)
 ((FORMS FORMS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defredundant.lisp::FIND-DEFUN-ALIASES-FOR-MACRO"
 (NIL NIL NIL NIL (B*) NIL NIL) (NIL NIL NIL (MV) (RAISE) NIL NIL)
 (("Expected macro alias for ~x0 to be a mutual-recursion or defun, ~
            but found ~x1."
   NAME DEFUN-FORM NIL NIL)
  NIL
  (NAME FN (UNLESS FN) DEFUN-FORM TYPE (WHEN (EQ TYPE 'MUTUAL-RECURSION))
   (WHEN (EQ TYPE 'DEFUN)))
  ((UNLESS (AND (CONSP FORM) (EQ (CAR FORM) 'DEFMACRO)))) NIL NIL NIL)
 (NIL NIL (SECOND CDR ACCESS-EVENT-TUPLE-FORM CAR) (RAISE MV MV MV) (B*) NIL
  NIL)
 (("Expected a defmacro form, not ~x0." FORM NIL NIL FORM NIL DEFUN-FORM) NIL
  (LIST (FNS (STRIP-CADRS (CDR DEFUN-FORM))) LIST LIST)
  (ASSOC GET-EVENT-TUPLE OR MV) NIL NIL NIL)
 ((NAME NAME FN WORLD MACROS FNS NAME FN) NIL (MACROS RAISE) (TABLE-ALIST AND)
  NIL NIL NIL)
 ((WORLD "Macro alias problem.") NIL (QUOTE)
  (FIND-MACRO-ALIASES-FOR-DEFUNS MEMBER MEMBER) NIL NIL NIL))
("/home/acl2/books/std/util/defredundant.lisp::REDUNDANT-EVENT"
 (NIL NIL NIL (B*) NIL NIL NIL) (NIL NIL NIL NIL NIL (RAISE) NIL)
 (("For ~x0: unsupported event type: ~x1 form: ~x2~%" NAME TYPE) NIL
  (WORLD EVENT-TUPLE FORM (UNLESS (CONSP FORM)) TYPE
   (WHEN
       (OR (EQ TYPE 'DEFTHM) (EQ TYPE 'DEFCONST) (EQ TYPE 'DEFSTOBJ)
           (EQ TYPE 'ENCAPSULATE)))
   (WHEN (EQ TYPE 'DEFUN)) (WHEN (EQ TYPE 'MUTUAL-RECURSION))
   (WHEN (EQ TYPE 'DEFMACRO)) ACCESS-EVENT-TUPLE-FORM)
  NIL NIL NIL NIL)
 ((EVENT-TUPLE) NIL (W ACCESS-EVENT-TUPLE-FORM CAR) (GET-EVENT-TUPLE B* B* B*)
  (RAISE REDUNDANT-EVENT1) NIL NIL)
 ((STATE NAME WORLD EVENT-TUPLE
   "For ~x0: expected a valid event form, but found ~x1." NAME FORM FORM NAME
   FORCE-PROGRAMP STATE)
  NIL NIL (APPEND APPEND APPEND)
  ((FN-EVENTS (REDUNDANT-EVENT1 NAME FORCE-PROGRAMP STATE))
   (DEFMACRO (ACCESS-EVENT-TUPLE-FORM EVENT-TUPLE)))
  ((FN-EVENTS (REDUNDANT-EVENT1 NAME FORCE-PROGRAMP STATE))) NIL)
 ((MACRO-EVENTS FN-EVENTS MACRO-EVENTS FN-EVENTS MACRO-EVENTS FN-EVENTS) NIL
  (DEFUN MACRO-NAMES MACRO-EVENTS
    DEFUNS
    MACRO-NAMES
    -
    MACRO-EVENTS
    (MV MACROS FNS)
    MACRO-EVENTS
    FN-EVENTS)
  NIL NIL NIL NIL)
 (NIL NIL (ACCESS-EVENT-TUPLE-FORM CDR)
  (FIND-MACRO-ALIASES-FOR-DEFUN FIND-MACRO-ALIASES-FOR-DEFUNS
   FIND-DEFUN-ALIASES-FOR-MACRO)
  (REDUNDANT-EVENTS1 CW REDUNDANT-EVENTS1 REDUNDANT-EVENTS1 REDUNDANT-EVENTS1)
  NIL NIL))
("/home/acl2/books/std/util/defredundant.lisp::REDUNDANT-EVENTS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (APPEND) NIL NIL NIL)
 ((NAMES) NIL NIL NIL
  (REDUNDANT-EVENT ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 ((FORCE-PROGRAMP STATE FORCE-PROGRAMP STATE) NIL (CAR CDR) NIL NIL NIL NIL)
 ((NAMES NAMES) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
