("/home/acl2/books/clause-processors/remove-hyp.lisp::REMOVE-FIRST-HYP-CP"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL (CONSP LIST LIST) NIL NIL NIL NIL)
 ((CLAUSE CLAUSE) NIL (CDR) NIL NIL NIL NIL) ((CLAUSE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/clause-processors/remove-hyp.lisp::REMOVE-HYP-CP"
 (NIL NIL (LIST) NIL NIL NIL NIL) (NIL NIL NIL (REMOVE-EQUAL) NIL NIL NIL)
 ((HYP CLAUSE) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
