("/home/acl2/books/std/io/unsound-read.lisp::UNSOUND-READ-FN"
 (NIL NIL NIL (FILENAME) NIL NIL NIL)
 ((HONS-MODE VERBOSEP) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
