("/home/acl2/books/tools/deftuple.lisp::PRETTY-ARGS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) NIL (IF) NIL NIL)
 ((ARGS HONS-OPT) NIL NIL (CONS CONS) NIL NIL NIL)
 (NIL NIL `SB-INT:QUASIQUOTE
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL)
 ((HONS-OPT HONS-OPT) NIL (CDR CDR) (HONS-LIST LIST) NIL NIL NIL)
 ((,(CAR ARGS) ARGS ,(CAR ARGS) ARGS) NIL 'QUOTE NIL NIL NIL NIL)
 ((,(CAR ARGS) ,(CAR ARGS)) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/deftuple.lisp::DEFTUPLE-CONSTRUCTOR"
 (NIL NIL NIL (LET*) NIL NIL NIL)
 (NIL NIL ((ARGS (COMPONENTS-NAMES COMPONENTS)) SB-INT:QUASIQUOTE) NIL NIL NIL
  NIL)
 (NIL NIL (CONS) NIL NIL (DEFUN) NIL)
 ((,NAME ,ARGS
   ,@(IF GUARD-OPT
         `((DECLARE (XARGS :GUARD T)))
         NIL)
   ,(IF PRETTY-OPT
        `(,(IF HONS-OPT
               'HONS-LIST
               'LIST)
          ',NAME ,@(PRETTY-ARGS HONS-OPT ARGS))
        (IF COMPACT-OPT
            (ARGTREE CONS ARGS)
            `(,(IF HONS-OPT
                   'HONS-LIST
                   'LIST)
              ,@ARGS))))
  NIL NIL NIL (IF) NIL NIL)
 ((HONS-OPT) NIL 'QUOTE NIL NIL NIL NIL) ((HONS CONS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/deftuple.lisp::PRETTY-STRUCTUREP"
 (NIL NIL NIL NIL (IF) NIL NIL)
 (NIL NIL (ATOM SB-INT:QUASIQUOTE) (LET) NIL NIL NIL)
 ((COMPONENTS (EQ ,X NIL) (N (COMPONENT-NAME (CAR COMPONENTS)))) NIL
  (SB-INT:QUASIQUOTE) NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL ((CONSP ,X)))
 ((,@(PRETTY-STRUCTUREP (CDR COMPONENTS) `(CDR ,X))) NIL (CONSP CONSP) (EQ EQ)
  NIL NIL NIL)
 ((NIL) NIL (CAR CAAR QUOTE CDAR CDDAR) NIL NIL NIL NIL)
 ((,X ,X ,N ,X ,X) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/deftuple.lisp::DEFTUPLE-STRUCTURE-RECOGNIZER"
 (NIL NIL NIL (LET*) NIL NIL NIL)
 (NIL NIL ((NCOMPS (LENGTH COMPS)) SB-INT:QUASIQUOTE) NIL NIL NIL NIL)
 (NIL NIL (TESTS) NIL NIL (DEFUN) NIL)
 ((,(APPSYMS (LIST NAME 'STRUCTUREP)) X
   ,@(IF GUARD-OPT
         `((DECLARE (XARGS :GUARD T)))
         NIL)
   ,@(IF (< (LEN TESTS) 2)
         TESTS
         `((AND ,@TESTS))))
  NIL NIL NIL (IF) NIL NIL)
 ((PRETTY-OPT) NIL (SB-INT:QUASIQUOTE) NIL (IF) NIL NIL)
 ((COMPACT-OPT) NIL (SB-INT:QUASIQUOTE) ((CONSP X) RECOG-CONSP-LIST) NIL NIL
  NIL)
 ((,@(PRETTY-STRUCTUREP COMPS '(CDR X)) NCOMPS) NIL '(TRUE-LISTP X) (EQ) NIL
  NIL NIL))
("/home/acl2/books/tools/deftuple.lisp::DEFTUPLE-COMPOUND-REC-THM"
 (NIL NIL (SB-INT:QUASIQUOTE) NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL (DEFTHM) NIL)
 ((,(PACKSYMS (LIST NAME 'P-COMPOUND-RECOGNIZER)) :RULE-CLASSES
   :COMPOUND-RECOGNIZER)
  NIL NIL (IMPLIES) NIL NIL NIL)
 ((,(IF COMPACT-OPT
        `(CONSP X)
        `(AND (CONSP X) (TRUE-LISTP X))))
  NIL (,(APPSYMS (LIST NAME 'STRUCTUREP))) NIL NIL NIL NIL)
 ((X) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/deftuple.lisp::DEFTUPLE-CONSTRUCTOR-STRUCTURE-RECOGNIZER-THM"
 (NIL NIL NIL (LET) NIL NIL NIL)
 (((CALL (CONS NAME (COMPONENTS-NAMES COMPONENTS)))) NIL (SB-INT:QUASIQUOTE)
  NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL (DEFTHM) NIL)
 ((,(PACKSYMS (LIST NAME '-STRUCTUREP- NAME)) :RULE-CLASSES
   (:FORWARD-CHAINING :TRIGGER-TERMS (,CALL)))
  NIL (,(APPSYMS (LIST NAME 'STRUCTUREP))) NIL NIL NIL NIL)
 ((,CALL) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/deftuple.lisp::DEFTUPLE-ACCESSOR"
 (NIL NIL NIL (LET) NIL NIL NIL)
 (NIL NIL ((REC (APPSYMS (LIST NAME 'STRUCTUREP))) SB-INT:QUASIQUOTE) NIL NIL
  NIL NIL)
 (NIL NIL (ACC) NIL NIL (DEFUN) NIL)
 ((,(APPSYMS (LIST NAME (COMPONENT-NAME COMPONENT))) X
   ,@(IF GUARD-OPT
         (IF (EQ GUARD-OPT :SAFE)
             `((DECLARE (XARGS :GUARD T)))
             `((DECLARE (XARGS :GUARD (,REC X)))))
         NIL)
   ,ACC)
  NIL NIL NIL (IF) NIL NIL)
 ((PRETTY-OPT) NIL NIL NIL (IF IF) NIL NIL)
 ((COMPACT-OPT) NIL `SB-INT:QUASIQUOTE (EQ) (IF) (TREE-ACCESSOR) NIL)
 ((GUARD-OPT :SAFE N NCOMPS GUARD-OPT) NIL
  (SAFE-CAR CADR QUOTE . `SB-INT:QUASIQUOTE) (EQ) NIL NIL NIL))
("/home/acl2/books/tools/deftuple.lisp::DEFTUPLE-ACCESSORS-HELP"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (CONS) NIL NIL NIL)
 ((COMPONENTS) NIL NIL NIL NIL NIL NIL)
 ((NAME NCOMPS N GUARD-OPT COMPACT-OPT PRETTY-OPT NAME NCOMPS GUARD-OPT
   COMPACT-OPT PRETTY-OPT)
  NIL (CAR CDR 1+) NIL NIL NIL NIL)
 ((COMPONENTS COMPONENTS N) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/deftuple.lisp::DEFTUPLE-ACCESSORS"
 (NIL NIL NIL NIL NIL NIL NIL)
 ((NAME COMPONENTS GUARD-OPT COMPACT-OPT PRETTY-OPT) (1) (LENGTH) NIL NIL NIL
  NIL)
 ((COMPONENTS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/deftuple.lisp::DEFTUPLE-CONSTRUCTOR-COMPONENT-THMS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (CONS) NIL NIL NIL)
 ((COMPONENTS) NIL NIL (LET*) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL)
 ((NAME CALL) NIL ((ARG (COMPONENT-NAME (CAR COMPONENTS))) . `CDR) NIL NIL NIL
  NIL)
 ((COMPONENTS) NIL (ACC) (DEFTHM) NIL NIL NIL)
 ((,(APPSYMS (LIST NAME NAME ARG))) NIL (APPSYMS) (EQUAL) NIL NIL NIL)
 ((,ARG) NIL (,ACC) (LIST) NIL NIL NIL))
("/home/acl2/books/tools/deftuple.lisp::DEFTUPLE-ACC-CALL-LIST"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (LET*) NIL NIL NIL)
 ((COMPONENTS) NIL ((CNAME (COMPONENT-NAME (CAR COMPONENTS)))) (CONS) NIL NIL
  NIL)
 (NIL NIL (ACC SB-INT:QUASIQUOTE) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL)
 ((NAME) NIL (APPSYMS ,ACC CDR) NIL NIL NIL NIL)
 ((X COMPONENTS) NIL NIL (LIST) NIL NIL NIL)
 ((NAME CNAME) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/deftuple.lisp::DEFTUPLE-ELIM-THM"
 (NIL NIL NIL (LET) NIL NIL NIL)
 (((ACCS (DEFTUPLE-ACC-CALL-LIST NAME COMPONENTS))) NIL (SB-INT:QUASIQUOTE) NIL
  NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL)
 ((,(APPSYMS (LIST NAME 'ELIM)) :RULE-CLASSES :HINTS
   ("Goal" :IN-THEORY (ENABLE TRUE-LISTP-LEN-0 NTH-OPEN)))
  NIL (:REWRITE) (IMPLIES) NIL NIL NIL)
 ((:ELIM) NIL (,(APPSYMS (LIST NAME 'STRUCTUREP))) (EQUAL) NIL NIL NIL)
 ((X X) NIL (,NAME) NIL NIL NIL NIL) ((,@ACCS) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/deftuple.lisp::DEFTUPLE-BINDER"
 (NIL NIL (SB-INT:QUASIQUOTE) NIL NIL NIL NIL)
 (NIL NIL NIL (DEF-PATBIND-MACRO) NIL NIL NIL)
 ((,NAME ,(ACCESSOR-LIST (LIST (CONS NAME COMPONENTS)) COMPONENTS)) NIL NIL NIL
  NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/deftuple.lisp::ACCESSOR-TYPE-LIST"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (LET) NIL NIL NIL)
 ((COMPONENTS) NIL ((TYPE (COMPONENT-TYPE (CAR COMPONENTS)))) NIL (IF) NIL NIL)
 ((TYPE) NIL (CNAME) (CONS ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL)
 ((NAME) NIL (COMPONENT-NAME . `CDR) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL)
 ((NAME COMPONENTS) NIL (CAR ,TYPE CDR) NIL NIL NIL NIL)
 ((COMPONENTS COMPONENTS) NIL (,(APPSYMS (LIST NAME CNAME))) NIL NIL NIL NIL))
("/home/acl2/books/tools/deftuple.lisp::DEFTUPLE-RECOGNIZER"
 (NIL NIL NIL (LET*) NIL NIL NIL)
 (((TESTS (ACCESSOR-TYPE-LIST NAME COMPONENTS))) NIL (SB-INT:QUASIQUOTE) NIL
  NIL NIL NIL)
 (NIL NIL NIL NIL NIL (DEFUN) NIL)
 ((,(PACKSYMS (LIST NAME 'P)) X
   ,@(IF GUARD-OPT
         `((DECLARE (XARGS :GUARD T)))
         NIL))
  NIL NIL (AND) NIL NIL NIL)
 ((,@TESTS) NIL (,(APPSYMS (LIST NAME 'STRUCTUREP))) NIL NIL NIL NIL)
 ((X) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/deftuple.lisp::DEFTUPLE-RECOGNIZER-STRUCTURE-RECOGNIZER"
 (NIL NIL (SB-INT:QUASIQUOTE) NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL (DEFTHM) NIL)
 ((,(PACKSYMS (LIST NAME 'P- NAME '-STRUCTUREP)) :RULE-CLASSES) NIL (:REWRITE)
  (IMPLIES) NIL NIL NIL)
 ((:FORWARD-CHAINING) NIL
  (,(PACKSYMS (LIST NAME 'P)) ,(APPSYMS (LIST NAME 'STRUCTUREP))) NIL NIL NIL
  NIL)
 ((X X) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/deftuple.lisp::DEFTUPLE-COMPONENT-TYPE-THMS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (LET) NIL NIL NIL)
 ((COMPONENTS) NIL ((TYPE (COMPONENT-TYPE (CAR COMPONENTS)))) NIL (IF) NIL NIL)
 ((TYPE) NIL (ACC) (CONS) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 ((NAME REC) NIL (APPSYMS . `CDR) NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 ((NAME REC COMPONENTS) NIL (CDR) (LIST DEFTHM) NIL NIL NIL)
 ((NAME ,(APPSYMS (LIST REC (COMPONENT-NAME (CAR COMPONENTS)))) COMPONENTS) NIL
  (COMPONENT-NAME) (IMPLIES) NIL NIL NIL))
("/home/acl2/books/tools/deftuple.lisp::COMPONENT-TYPE-LIST"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (LET) NIL NIL NIL)
 ((COMPONENTS) NIL ((TYPE (COMPONENT-TYPE (CAR COMPONENTS)))) NIL (IF) NIL NIL)
 ((TYPE) NIL (NAME ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (CONS) NIL NIL
  NIL)
 (NIL NIL
  (COMPONENT-NAME SB-INT:QUASIQUOTE ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   CDR)
  NIL NIL NIL NIL)
 ((COMPONENTS) NIL (CAR ,TYPE CDR) NIL NIL NIL NIL)
 ((COMPONENTS ,NAME COMPONENTS) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/deftuple.lisp::DEFTUPLE-RECOGNIZER-CONSTRUCTOR-THM"
 (NIL NIL NIL (LET*) NIL NIL NIL)
 (NIL NIL (SB-INT:QUASIQUOTE) ((TESTS (COMPONENT-TYPE-LIST COMPONENTS))) NIL
  NIL NIL)
 (NIL NIL (CALL CONCL) (DEFTHM) NIL NIL NIL)
 ((,(PACKSYMS (LIST NAME 'P- NAME))
   ,(IF (< 0 (LEN TESTS))
        `(EQUAL ,CONCL
                ,@(IF (< 1 (LEN TESTS))
                      `((AND ,@TESTS))
                      TESTS))
        `(EQUAL ,CONCL T)))
  NIL `SB-INT:QUASIQUOTE NIL NIL NIL NIL)
 (NIL NIL (,NAME ,(PACKSYMS (LIST NAME 'P))) NIL NIL NIL NIL)
 ((,@(COMPONENTS-NAMES COMPONENTS) ,CALL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/deftuple.lisp::DEFTUPLE-DEFS"
 (NIL NIL (SB-INT:QUASIQUOTE) NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 ((,(DEFTUPLE-STRUCTURE-RECOGNIZER NAME COMPONENTS GUARD-OPT COMPACT-OPT
     PRETTY-OPT)
   ,(DEFTUPLE-COMPOUND-REC-THM NAME COMPACT-OPT)
   ,(DEFTUPLE-CONSTRUCTOR-STRUCTURE-RECOGNIZER-THM NAME COMPONENTS)
   ,@(DEFTUPLE-ACCESSORS NAME COMPONENTS GUARD-OPT COMPACT-OPT PRETTY-OPT)
   ,@(DEFTUPLE-CONSTRUCTOR-COMPONENT-THMS NAME COMPONENTS
      `(,NAME ,@(COMPONENTS-NAMES COMPONENTS)))
   ,(DEFTUPLE-ELIM-THM NAME COMPONENTS) ,(DEFTUPLE-BINDER NAME COMPONENTS)
   ,(DEFTUPLE-RECOGNIZER NAME COMPONENTS GUARD-OPT)
   ,(DEFTUPLE-RECOGNIZER-STRUCTURE-RECOGNIZER NAME)
   ,@(DEFTUPLE-COMPONENT-TYPE-THMS NAME (PACKSYMS (LIST NAME 'P)) COMPONENTS)
   ,(DEFTUPLE-RECOGNIZER-CONSTRUCTOR-THM NAME COMPONENTS))
  NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/deftuple.lisp::DEFTUPLE-FN"
 (NIL NIL NIL (LET*) NIL NIL NIL) (NIL NIL (SB-INT:QUASIQUOTE) NIL NIL NIL NIL)
 (NIL NIL
  (HONS-OPT ARITHMETIC-OPT PRETTY-OPT COMPACT-OPT BEFORE-LABEL DIFFTHEORY
   FUNCTION-THEORY EXEC-THEORY)
  NIL NIL NIL NIL)
 ((NIL
   ,@(IF ARITHMETIC-OPT
         `((LOCAL (INCLUDE-BOOK "arithmetic/top-with-meta" :DIR :SYSTEM)))
         NIL)
   ,@(DEFTUPLE-DEFS NAME COMPONENTS GUARD-OPT HONS-OPT COMPACT-OPT PRETTY-OPT))
  NIL (APPSYMS SB-INT:QUASIQUOTE APPSYMS APPSYMS DEFLABEL IN-THEORY)
  (AND DEFTHEORY DEFTHEORY DEFTHEORY DEFTHEORY) (KWASSOC KWASSOC KWASSOC) NIL
  NIL)
 ((:HONS NIL KWALIST :ARITHMETIC T KWALIST :PRETTY NIL KWALIST ,BEFORE-LABEL
   ,FUNCTION-THEORY ,EXEC-THEORY ,(APPSYMS (LIST NAME 'THEOREMS))
   ,(APPSYMS (LIST NAME 'ENTIRE-THEORY)))
  NIL (NOT)
  (LIST SET-DIFFERENCE-THEORIES LIST LIST RULES-OF-TYPE RULES-OF-TYPE
        SET-DIFFERENCE-THEORIES DISABLE SET-DIFFERENCE-THEORIES)
  (KWASSOC) NIL NIL)
 ((PRETTY-OPT :COMPACT NIL KWALIST NAME NAME NAME :DEFINITION ,DIFFTHEORY
   :EXECUTABLE-COUNTERPART ,DIFFTHEORY ,DIFFTHEORY ,FUNCTION-THEORY
   ,EXEC-THEORY)
  NIL
  (QUOTE CURRENT-THEORY CURRENT-THEORY QUOTE QUOTE UNIVERSAL-THEORY
   UNIVERSAL-THEORY)
  (UNION-THEORIES) NIL NIL NIL)
 ((BEFORE :HERE FUNCTIONS EXECUTABLE-COUNTERPARTS :HERE) NIL
  (QUOTE THEORY THEORY QUOTE) NIL NIL NIL NIL))
("/home/acl2/books/tools/deftuple.lisp::TRANSLATE-KWALIST"
 (NIL NIL NIL NIL (IF) NIL NIL)
 ((NIL) NIL (ATOM SB-INT:QUASIQUOTE) NIL NIL NIL NIL)
 ((KWALIST) NIL NIL (CONS) NIL NIL NIL)
 ((,(TRANSLATE-KWALIST (CDR KWALIST))) NIL NIL (CONS) NIL NIL NIL)
 ((,(CDAR KWALIST)) NIL (QUOTE) NIL NIL NIL NIL)
 ((,(CAAR KWALIST)) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
