("/home/acl2/books/std/util/formals.lisp::FORMALLIST-P"
 ((X) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/formals.lisp::FORMALLIST->NAMES"
 ((X) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/formals.lisp::FORMALLIST->GUARDS"
 ((X) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/formals.lisp::FORMALLIST-COLLECT-STOBJS"
 (NIL NIL (X) NIL NIL NIL NIL) ((WORLD) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/formals.lisp::PARSE-FORMAL-NAME"
 (NIL NIL (CTX) NIL NIL NIL NIL) ((VARNAME) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/formals.lisp::CHECK-FORMAL-GUARD"
 (NIL NIL NIL (B*) NIL NIL NIL) (NIL NIL NIL NIL NIL NIL (RAISE))
 (("Error in ~x0: the guard for ~x1 should take a single argument, ~
            but ~x2 takes ~x3 arguments."
   CTX VARNAME ITEM)
  NIL
  ((UNLESS WORLD) MACRO-ARGS (UNLESS (EQ MACRO-ARGS :BAD)) FORMALS
   (WHEN (EQ FORMALS :BAD)) (WHEN (TUPLEP 1 FORMALS)) LEN)
  NIL NIL NIL NIL)
 ((NIL NIL NIL FORMALS) NIL NIL NIL NIL (RAISE) (GETPROP GETPROP))
 ((ITEM :BAD WORLD ITEM :BAD WORLD
   "Error in ~x0: the guard for ~x1 is ~x2, but there is no ~
                function or macro named ~x2."
   CTX VARNAME ITEM)
  NIL (QUOTE QUOTE QUOTE QUOTE) NIL NIL NIL NIL)
 ((MACRO-ARGS CURRENT-ACL2-WORLD FORMALS CURRENT-ACL2-WORLD) NIL NIL NIL NIL
  NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/formals.lisp::PARSE-FORMALS"
 (NIL NIL NIL NIL (CTX) NIL NIL)
 ((FORMALS LEGAL-KWDS WORLD) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/formals.lisp::HAS-MACRO-ARGS"
 ((X) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/formals.lisp::REMOVE-MACRO-ARGS"
 (NIL NIL NIL (CTX) NIL NIL NIL) ((FORMALS SEENP) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/formals.lisp::FORMALS-FOR-MACRO"
 (NIL NIL NIL (CTX) NIL NIL NIL) ((FORMALS SEENP) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/formals.lisp::REMOVE-MACRO-DEFAULT-VALUES"
 ((ARGS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/formals.lisp::MAKE-WRAPPER-MACRO"
 (NIL NIL NIL (FNNAME) NIL NIL NIL)
 ((FNNAME-FN FORMALS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
