("/home/acl2/books/projects/apply/base.lisp::META-APPLY$-PRIM"
 ((TERM) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/projects/apply/base.lisp::SUITABLY-TAMEP-LISTP-INDUCTION"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ZP N) T) NIL NIL NIL NIL)
 (NIL NIL NIL (LIST) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 ((FLAGS ARGS) NIL (CDR CDR) (-) NIL NIL NIL)
 ((N FLAGS ARGS) (1) NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
