("/home/acl2/books/std/lists/abstract.lisp::RULETABLE-DELETE-TAGS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) NIL (IF) NIL NIL)
 ((TABLE) NIL NIL (AND ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL CONS) NIL NIL
  NIL)
 ((TAGS) NIL (CONSP CDR CAR)
  (INTERSECTP-EQ ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((TAGS TABLE TABLE TAGS) NIL (CDAR CDR CDR) NIL NIL NIL NIL)
 ((TABLE TABLE) NIL NIL (ASSOC) NIL NIL NIL)
 ((:TAGS) NIL (CDAR) NIL NIL NIL NIL))
("/home/acl2/books/std/lists/abstract.lisp::RULETABLE-KEEP-TAGS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) NIL (IF) NIL NIL)
 ((TABLE) NIL NIL (AND CONS ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL)
 ((TAGS) NIL (CONSP CAR CDR)
  (INTERSECTP-EQ ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((TAGS TABLE TAGS TABLE) NIL (CDAR CDR CDR) NIL NIL NIL NIL)
 ((TABLE TABLE) NIL NIL (ASSOC) NIL NIL NIL)
 ((:TAGS) NIL (CDAR) NIL NIL NIL NIL))
