("/home/acl2/books/clause-processors/unify-subst.lisp::LIST-TERM"
 ((LST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/clause-processors/unify-subst.lisp::FILTER-OUT-UNIFY-SUBST-EVALS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (LET*) NIL NIL NIL)
 ((ENV-TERMS) NIL ((ENV (CAR ENV-TERMS))) NIL (CASE-MATCH) NIL NIL)
 ((ENV) NIL (REST (!EV-ALIST ('MV-NTH ''1 !SIMPLE-ONE-WAY-UNIFY-CALL) A) &) NIL
  NIL NIL NIL)
 (NIL NIL NIL (CONS) (IF) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL)
 ((SIMPLE-ONE-WAY-UNIFY-CALL EV-ALIST FULL-ENV-TERMS REST ENV REST) NIL (CDR)
  (MEMBER-EQUAL CONS) NIL NIL NIL)
 ((ENV-TERMS A FULL-ENV-TERMS A REST) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/clause-processors/unify-subst.lisp::SIMPLE-ONE-WAY-UNIFY-BIND-FREE"
 (NIL NIL NIL NIL (RW-TERM) NIL NIL)
 ((EVAL-FNS MFC STATE) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/clause-processors/unify-subst.lisp::UNIFY-EV-SIMPLE-ONE-WAY-UNIFY-EQUALITIES"
 (NIL NIL NIL NIL (IF) NIL NIL) ((T) NIL (ATOM) (AND) NIL NIL NIL)
 ((ENVS) NIL NIL (EQUAL) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL)
 ((PAT TERM SUBST) NIL (CDR) (UNIFY-EV UNIFY-EV) NIL NIL NIL)
 ((TERM PAT ENVS) NIL (CAR) (UNIFY-EV-ALIST) NIL NIL NIL)
 ((ENVS SUBST) NIL (CAR) NIL NIL NIL NIL) ((ENVS) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/clause-processors/unify-subst.lisp::UNIFY-EV-LST-SIMPLE-ONE-WAY-UNIFY-EQUALITIES"
 (NIL NIL NIL NIL (IF) NIL NIL) ((T) NIL (ATOM) (AND) NIL NIL NIL)
 ((ENVS) NIL NIL (EQUAL) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL)
 ((PAT TERM SUBST) NIL (CDR) (UNIFY-EV-LST UNIFY-EV-LST) NIL NIL NIL)
 ((TERM PAT ENVS) NIL (CAR) (UNIFY-EV-ALIST) NIL NIL NIL)
 ((ENVS SUBST) NIL (CAR) NIL NIL NIL NIL) ((ENVS) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/clause-processors/unify-subst.lisp::DEF-UNIFY-PREFIX-PAIR"
 (NIL NIL NIL (LET) NIL NIL NIL)
 (((STR (SYMBOL-NAME SYM))) NIL NIL (CONS) NIL NIL NIL)
 (NIL NIL NIL (INTERN$ INTERN-IN-PACKAGE-OF-SYMBOL) NIL NIL NIL)
 (("ACL2" EV) NIL NIL NIL (CONCATENATE CONCATENATE) NIL NIL)
 ((STR STR) NIL (QUOTE SYMBOL-NAME QUOTE SYMBOL-NAME) NIL NIL NIL NIL)
 ((STRING NEW-EV STRING EV) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/clause-processors/unify-subst.lisp::DEF-UNIFY-PREFIX-PAIRS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (CONS) NIL NIL NIL)
 ((SYMS) NIL NIL NIL
  (DEF-UNIFY-PREFIX-PAIR ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 ((NEW-EV EV NEW-EV EV) NIL (CAR CDR) NIL NIL NIL NIL)
 ((SYMS SYMS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/clause-processors/unify-subst.lisp::DEF-UNIFY-SUFFIX-PAIR"
 (NIL NIL NIL (LET) NIL NIL NIL)
 (((STR (SYMBOL-NAME SYM))) NIL NIL (CONS) NIL NIL NIL)
 (NIL NIL NIL (INTERN$ INTERN-IN-PACKAGE-OF-SYMBOL) NIL NIL NIL)
 (("ACL2" EV) NIL NIL NIL (CONCATENATE CONCATENATE) NIL NIL)
 ((STR STR) NIL (QUOTE SYMBOL-NAME QUOTE SYMBOL-NAME) NIL NIL NIL NIL)
 ((STRING NEW-EV STRING EV) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/clause-processors/unify-subst.lisp::DEF-UNIFY-SUFFIX-PAIRS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (CONS) NIL NIL NIL)
 ((SYMS) NIL NIL NIL
  (DEF-UNIFY-SUFFIX-PAIR ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 ((NEW-EV EV NEW-EV EV) NIL (CAR CDR) NIL NIL NIL NIL)
 ((SYMS SYMS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
