("/home/acl2/books/tools/run-script.lisp::DIFF-MSG"
 (NIL NIL NIL NIL (FILE1) NIL NIL) ((FILE2 S1 S2) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/run-script.lisp::IDENTICAL-FILES-P-FN"
 (NIL NIL NIL (FILE1) NIL NIL NIL) ((FILE2 STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
