("/home/acl2/books/tools/rewrite-with-equality.lisp::PREFERRED-TERMS-FOR-REWRITE-WITH-EQUALP"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL
  ((ENDP PREFERENCES)
   (AND (MEMBER-EQ FN (CAR (CAR PREFERENCES)))
        (MEMBER-EQ GN (CADR (CAR PREFERENCES))))
   T)
  NIL NIL NIL NIL)
 ((NIL T) NIL NIL NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 ((FN GN) NIL (CDR) NIL NIL NIL NIL) ((PREFERENCES) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/rewrite-with-equality.lisp::TRIGGERING-LIT-FOR-REWRITE-WITH-EQUALP"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((LIT) NIL (('NOT ('EQUAL (FN . &) (GN . &))) &) NIL NIL NIL NIL)
 (NIL NIL NIL NIL (COND MV) NIL NIL)
 ((NIL NIL NIL) NIL
  ((PREFERRED-TERMS-FOR-REWRITE-WITH-EQUALP PREFERENCES FN GN)
   (PREFERRED-TERMS-FOR-REWRITE-WITH-EQUALP PREFERENCES GN FN) T)
  NIL NIL NIL NIL)
 (NIL NIL NIL NIL (MV MV MV) NIL NIL)
 ((LIT LIT NIL NIL NIL) NIL NIL (FARGN FARGN FARGN FARGN) NIL NIL NIL)
 (NIL (1 2 2 1) NIL (FARGN FARGN FARGN FARGN) NIL NIL NIL))
("/home/acl2/books/tools/rewrite-with-equality.lisp::FIND-TRIGGERING-LIT-FOR-REWRITE-WITH-EQUALP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ENDP CL) T) NIL NIL NIL NIL)
 (NIL NIL NIL NIL (MV MV-LET) NIL NIL)
 ((NIL NIL NIL) NIL NIL (LIT TRIGGERING-LIT-FOR-REWRITE-WITH-EQUALP COND) NIL
  NIL NIL)
 ((LHS RHS PREFERENCES) NIL (CAR LIT T) NIL NIL NIL NIL)
 ((CL) NIL NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (MV) NIL NIL)
 ((LIT LHS RHS PREFERENCES) NIL (CDR) NIL NIL NIL NIL))
("/home/acl2/books/tools/rewrite-with-equality.lisp::MY-SUBST-EXPR1"
 (NIL NIL NIL NIL (FLG) NIL NIL) ((NEW OLD X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/rewrite-with-equality.lisp::REWRITE-CLAUSE-WITH-EQUAL"
 (NIL NIL NIL NIL (MV-LET) NIL NIL)
 (NIL NIL NIL (LIT FIND-TRIGGERING-LIT-FOR-REWRITE-WITH-EQUALP COND) NIL NIL
  NIL)
 ((BAD GOOD PREFERENCES CL) NIL (LIT T) NIL NIL NIL NIL)
 (NIL NIL (LIST) (PROG2$) NIL NIL NIL) ((CL) NIL (LIST) NIL (CW) NIL NIL)
 (("~%~%HIT!  Replaced ~x0 by ~x1.~%~%" BAD GOOD) NIL NIL NIL NIL
  (MY-SUBST-EXPR1) NIL)
 ((NIL GOOD BAD CL) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/rewrite-with-equality.lisp::REWRITE-WITH-EQUALITY-WHEN-STABLE"
 (NIL NIL NIL NIL (ID) NIL NIL)
 ((CLAUSE WORLD STABLE-UNDER-SIMPLIFICATIONP) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
