("/home/acl2/books/misc/dijkstra-shortest-path.lisp::DEL"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ENDP) NIL (IF) NIL NIL)
 ((Y) NIL (CDR) (EQUAL CONS) NIL NIL NIL)
 ((X Y) NIL (CAR CAR) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((Y Y X) NIL (CDR) NIL NIL NIL NIL) ((Y) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::MEMP"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ENDP) (OR) NIL NIL NIL)
 ((X) NIL NIL (EQUAL ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((E E) NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::SETP"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL ((ENDP S) (MEMP (CAR S) (CDR S)) T) NIL NIL NIL NIL)
 ((T NIL) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL NIL)
 (NIL NIL (CDR) NIL NIL NIL NIL) ((S) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::MY-UNION"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL ((ENDP S1) (MEMP (CAR S1) S2) T) NIL NIL NIL NIL)
 ((S2) NIL NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL CONS) NIL NIL NIL)
 ((S2) NIL (CDR CAR) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((S1 S1 S2) NIL (CDR) NIL NIL NIL NIL) ((S1) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::MY-SUBSETP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ENDP S1) T) NIL NIL NIL NIL)
 ((T) NIL NIL (AND) NIL NIL NIL)
 (NIL NIL NIL (MEMP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((S2 S2) NIL (CAR CDR) NIL NIL NIL NIL) ((S1 S1) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::INFINITEP"
 (NIL NIL (NULL) NIL NIL NIL NIL) ((X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::LT"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL ((INFINITEP X) (INFINITEP Y) T) NIL NIL NIL NIL)
 ((NIL T) NIL NIL (<) NIL NIL NIL) ((X Y) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::PLUS"
 (NIL NIL NIL (COND) NIL NIL NIL)
 (NIL NIL ((OR (INFINITEP X) (INFINITEP Y)) T) NIL NIL NIL NIL)
 ((NIL) NIL NIL (+) NIL NIL NIL) ((X Y) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::EDGE-LISTP"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL
  ((ENDP LST)
   (AND (CONSP (CAR LST)) (RATIONALP (CDAR LST)) (<= 0 (CDAR LST))
        (NOT (ASSOC (CAAR LST) (CDR LST))))
   T)
  NIL NIL NIL NIL)
 ((NIL) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (EQUAL) NIL NIL NIL)
 ((LST NIL) NIL (CDR) NIL NIL NIL NIL) ((LST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::GRAPHP"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL ((ENDP G) (AND (CONSP (CAR G)) (EDGE-LISTP (CDAR G))) T) NIL NIL NIL
  NIL)
 ((NIL) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (EQUAL) NIL NIL NIL)
 ((G NIL) NIL (CDR) NIL NIL NIL NIL) ((G) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::CONS-SET"
 (NIL NIL NIL NIL (IF) NIL NIL) ((S) NIL NIL (MEMP CONS) NIL NIL NIL)
 ((E S E S) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::ALL-NODES"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ENDP G) T) NIL NIL NIL NIL)
 ((NIL) NIL NIL (CONS-SET) NIL NIL NIL) (NIL NIL (CAAR) (MY-UNION) NIL NIL NIL)
 ((G) NIL (STRIP-CARS ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL
  NIL)
 (NIL NIL (CDAR CDR) NIL NIL NIL NIL) ((G G) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::NODEP"
 (NIL NIL NIL (MEMP) NIL NIL NIL) ((N) NIL (ALL-NODES) NIL NIL NIL NIL)
 ((G) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::NEIGHBORS"
 (NIL NIL (STRIP-CARS) NIL NIL NIL NIL) (NIL NIL (CDR) NIL NIL NIL NIL)
 (NIL NIL NIL (ASSOC) NIL NIL NIL) ((N G) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::PATHP-AUX"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL ((ENDP PATH) (ENDP (CDR PATH)) T) NIL NIL NIL NIL)
 ((NIL) NIL NIL (NODEP AND) NIL NIL NIL)
 ((G) NIL (CAR) (MEMP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((PATH G) NIL (CADR CDR) (NEIGHBORS) NIL NIL NIL)
 ((PATH G PATH) NIL (CAR) NIL NIL NIL NIL) ((PATH) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::PATHP"
 (NIL NIL NIL (AND) NIL NIL NIL) (NIL NIL (TRUE-LISTP) (PATHP-AUX) NIL NIL NIL)
 ((PATH PATH G) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::EDGE-LEN"
 (NIL NIL (CDR) NIL NIL NIL NIL) (NIL NIL NIL (ASSOC) NIL NIL NIL)
 ((B) NIL (CDR) NIL NIL NIL NIL) (NIL NIL NIL (ASSOC) NIL NIL NIL)
 ((A G) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::PATH-LEN"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL ((ENDP PATH) (ENDP (CDR PATH)) T) NIL NIL NIL NIL)
 ((NIL) NIL NIL (PLUS) (IF) NIL NIL)
 ((NIL) (0) NIL (NODEP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (EDGE-LEN) NIL
  NIL)
 ((G G G) NIL (CAR CAR CADR CDR) NIL NIL NIL NIL)
 ((PATH PATH PATH PATH) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::PATH"
 (NIL NIL (CDR) NIL NIL NIL NIL) (NIL NIL NIL (ASSOC) NIL NIL NIL)
 ((N PT) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::D"
 (NIL NIL NIL (PATH-LEN) NIL NIL NIL) ((G) NIL NIL (PATH) NIL NIL NIL)
 ((N PT) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::CHOOSE-NEXT"
 (NIL NIL NIL NIL NIL (COND) NIL)
 (NIL NIL
  ((ENDP TS) (ENDP (CDR TS))
   (LT (D (CAR TS) PT G) (D (CHOOSE-NEXT (CDR TS) PT G) PT G)) T)
  NIL NIL NIL NIL)
 (NIL NIL (QUOTE CAR CAR) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL)
 ((NON-NODE TS TS PT G) NIL (CDR) NIL NIL NIL NIL)
 ((TS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::REASSIGN"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ENDP V-LST) T) NIL NIL NIL NIL)
 ((PT) NIL NIL (LET*) NIL NIL NIL)
 (NIL NIL ((V (CAR V-LST))) (COND) NIL NIL NIL)
 (NIL NIL (W (LT (PLUS (D U PT G) W) (D V PT G)) T) NIL NIL NIL NIL)
 (NIL NIL NIL (CONS) (EDGE-LEN) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL)
 ((U V G U PT G) NIL (CDR) (CONS) NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::DSP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ENDP TS) T) NIL NIL NIL NIL)
 ((PT) NIL NIL (LET) NIL NIL NIL)
 (((U (CHOOSE-NEXT TS PT G))) NIL NIL NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 ((G) NIL NIL (DEL) NIL (REASSIGN) NIL)
 ((U TS U PT G) NIL NIL (NEIGHBORS) NIL NIL NIL)
 ((U G) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::DIJKSTRA-SHORTEST-PATH"
 (NIL NIL NIL (LET) NIL NIL NIL)
 (((P (DSP (ALL-NODES G) (LIST (CONS A (LIST A))) G))) NIL NIL (PATH) NIL NIL
  NIL)
 ((B P) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::PATHP-FROM-TO"
 (NIL NIL NIL NIL (AND) NIL NIL) (NIL NIL NIL (PATHP EQUAL EQUAL) NIL NIL NIL)
 ((P G A B) NIL (CAR CAR) NIL NIL NIL NIL) ((P) NIL (LAST) NIL NIL NIL NIL)
 ((P) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::PT-PROPERTYP"
 (NIL NIL NIL NIL (IF) NIL NIL) ((T) NIL (ENDP) (AND) NIL NIL NIL)
 ((PT) NIL NIL (OR) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 ((A G) NIL (NULL CDR) NIL NIL (PATHP-FROM-TO) NIL)
 ((A G PT) NIL (CDAR CDAR CAAR) NIL NIL NIL NIL)
 ((PT PT PT) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::LTE"
 (NIL NIL (NOT) NIL NIL NIL NIL) (NIL NIL NIL (LT) NIL NIL NIL)
 ((N2 N1) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::SHORTERP"
 (NIL NIL NIL (LTE) NIL NIL NIL) (NIL NIL NIL (PATH-LEN PATH-LEN) NIL NIL NIL)
 ((P1 G P2 G) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::CONFINEDP"
 (NIL NIL NIL NIL (IF) NIL NIL) ((T) NIL (ENDP) NIL (IF) NIL NIL)
 ((P T) NIL (ENDP) (AND) NIL NIL NIL)
 (NIL NIL (CDR) (MEMP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((P FS FS) NIL (CAR CDR) NIL NIL NIL NIL) ((P P) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::TS-PROPERTYP"
 (NIL NIL NIL NIL (IF) NIL NIL) ((T) NIL (ENDP) NIL (AND) NIL NIL)
 ((TS) NIL NIL (CONFINEDP) NIL NIL
  (SHORTEST-CONFINED-PATHP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL))
 ((A FS G FS A FS PT G) NIL (CAR CDR) (PATH PATH) NIL NIL NIL)
 ((TS PT PT TS) NIL (CAR CAR) NIL NIL NIL NIL)
 ((TS TS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::FS-PROPERTYP"
 (NIL NIL NIL NIL (IF) NIL NIL) ((T) NIL (ENDP) NIL (AND) NIL NIL)
 ((FS) NIL NIL (CONFINEDP) NIL (SHORTEST-PATHP)
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL))
 ((A G FS0 A FS0 PT G) NIL (CAR CDR) (PATH PATH) NIL NIL NIL)
 ((FS PT PT FS) NIL (CAR CAR) NIL NIL NIL NIL)
 ((FS FS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::COMP-SET"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ENDP) NIL (IF) NIL NIL)
 ((S) NIL NIL (MEMP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL CONS) NIL NIL NIL)
 ((TS TS) NIL (CAR CDR CAR) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL)
 ((S S S TS) NIL (CDR) NIL NIL NIL NIL) ((S) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::INVP"
 (NIL NIL NIL (LET) NIL NIL NIL)
 (((FS (COMP-SET TS (ALL-NODES G)))) NIL NIL NIL (AND) NIL NIL)
 (NIL NIL NIL NIL (PT-PROPERTYP) NIL (TS-PROPERTYP FS-PROPERTYP))
 ((A TS FS PT G A FS FS PT G A PT G) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::FIND-PARTIAL-PATH"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ENDP) NIL (IF) NIL NIL)
 ((P) NIL (LIST) (MEMP CONS) NIL NIL NIL)
 ((S) NIL (CAR CAR CAR) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((P P S P) NIL (CDR) NIL NIL NIL NIL) ((P) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::FIND-LAST-NEXT-PATH"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL NIL (OR CONS) NIL NIL NIL)
 (NIL NIL (ENDP ENDP CAR ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL
  NIL)
 ((P P) NIL (CDR CDR) NIL NIL NIL NIL) ((P P) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::LAST-NODE"
 (NIL NIL (CAR) NIL NIL NIL NIL) (NIL NIL (LAST) NIL NIL NIL NIL)
 (NIL NIL (FIND-LAST-NEXT-PATH) NIL NIL NIL NIL) ((P) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/dijkstra-shortest-path.lisp::FIND-PARTIAL-PATH-TO-U"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL ((NOT (MEMP U P)) (EQUAL (CAR P) U) T) NIL NIL NIL NIL)
 ((NIL) NIL (LIST) (CONS) NIL NIL NIL)
 ((U) NIL (CAR) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((P U) NIL (CDR) NIL NIL NIL NIL) ((P) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
