("/home/acl2/books/rtl/rel9/arithmetic/even-odd2-proofs.lisp::INDUCT-SCHEME"
 (NIL NIL NIL NIL (IF) NIL NIL) ((T) NIL (ZP) (CONS) NIL NIL NIL)
 ((N) NIL 'ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL NIL NIL NIL NIL)
 ((A) NIL NIL (+) NIL NIL NIL) ((N) (-1) NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
