("/home/acl2/books/tools/prove-dollar-tests.lisp::FIRST-SUCCESS-TIME"
 (NIL NIL NIL (TERMLIST) NIL NIL NIL)
 ((TIME-LIMIT STATE) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/prove-dollar-tests.lisp::FIRST-SUCCESS-STEP"
 (NIL NIL NIL (TERMLIST) NIL NIL NIL)
 ((STEP-LIMIT STATE) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
