("/home/acl2/books/arithmetic-5/support/basic-arithmetic.lisp::NONLINEARP-DEFAULT-HINT-PASS1"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL
  (STABLE-UNDER-SIMPLIFICATIONP
   (ACCESS REWRITE-CONSTANT (ACCESS PROVE-SPEC-VAR PSPV :REWRITE-CONSTANT)
           :NONLINEARP)
   T)
  NIL NIL NIL NIL)
 ((NIL) NIL NIL NIL (IF IF) NIL NIL)
 ((NIL NIL) NIL 'QUOTE (EQUAL) (ACCESS) NIL NIL)
 ((REWRITE-CONSTANT :NONLINEARP) NIL (CAAR QUOTE) NIL
  (ACCESS :COMPUTED-HINT-REPLACEMENT :COMPUTED-HINT-REPLACEMENT) NIL NIL)
 ((PROVE-SPEC-VAR PSPV :REWRITE-CONSTANT T :NONLINEARP T HIST
   SETTLED-DOWN-CLAUSE T :NONLINEARP NIL)
  NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
