("/home/acl2/books/rtl/rel9/arithmetic/induct.lisp::OR-DIST-INDUCT"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL NIL (AND) (IF) NIL NIL)
 ((Y) NIL (INTEGERP) (>= = ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL)
 ((N N N) (0 0) (FL 1-) NIL NIL NIL NIL) ((N) NIL NIL (/) NIL NIL NIL)
 ((Y) (2) NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/rtl/rel9/arithmetic/induct.lisp::LOG-INDUCT"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL NIL NIL (IF) (AND) NIL)
 ((NIL) NIL (INTEGERP INTEGERP)
  (>= >= OR ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((I I J J) (0 0) (FL FL) (= =) NIL NIL NIL)
 ((I J) (0 0) NIL (/ /) NIL NIL NIL) ((I J) (2 2) NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/rtl/rel9/arithmetic/induct.lisp::LOGAND-THREE-ARGS-INDUCT"
 (NIL NIL NIL (I) NIL NIL NIL) ((J K) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/rtl/rel9/arithmetic/induct.lisp::LOG-INDUCT-ALLOWS-NEGATIVES"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL NIL (AND) (IF) NIL NIL)
 ((NIL) NIL (INTEGERP INTEGERP) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  (OR) NIL)
 ((I J) NIL (FL FL) (= = = =) NIL NIL NIL)
 ((I J I J) (0 0 -1 -1) NIL (/ /) NIL NIL NIL)
 ((I J) (2 2) NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/rtl/rel9/arithmetic/induct.lisp::OP-DIST-INDUCT"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL NIL (AND) (IF) NIL NIL)
 (NIL NIL (INTEGERP) (>= = LIST) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL)
 ((N N N I J) (0 0) (FL FL 1-) NIL NIL NIL NIL) ((N) NIL NIL (/ /) NIL NIL NIL)
 ((I J) (2 2) NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/rtl/rel9/arithmetic/induct.lisp::NATP-INDUCT"
 (NIL NIL NIL NIL (IF) NIL NIL)
 ((T) NIL (ZP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL NIL)
 ((K) NIL (1-) NIL NIL NIL NIL) ((K) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
