("/home/acl2/books/misc/fibonacci.lisp::FIB-GENERAL"
 (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL ((ZP N) (EQUAL N 0) (EQUAL N 1) (EQUAL N 2) (< 2 N) T) NIL NIL NIL
  NIL)
 ((X Y NIL) (0 0) NIL NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 ((Y) NIL NIL (+ +) NIL NIL NIL) ((X Y N) (-1) NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/fibonacci.lisp::FIB" (NIL NIL NIL NIL NIL (COND) NIL)
 (NIL NIL ((ZP N) (EQUAL N 0) (EQUAL N 1) T) NIL NIL NIL NIL)
 (NIL (0 0 1) NIL (+) NIL NIL NIL)
 (NIL NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 (NIL NIL NIL (- -) NIL NIL NIL) ((N N) (1 2) NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
