("/home/acl2/books/arithmetic-5/lib/basic-ops/simple-equalities-and-inequalities.lisp::FIND-CONSTANT-ADDEND"
 (NIL NIL NIL NIL NIL (COND) NIL)
 (NIL NIL
  ((AND (EQ (FN-SYMB LHS) 'BINARY-+) (EQ (FN-SYMB RHS) 'BINARY-+)
        (NUMERIC-CONSTANT-P (ARG1 LHS)) (NUMERIC-CONSTANT-P (ARG1 RHS)))
   (AND (EQ (FN-SYMB RHS) 'BINARY-+) (NUMERIC-CONSTANT-P LHS)
        (NUMERIC-CONSTANT-P (ARG1 RHS)))
   (AND (EQ (FN-SYMB LHS) 'BINARY-+) (NUMERIC-CONSTANT-P (ARG1 LHS))
        (NUMERIC-CONSTANT-P RHS))
   T)
  NIL NIL NIL NIL)
 ((NIL) NIL NIL
  (LET LET
    LET)
  NIL NIL NIL)
 (NIL NIL ((C (UNQUOTE (ARG1 LHS))) (C (UNQUOTE LHS)) (C (UNQUOTE (ARG1 LHS))))
  NIL NIL (COND COND COND) NIL)
 (NIL NIL
  (D (EQL C 0) (EQL D 0) (< C D) T D (EQL C 0) (EQL D 0) (< C D) T D (EQL C 0)
   (EQL D 0) (< C D) T)
  NIL NIL NIL NIL)
 ((NIL NIL NIL NIL) NIL
  (UNQUOTE SB-INT:QUASIQUOTE SB-INT:QUASIQUOTE UNQUOTE SB-INT:QUASIQUOTE
           SB-INT:QUASIQUOTE SB-INT:QUASIQUOTE UNQUOTE SB-INT:QUASIQUOTE
           . `SB-INT:QUASIQUOTE)
  NIL NIL NIL NIL)
 (((C . ,(KWOTE (- C))) (C . ,(KWOTE (- D))) (C . ,(KWOTE (- D)))
   (C . ,(KWOTE (- C))) (C . ,(KWOTE (- D))) RHS (C . ,(KWOTE (- C)))
   (C . ,(KWOTE (- C))) (C . ,(KWOTE (- D))))
  NIL (ARG1 ARG1) NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/simple-equalities-and-inequalities.lisp::FIND-CONSTANT-FACTOR-EQUAL"
 (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL
  ((AND (EQ (FN-SYMB LHS) 'BINARY-*) (EQ (FN-SYMB RHS) 'BINARY-*)
        (NUMERIC-CONSTANT-P (ARG1 LHS)) (NUMERIC-CONSTANT-P (ARG1 RHS)))
   (AND (EQ (FN-SYMB RHS) 'BINARY-*) (NUMERIC-CONSTANT-P LHS)
        (NUMERIC-CONSTANT-P (ARG1 RHS)))
   (AND (EQ (FN-SYMB LHS) 'BINARY-*) (NUMERIC-CONSTANT-P (ARG1 LHS))
        (NUMERIC-CONSTANT-P RHS))
   (AND (EQ (FN-SYMB RHS) 'BINARY-*) (NUMERIC-CONSTANT-P (ARG1 RHS))
        (NOT (EQ (FN-SYMB (ARG2 RHS)) 'BINARY-*)) (EQ (FN-SYMB LHS) 'BINARY-+))
   (AND (EQ (FN-SYMB LHS) 'BINARY-*) (NUMERIC-CONSTANT-P (ARG1 LHS))
        (NOT (EQ (FN-SYMB (ARG2 LHS)) 'BINARY-*)) (EQ (FN-SYMB RHS) 'BINARY-+))
   (AND (EQ (FN-SYMB RHS) 'BINARY-+) (EQ (FN-SYMB LHS) 'BINARY-+)) T)
  NIL NIL NIL NIL)
 ((NIL NIL) NIL `SB-INT:QUASIQUOTE
  (LET LET
    LET)
  NIL NIL NIL)
 (((C . ,(KWOTE (/ (UNQUOTE (ARG1 LHS)))))
   (C . ,(KWOTE (/ (UNQUOTE (ARG1 RHS))))))
  NIL ((C (UNQUOTE (ARG1 LHS))) (C (UNQUOTE LHS)) (C (UNQUOTE (ARG1 LHS)))) NIL
  NIL (COND COND COND) NIL)
 (NIL NIL
  (D (OR (EQL C 0) (EQL (ABS C) 1)) (OR (EQL D 0) (EQL (ABS D) 1)) (< C D) T D
   (OR (EQL C 0) (EQL (ABS C) 1)) (OR (EQL D 0) (EQL (ABS D) 1)) (< C D) T D
   (OR (EQL C 0) (EQL (ABS C) 1)) (OR (EQL D 0) (EQL (ABS D) 1)) (< C D) T)
  NIL NIL NIL NIL)
 (NIL NIL
  (UNQUOTE SB-INT:QUASIQUOTE SB-INT:QUASIQUOTE SB-INT:QUASIQUOTE
           SB-INT:QUASIQUOTE UNQUOTE SB-INT:QUASIQUOTE SB-INT:QUASIQUOTE
           SB-INT:QUASIQUOTE SB-INT:QUASIQUOTE UNQUOTE SB-INT:QUASIQUOTE
           SB-INT:QUASIQUOTE . `SB-INT:QUASIQUOTE)
  NIL NIL NIL NIL)
 (((C . ,(KWOTE (/ D))) (C . ,(KWOTE (/ C))) (C . ,(KWOTE (/ C)))
   (C . ,(KWOTE (/ D))) (C . ,(KWOTE (/ D))) (C . ,(KWOTE (/ C)))
   (C . ,(KWOTE (/ C))) (C . ,(KWOTE (/ D))) RHS (C . ,(KWOTE (/ D)))
   (C . ,(KWOTE (/ C))) (C . ,(KWOTE (/ C))) (C . ,(KWOTE (/ D))))
  NIL (ARG1 ARG1) NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/simple-equalities-and-inequalities.lisp::FIND-RATIONAL-CONSTANT-FACTOR-<"
 (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL
  ((AND (EQ (FN-SYMB LHS) 'BINARY-*) (EQ (FN-SYMB RHS) 'BINARY-*)
        (RATIONAL-CONSTANT-P (ARG1 LHS)) (RATIONAL-CONSTANT-P (ARG1 RHS)))
   (AND (EQ (FN-SYMB RHS) 'BINARY-*) (RATIONAL-CONSTANT-P LHS)
        (RATIONAL-CONSTANT-P (ARG1 RHS)))
   (AND (EQ (FN-SYMB LHS) 'BINARY-*) (RATIONAL-CONSTANT-P (ARG1 LHS))
        (RATIONAL-CONSTANT-P RHS))
   (AND (EQ (FN-SYMB RHS) 'BINARY-*) (RATIONAL-CONSTANT-P (ARG1 RHS))
        (NOT (EQ (FN-SYMB (ARG2 RHS)) 'BINARY-*)) (EQ (FN-SYMB LHS) 'BINARY-+))
   (AND (EQ (FN-SYMB LHS) 'BINARY-*) (RATIONAL-CONSTANT-P (ARG1 LHS))
        (NOT (EQ (FN-SYMB (ARG2 LHS)) 'BINARY-*)) (EQ (FN-SYMB RHS) 'BINARY-+))
   (AND (EQ (FN-SYMB RHS) 'BINARY-+) (EQ (FN-SYMB LHS) 'BINARY-+)) T)
  NIL NIL NIL NIL)
 ((NIL NIL NIL NIL) NIL NIL
  (LET LET
    LET)
  NIL NIL NIL)
 (NIL NIL ((C (UNQUOTE (ARG1 LHS))) (C (UNQUOTE LHS)) (C (UNQUOTE (ARG1 LHS))))
  NIL NIL (COND COND COND) NIL)
 (NIL NIL
  (D (OR (EQL C 0) (EQL (ABS C) 1)) (OR (EQL D 0) (EQL (ABS D) 1)) (< C D) T D
   (OR (EQL C 0) (EQL (ABS C) 1)) (OR (EQL D 0) (EQL (ABS D) 1)) (< C D) T D
   (OR (EQL C 0) (EQL (ABS C) 1)) (OR (EQL D 0) (EQL (ABS D) 1)) (< C D) T)
  NIL NIL NIL NIL)
 (NIL NIL
  (UNQUOTE SB-INT:QUASIQUOTE SB-INT:QUASIQUOTE SB-INT:QUASIQUOTE
           SB-INT:QUASIQUOTE UNQUOTE SB-INT:QUASIQUOTE SB-INT:QUASIQUOTE
           SB-INT:QUASIQUOTE SB-INT:QUASIQUOTE UNQUOTE SB-INT:QUASIQUOTE
           SB-INT:QUASIQUOTE . `SB-INT:QUASIQUOTE)
  NIL NIL NIL NIL)
 (((C . ,(KWOTE (/ D))) (C . ,(KWOTE (/ C))) (C . ,(KWOTE (/ C)))
   (C . ,(KWOTE (/ D))) (C . ,(KWOTE (/ D))) (C . ,(KWOTE (/ C)))
   (C . ,(KWOTE (/ C))) (C . ,(KWOTE (/ D))) RHS (C . ,(KWOTE (/ D)))
   (C . ,(KWOTE (/ C))) (C . ,(KWOTE (/ C))) (C . ,(KWOTE (/ D))))
  NIL (ARG1 ARG1) NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/simple-equalities-and-inequalities.lisp::FIND-CONSTANT-FACTOR-<"
 (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL
  ((AND (EQ (FN-SYMB LHS) 'BINARY-*) (EQ (FN-SYMB RHS) 'BINARY-*)
        (NUMERIC-CONSTANT-P (ARG1 LHS)) (NUMERIC-CONSTANT-P (ARG1 RHS)))
   (AND (EQ (FN-SYMB RHS) 'BINARY-*) (NUMERIC-CONSTANT-P LHS)
        (NUMERIC-CONSTANT-P (ARG1 RHS)))
   (AND (EQ (FN-SYMB LHS) 'BINARY-*) (NUMERIC-CONSTANT-P (ARG1 LHS))
        (NUMERIC-CONSTANT-P RHS))
   (AND (EQ (FN-SYMB RHS) 'BINARY-*) (NUMERIC-CONSTANT-P (ARG1 RHS))
        (NOT (EQ (FN-SYMB (ARG2 RHS)) 'BINARY-*)) (EQ (FN-SYMB LHS) 'BINARY-+))
   (AND (EQ (FN-SYMB LHS) 'BINARY-*) (NUMERIC-CONSTANT-P (ARG1 LHS))
        (NOT (EQ (FN-SYMB (ARG2 LHS)) 'BINARY-*)) (EQ (FN-SYMB RHS) 'BINARY-+))
   (AND (EQ (FN-SYMB RHS) 'BINARY-+) (EQ (FN-SYMB LHS) 'BINARY-+)) T)
  NIL NIL NIL NIL)
 ((NIL NIL NIL NIL) NIL NIL
  (LET LET
    LET)
  NIL NIL NIL)
 (NIL NIL ((C (UNQUOTE (ARG1 LHS))) (C (UNQUOTE LHS)) (C (UNQUOTE (ARG1 LHS))))
  NIL NIL (COND COND COND) NIL)
 (NIL NIL
  (D (OR (EQL C 0) (EQL (ABS C) 1)) (OR (EQL D 0) (EQL (ABS D) 1)) (< C D) T D
   (OR (EQL C 0) (EQL (ABS C) 1)) (OR (EQL D 0) (EQL (ABS D) 1)) (< C D) T D
   (OR (EQL C 0) (EQL (ABS C) 1)) (OR (EQL D 0) (EQL (ABS D) 1)) (< C D) T)
  NIL NIL NIL NIL)
 (NIL NIL
  (UNQUOTE SB-INT:QUASIQUOTE SB-INT:QUASIQUOTE SB-INT:QUASIQUOTE
           SB-INT:QUASIQUOTE UNQUOTE SB-INT:QUASIQUOTE SB-INT:QUASIQUOTE
           SB-INT:QUASIQUOTE SB-INT:QUASIQUOTE UNQUOTE SB-INT:QUASIQUOTE
           SB-INT:QUASIQUOTE . `SB-INT:QUASIQUOTE)
  NIL NIL NIL NIL)
 (((C . ,(KWOTE (/ D))) (C . ,(KWOTE (/ C))) (C . ,(KWOTE (/ C)))
   (C . ,(KWOTE (/ D))) (C . ,(KWOTE (/ D))) (C . ,(KWOTE (/ C)))
   (C . ,(KWOTE (/ C))) (C . ,(KWOTE (/ D))) RHS (C . ,(KWOTE (/ D)))
   (C . ,(KWOTE (/ C))) (C . ,(KWOTE (/ C))) (C . ,(KWOTE (/ D))))
  NIL (ARG1 ARG1) NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/simple-equalities-and-inequalities.lisp::PRODUCT"
 ((FACTORS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/simple-equalities-and-inequalities.lisp::FIND-RATIONAL-FACTOR-AND-REMAINDER-1"
 (NIL NIL NIL NIL (X) NIL NIL) ((REM MFC STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/simple-equalities-and-inequalities.lisp::FIND-RATIONAL-FACTOR-AND-REMAINDER"
 (NIL NIL NIL (X) NIL NIL NIL) ((MFC STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
