("/home/acl2/books/system/apply/apply.lisp::BADGE"
 ((FN) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/apply/apply.lisp::EV$-MEASURE"
 (NIL NIL (X) NIL NIL NIL NIL) ((A) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/apply/apply.lisp::EV$-LIST-MEASURE"
 (NIL NIL (X) NIL NIL NIL NIL) ((A) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/apply/apply.lisp::APPLY$-MEASURE"
 (NIL NIL NIL NIL NIL (COND) NIL)
 (NIL NIL ((CONSP FN) (EQ FN 'APPLY$) (EQ FN 'EV$) T) NIL NIL NIL NIL)
 (NIL NIL NIL (LLIST LLIST LLIST LLIST) NIL NIL NIL)
 (NIL (0 0 0 0 0) (ACL2-COUNT) (+ +) NIL NIL NIL)
 ((FN) (1 1) (ACL2-COUNT ACL2-COUNT) NIL NIL NIL NIL)
 (NIL NIL (CAR CAR) NIL NIL NIL NIL) ((ARGS ARGS) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/apply/apply.lisp::APPLY$-LAMBDA-MEASURE"
 (NIL NIL (FN) NIL NIL NIL NIL) ((ARGS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/apply/apply.lisp::FN-EQUAL"
 (NIL NIL (FN1) NIL NIL NIL NIL) ((FN2) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/apply/apply.lisp::DEFCONG-FN-EQUAL-EQUAL-EVENTS"
 (NIL NIL NIL (TERM) NIL NIL NIL) ((I C1-CN) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
