("/home/acl2/books/rtl/rel9/arithmetic/mod-proofs.lisp::FL"
 ((X) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/rtl/rel9/arithmetic/mod-proofs.lisp::NATP"
 ((X) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/rtl/rel9/arithmetic/mod-proofs.lisp::INDUCT-NAT"
 (NIL NIL NIL NIL (IF) NIL NIL)
 ((NIL) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (AND) NIL NIL NIL)
 (NIL NIL (INTEGERP 1-) (>) NIL NIL NIL) ((X X X) (0) NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
