("/home/acl2/books/misc/defopener.lisp::SPLITTER1-P"
 (NIL NIL NIL NIL NIL (COND) NIL)
 (NIL NIL
  ((NULL HYPS-LIST) (MEMBER-TERM LIT (CAR HYPS-LIST))
   (MEMBER-COMPLEMENT-TERM LIT (CAR HYPS-LIST)) T)
  NIL NIL NIL NIL)
 ((FOUND-NEGATION NIL) NIL NIL NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL)
 ((LIT FOUND-NEGATION LIT T) NIL (CDR CDR) NIL NIL NIL NIL)
 ((HYPS-LIST HYPS-LIST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/defopener.lisp::SPLITTER"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL ((ENDP HYPS) (SPLITTER1-P (CAR HYPS) HYPS-LIST NIL) T) NIL NIL NIL
  NIL)
 ((NIL) NIL (CAR) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((HYPS HYPS-LIST) NIL (CDR) NIL NIL NIL NIL) ((HYPS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/defopener.lisp::CONCL-AS-EQUIV-AND-LHS-1"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ENDP CONCLS) T) NIL NIL NIL NIL)
 ((NIL) NIL NIL (LET) NIL NIL NIL)
 (((TERM (CAR CONCLS))) NIL NIL NIL NIL (CASE-MATCH) NIL)
 ((TERM) NIL ((!EQUIV !LHS &) ('NOT !LHS) &) NIL NIL NIL NIL)
 (NIL NIL NIL NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  (MSG) NIL)
 ((EQUIV LHS EQUIV LHS
   "The last literal of each clause generated is expected to ~
                   be of the form (equiv lhs rhs) for the same equiv and lhs. ~
                   The equiv for the last literal of the first clause is ~x0 ~
                   and its lhs is ~x1; but the last literal of one clause ~
                   generated is:~|~%~x2"
   EQUIV LHS TERM)
  NIL (CDR CDR) NIL NIL NIL NIL))
("/home/acl2/books/misc/defopener.lisp::CONCL-AS-EQUIV-AND-LHS"
 (NIL NIL NIL (ASSERT$) NIL NIL NIL) ((CONCLS) NIL NIL (LET) NIL NIL NIL)
 (((TERM (CAR CONCLS))) NIL NIL NIL NIL (CASE-MATCH) NIL)
 ((TERM) NIL ((!EQUIV LHS &) ('NOT LHS) &) NIL NIL NIL NIL)
 (NIL NIL NIL
  (LET LET
    MV)
  NIL NIL NIL)
 (((MSG (CONCL-AS-EQUIV-AND-LHS-1 EQUIV LHS (CDR CONCLS)))
   (MSG (CONCL-AS-EQUIV-AND-LHS-1 EQUIV LHS (CDR CONCLS))) NIL)
  NIL NIL (COND COND MSG) NIL NIL NIL)
 (("The last literal of each clause generated is expected ~
                        to be of the form (equiv lhs rhs), the but last ~
                        literal of the first clause generated is:~|~%~x0"
   TERM)
  NIL (MSG T MSG T) NIL NIL NIL NIL))
("/home/acl2/books/misc/defopener.lisp::REMOVE-TERM"
 (NIL NIL NIL NIL NIL NIL (COND))
 (NIL NIL
  ((VARIABLEP LIT) (FQUOTEP LIT) (MEMBER-EQUAL LIT CL)
   (OR (EQ (FFN-SYMB LIT) 'EQUAL) (EQ (FFN-SYMB LIT) 'IFF)) T)
  NIL NIL NIL NIL)
 (NIL NIL NIL (REMOVE1-EQ REMOVE1-EQUAL REMOVE1-EQUAL LET ASSERT$) NIL NIL NIL)
 ((LIT CL LIT CL LIT CL
   (NEW-LIT (FCONS-TERM* (FFN-SYMB LIT) (FARGN LIT 2) (FARGN LIT 1))))
  NIL NIL (ASSERT$ EQ LET) NIL NIL NIL)
 (((ATM (FARGN LIT 1))) NIL (FFN-SYMB QUOTE)
  (MEMBER-EQUAL REMOVE1-EQUAL ASSERT$) NIL NIL NIL)
 ((NEW-LIT CL NEW-LIT CL LIT NOT) NIL NIL (LET*) (AND) NIL NIL)
 (NIL NIL
  (NVARIABLEP NOT
              (NEW-ATM
               (FCONS-TERM* (FFN-SYMB ATM) (FARGN ATM 2) (FARGN ATM 1))))
  (OR ASSERT$) NIL NIL NIL))
("/home/acl2/books/misc/defopener.lisp::SPLIT-CL-LIST"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL ((ENDP HYPS-LIST) (MEMBER-TERM SPLITTER (CAR HYPS-LIST)) T) NIL NIL
  NIL NIL)
 (NIL NIL NIL (ASSERT$) NIL (MV) NIL)
 ((SPLITTER NEG-HYPS-LIST NEG-CONCLS) NIL
  (REVERSE REVERSE REVERSE REVERSE CDR CDR) (CONS CONS MEMBER-COMPLEMENT-TERM)
  NIL NIL NIL)
 ((POS-HYPS-LIST POS-CONCLS NEG-HYPS-LIST NEG-CONCLS HYPS-LIST CONCLS
   POS-HYPS-LIST POS-CONCLS SPLITTER SPLITTER POS-HYPS-LIST POS-CONCLS)
  NIL (CAR CAR CDR CDR) (REMOVE-TERM CONS CONS) NIL NIL NIL)
 ((SPLITTER CONCLS HYPS-LIST HYPS-LIST CONCLS NEG-HYPS-LIST NEG-CONCLS) NIL
  (CAR CAR) (REMOVE-TERM) NIL NIL NIL)
 ((HYPS-LIST CONCLS) NIL (DUMB-NEGATE-LIT CAR) NIL NIL NIL NIL))
("/home/acl2/books/misc/defopener.lisp::INDEX-OF-SHORTEST-REC"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ENDP LST-LST) T) NIL NIL NIL NIL)
 ((ANS) NIL NIL (LET) NIL NIL NIL)
 (((NEW-LEN (LENGTH (CAR LST-LST)))) NIL NIL NIL (IF) NIL NIL)
 (NIL NIL NIL (<) NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL)
 ((NEW-LEN LEN NEW-LEN I LEN ANS) NIL (CDR 1+ CDR 1+) NIL NIL NIL NIL)
 ((LST-LST I LST-LST I) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/defopener.lisp::INDEX-OF-SHORTEST"
 ((LST-LST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/defopener.lisp::MEMBER-EQUAL-ALL"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ENDP LST-LST) T) NIL NIL NIL NIL)
 ((T) NIL NIL (AND) NIL NIL NIL)
 (NIL NIL NIL (MEMBER-EQUAL ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL)
 ((X X) NIL (CAR CDR) NIL NIL NIL NIL)
 ((LST-LST LST-LST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/defopener.lisp::INTERSECTION-EQUAL-WITH-ALL"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL ((ENDP LST) (MEMBER-EQUAL-ALL (CAR LST) LST-LST) T) NIL NIL NIL NIL)
 ((NIL) NIL NIL (CONS ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((LST-LST) NIL (CAR CDR) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL)
 ((LST LST-LST LST) NIL (CDR) NIL NIL NIL NIL) ((LST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/defopener.lisp::ALL-SET-DIFFERENCE-EQUAL"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ENDP LST-LST) T) NIL NIL NIL NIL)
 ((NIL) NIL NIL (CONS) NIL NIL NIL)
 (NIL NIL NIL (SET-DIFFERENCE-EQUAL ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL)
 ((LST LST) NIL (CAR CDR) NIL NIL NIL NIL)
 ((LST-LST LST-LST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/defopener.lisp::DEFOPENER-REMOVE1-BY-POSITION"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ENDP) NIL (IF) NIL NIL)
 ((LST) NIL (ZP CDR) (CONS) NIL NIL NIL)
 ((INDEX LST) NIL (CAR) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((LST) NIL (1- CDR) NIL NIL NIL NIL) ((INDEX LST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/defopener.lisp::SPLIT-CLAUSES-TO-TERM-REC"
 (NIL NIL NIL (LET*) NIL NIL NIL)
 (((SPLITTER (SPLITTER (CAR HYPS-LIST) (CDR HYPS-LIST)))) NIL NIL NIL (COND)
  NIL NIL)
 (NIL NIL (SPLITTER (NULL (CDR CONCLS)) T) NIL NIL NIL NIL)
 (NIL NIL NIL (MV MV) (MV-LET) NIL NIL)
 ((NIL T) NIL NIL (FARGN LET*) (POS-HYPS-LIST MV-LET) NIL NIL)
 ((POS-CONCLS NEG-HYPS-LIST NEG-CONCLS SPLITTER HYPS-LIST CONCLS NIL NIL NIL
   NIL)
  (2) (FLG1 CAR) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (MV-LET) (MV-LET)
  NIL)
 ((NEG NEG-HYPS-LIST NEG-CONCLS CONCLS) NIL
  (FLG2 HYPS CONCL HYPS-LIST CONCLS COMMON-HYPS HYPS-LIST HYPS TBR FLG DECLARE)
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL MV
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  (IF) NIL NIL))
("/home/acl2/books/misc/defopener.lisp::SPLIT-CLAUSES-TO-FLG-TERM-PAIR"
 (NIL NIL NIL NIL (MV-LET) NIL NIL)
 (NIL NIL (FLG) (SPLIT-CLAUSES-TO-TERM-REC CONS) NIL NIL NIL)
 ((TERM HYPS-LIST CONCLS FLG TERM) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/defopener.lisp::SPLIT-OUT-CONCLS"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ENDP CL-LIST) T) NIL NIL NIL NIL)
 (NIL NIL NIL (MV) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 (NIL NIL (REVERSE REVERSE CDR) (CONS CONS) NIL NIL NIL)
 ((HYPS-LIST CONCLS CL-LIST HYPS-LIST CONCLS) NIL (CAR) (BUTLAST) NIL NIL NIL)
 (NIL (1) (CAR LAST) NIL NIL NIL NIL) ((CL-LIST) NIL (CAR) NIL NIL NIL NIL))
("/home/acl2/books/misc/defopener.lisp::FLATTEN-IFS-TO-COND"
 (NIL NIL NIL NIL NIL (CASE-MATCH) NIL)
 ((TERM) NIL (('IF TST ('IF X Y Z) FBR) ('IF TST TBR FBR) &) NIL NIL NIL NIL)
 ((TERM) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL SB-INT:QUASIQUOTE) NIL
  NIL NIL NIL)
 (NIL NIL (SB-INT:QUASIQUOTE) NIL (IF) NIL NIL)
 ((,(CONJOIN (FLATTEN-ANDS-IN-LIT TST)) ,TBR ,(FLATTEN-IFS-TO-COND FBR)) NIL
  NIL NIL (IF) NIL NIL)
 ((,(CONJOIN2 TST X) ,Y) NIL NIL NIL (IF) NIL NIL)
 ((,(CONJOIN2 TST (DUMB-NEGATE-LIT X)) ,Z ,FBR) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/defopener.lisp::BASH-SIM-FN"
 (NIL NIL NIL (ER-LET*) NIL NIL NIL)
 (((CL-LIST
    (WITH-CTX-SUMMARIZED CTX (SIMPLIFY-WITH-PROVER FORM HINTS CTX STATE))))
  NIL NIL NIL (MV-LET) NIL NIL)
 (NIL NIL (HYPS-LIST) NIL (SPLIT-OUT-CONCLS MV-LET) NIL NIL)
 ((CONCLS CL-LIST NIL NIL) NIL (EQUIV) (CONCL-AS-EQUIV-AND-LHS COND) NIL NIL
  NIL)
 ((LHS CONCLS EQUIV) NIL (EQUIV T) NIL NIL NIL NIL)
 (NIL NIL (VALUE) NIL NIL (ER) NIL)
 ((SOFT CTX "~@0" LHS) NIL NIL (SPLIT-CLAUSES-TO-FLG-TERM-PAIR) NIL NIL NIL))
("/home/acl2/books/misc/defopener.lisp::DEFOPENER-HINT-DEF"
 (NIL NIL (SB-INT:QUASIQUOTE) NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL (DEFUN) NIL)
 ((DEFOPENER-HINT) NIL (DECLARE) (AND) (ID) NIL NIL)
 ((CLAUSE WORLD STABLE-UNDER-SIMPLIFICATIONP STABLE-UNDER-SIMPLIFICATIONP) NIL
  NIL (IGNORE LET) NIL NIL NIL)
 ((ID WORLD (TERM (CAR (LAST CLAUSE)))
   ,(COND
     (FLATTEN-FAILED-FLG
      '(CASE-MATCH TERM ((& & ('HIDE X)) (LIST :EXPAND (LIST (LIST 'HIDE X))))
                   ((& ('HIDE X) &) (LIST :EXPAND (LIST (LIST 'HIDE X))))
                   (('NOT ('HIDE X)) (LIST :EXPAND (LIST (LIST 'HIDE X))))
                   (& NIL)))
     (T
      '(CASE-MATCH TERM
                   ((& & ('HIDE X))
                    (LIST :EXPAND (LIST (LIST 'HIDE X)) :IN-THEORY
                          '(THEORY 'MINIMAL-THEORY)))
                   ((& ('HIDE X) &)
                    (LIST :EXPAND (LIST (LIST 'HIDE X)) :IN-THEORY
                          '(THEORY 'MINIMAL-THEORY)))
                   (('NOT ('HIDE X))
                    (LIST :EXPAND (LIST (LIST 'HIDE X)) :IN-THEORY
                          '(THEORY 'MINIMAL-THEORY)))
                   (& NIL)))))
  NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
