("/home/acl2/books/std/osets/computed-hints.lisp::REWRITING-GOAL-LIT"
 (NIL NIL (MFC) NIL NIL NIL NIL) ((STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/osets/computed-hints.lisp::REWRITING-CONC-LIT"
 (NIL NIL NIL (TERM) NIL NIL NIL) ((MFC STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/osets/computed-hints.lisp::HARVEST-TRIGGER"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ENDP) NIL (IF) NIL NIL)
 ((CLAUSE) NIL NIL (AND CONS ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL)
 ((TRIGGER-FN) NIL (CONSP CAR CDR)
  (EQ ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((TRIGGER-FN CLAUSE TRIGGER-FN CLAUSE) NIL (CAR CAAR CDR) NIL NIL NIL NIL)
 ((CLAUSE CLAUSE CLAUSE) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/osets/computed-hints.lisp::OTHERS-TO-NEGATED-LIST"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ENDP) NIL (IF) NIL NIL)
 ((OTHERS) NIL NIL (AND CONS CONS) NIL NIL NIL)
 (NIL NIL
  (CONSP SECOND ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
         ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  (EQUAL LIST) NIL NIL NIL)
 (NIL NIL (CAR CAAR QUOTE CAR CDR QUOTE CAR CDR) NIL NIL NIL NIL)
 ((OTHERS OTHERS NOT OTHERS OTHERS NOT OTHERS OTHERS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/osets/computed-hints.lisp::OTHERS-TO-HYPS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((T) NIL (ENDP) (LET) NIL NIL NIL)
 ((OTHERS (NEGATED (OTHERS-TO-NEGATED-LIST OTHERS))) NIL NIL NIL (IF) NIL NIL)
 (NIL NIL (ENDP CAR) (CONS) NIL NIL NIL)
 ((NEGATED) NIL (CDR QUOTE OTHERS-TO-NEGATED-LIST) NIL NIL NIL NIL)
 ((NEGATED AND OTHERS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/osets/computed-hints.lisp::BUILD-HINT"
 (NIL NIL NIL (LET*) NIL NIL NIL)
 (NIL NIL
  ((BASE-PRED (CONS GENERIC-PREDICATE (CONS '?X (CDDR TRIGGER))))
   SB-INT:QUASIQUOTE)
  NIL NIL NIL NIL)
 (NIL NIL (PRED-SUB) NIL NIL NIL (:FUNCTIONAL-INSTANCE))
 ((,GENERIC-THEOREM) NIL
  (,GENERIC-HYPS ,GENERIC-COLLECTION ,GENERIC-COLLECTION-P ,GENERIC-PREDICATE)
  (INSTANCE-REWRITE) NIL NIL NIL)
 ((BASE-PRED PREDICATE-REWRITE) NIL NIL (LAMBDA LAMBDA LAMBDA LAMBDA) NIL NIL
  NIL)
 ((NIL ,HYPS-SUB NIL ,(SECOND TRIGGER) ?X
   ,(CONS COLLECTION-P-SUB (CONS '?X (CDDR TRIGGER))) ?X ,PRED-SUB)
  NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/osets/computed-hints.lisp::BUILD-HINTS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ENDP) (CONS) NIL NIL NIL)
 ((TRIGGERS) NIL NIL NIL NIL NIL NIL)
 ((GENERIC-THEOREM GENERIC-HYPS GENERIC-COLLECTION GENERIC-PREDICATE
   GENERIC-COLLECTION-P COLLECTION-P-SUB HYPS-SUB PREDICATE-REWRITE
   GENERIC-THEOREM GENERIC-HYPS GENERIC-COLLECTION GENERIC-PREDICATE
   GENERIC-COLLECTION-P COLLECTION-P-SUB HYPS-SUB PREDICATE-REWRITE)
  NIL (CAR CDR) NIL NIL NIL NIL)
 ((TRIGGERS TRIGGERS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/osets/computed-hints.lisp::AUTOMATE-INSTANTIATION-FN"
 (NIL NIL (SB-INT:QUASIQUOTE) NIL NIL NIL NIL)
 (NIL NIL NIL NIL (ENCAPSULATE) NIL NIL)
 ((NIL) NIL (ADD-DEFAULT-HINTS!) NIL NIL (DEFUN) NIL)
 ((,NEW-HINT-NAME) NIL (QUOTE) (DECLARE) (ID IF) NIL NIL)
 ((CLAUSE WORLD STABLE NIL
   (,NEW-HINT-NAME ID CLAUSE WORLD STABLE-UNDER-SIMPLIFICATIONP))
  NIL (NOT) (XARGS IGNORE LET) NIL NIL NIL)
 ((:MODE :PROGRAM ID WORLD STABLE
   (TRIGGERS (HARVEST-TRIGGER CLAUSE ,TRIGGER-SYMBOL)))
  NIL NIL NIL (IF) NIL NIL)
 ((NIL) NIL (NOT) (LET*) NIL NIL NIL))
