("/home/acl2/books/misc/seqw.lisp::SEQW-PROCESS-BIND"
 (NIL NIL NIL NIL (X) NIL NIL) ((STREAM WARNINGS REST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/seqw.lisp::SEQW-FN" (NIL NIL NIL (STREAM) NIL NIL NIL)
 ((WARNINGS BLOCK) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/seqw.lisp::SEQW-BACKTRACK-FN"
 (NIL NIL NIL (STREAM) NIL NIL NIL) ((WARNINGS BLOCKS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
