("/home/acl2/books/tools/k-induction.lisp::PK-INDUCTION"
 (NIL NIL NIL NIL (IF) NIL NIL)
 ((T) NIL NIL (OR ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((PARAMS) NIL (ZP) (PK PK-BADGUY) NIL NIL NIL)
 ((N N PARAMS N PARAMS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/k-induction.lisp::Q-PARAMS"
 (NIL NIL NIL NIL (Q) NIL NIL) ((N) NIL NIL (NTH NTH) NIL NIL NIL)
 ((PARAMS PARAMS) (0 1) NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/k-induction.lisp::Q-PARAMS-BADGUY"
 (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL
  ((ZP N) (NOT (Q-PARAMS (- N 1) PARAMS)) (EQUAL N 1)
   (NOT (Q-PARAMS (- N 2) PARAMS)) (EQUAL N 2) T)
  NIL NIL NIL NIL)
 (NIL (0 0 0) NIL (- - -) NIL NIL NIL) ((N N N) (1 2 3) NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
