("/home/acl2/books/tools/easy-simplify.lisp::EASY-SIMPLIFY-TERM1-FN"
 (NIL NIL NIL NIL NIL NIL NIL)
 ((HYPS HINTS EQUIV NORMALIZE REWRITE REPEAT BACKCHAIN-LIMIT STATE) NIL NIL NIL
  NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/easy-simplify.lisp::EASY-SIMPLIFY-TERM-FN"
 (NIL NIL NIL NIL NIL NIL NIL)
 ((HYP-TERM HINTS EQUIV NORMALIZE REWRITE REPEAT BACKCHAIN-LIMIT UNTRANS-RESULT
   STATE)
  NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
