("/home/acl2/books/system/convert-normalized-term-to-pairs.lisp::NORMALIZEDP"
 (NIL NIL NIL NIL NIL (COND) NIL)
 (NIL NIL ((VARIABLEP TERM) (FQUOTEP TERM) (EQ (FFN-SYMB TERM) 'IF) T) NIL NIL
  NIL NIL)
 ((T T T) NIL NIL NIL (AND) NIL NIL)
 (NIL NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  (OR) NIL NIL NIL)
 (NIL NIL (SYMBOLP) (AND FARGN FARGN) NIL NIL NIL)
 ((TERM TERM) (2 3) (NOT NOT) (FARGN) NIL NIL NIL)
 ((TERM) (1) (FQUOTEP) (EQ) NIL NIL NIL))
("/home/acl2/books/system/convert-normalized-term-to-pairs.lisp::CNTP-M-PAIR"
 (NIL NIL NIL NIL NIL (FCONS-TERM*) NIL)
 ((*T*) NIL (QUOTE CONJOIN CDR) NIL NIL NIL NIL)
 ((IF PAIR) NIL (CAR) NIL NIL NIL NIL) ((PAIR) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/convert-normalized-term-to-pairs.lisp::CNTP-M"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ENDP PAIRS) T) NIL NIL NIL NIL)
 ((*T*) NIL NIL NIL NIL (FCONS-TERM*) NIL)
 ((*NIL*) NIL (QUOTE CNTP-M-PAIR ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL NIL NIL)
 ((IF) NIL (CAR CDR) NIL NIL NIL NIL) ((PAIRS PAIRS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/convert-normalized-term-to-pairs.lisp::CONVERT-NORMALIZED-TERM-TO-PAIRS"
 (NIL NIL NIL NIL NIL (COND) NIL)
 (NIL NIL ((VARIABLEP TERM) (FQUOTEP TERM) (EQ (FFN-SYMB TERM) 'IF) T) NIL NIL
  NIL NIL)
 (NIL NIL NIL (CONS CONS) (IF COND) NIL NIL)
 ((ANS ANS ANS) NIL
  ((EQUAL (FARGN TERM 3) *NIL*) (EQUAL (FARGN TERM 2) *NIL*) T)
  (CONS EQUAL COND CONS) NIL NIL NIL)
 ((TERM TERM *NIL* TERM) NIL ((CONSP RHYPS) T) (REVAPPEND REVAPPEND)
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL)
 ((RHYPS NIL RHYPS RHYPS RHYPS NIL) NIL NIL
  (CONS CONS FARGN CONS FARGN CONS CONS FARGN)
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 ((ANS ANS TERM ANS TERM ANS RHYPS TERM ANS) (2 3 2) NIL
  (CONS CONS CONS CONS FARGN CONS FARGN) NIL NIL NIL))
