("/home/acl2/books/arithmetic/sumlist.lisp::SUMLIST"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL (0) (CONSP) (+) NIL NIL NIL)
 ((X) NIL (CAR ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL NIL)
 ((X) NIL (CDR) NIL NIL NIL NIL) ((X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
