("/home/acl2/books/rtl/rel9/arithmetic/negative-syntaxp.lisp::NEGATIVE-SYNTAXP"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (NOT) NIL NIL NIL NIL)
 (NIL NIL (CONSP CAR QUOTE UNARY-- BINARY-+ BINARY-* OTHERWISE) NIL NIL NIL
  NIL)
 ((TERM TERM NIL) NIL (NOT AND) (AND AND) NIL NIL NIL)
 (NIL NIL
  (RATIONALP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
             ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
             ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  (< OR) NIL NIL NIL)
 (NIL (0) (CADR CADR CADR CADR CADDR) (AND AND) NIL NIL NIL)
 ((TERM TERM TERM TERM TERM) NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL NOT NOT
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL))
