("/home/acl2/books/system/origin.lisp::ORIGIN-FN"
 (NIL NIL NIL (LET*) NIL NIL NIL)
 (((WRLD (W STATE))) NIL NIL (COND) NIL NIL NIL)
 (NIL NIL ((ACL2-SYSTEM-NAMEP LOGICAL-NAME WRLD) T) NIL NIL NIL NIL)
 (NIL NIL (VALUE) (LET) NIL NIL NIL)
 ((:BUILT-IN (EV-WRLD (DECODE-LOGICAL-NAME LOGICAL-NAME WRLD))) NIL NIL (COND)
  NIL NIL NIL)
 (NIL NIL (EV-WRLD T) NIL NIL NIL NIL) (NIL NIL (VALUE) NIL (MV) NIL NIL))
