("/home/acl2/books/centaur/fty/fixtype.lisp::GET-FIXTYPES-ALIST"
 (NIL NIL (CDR) NIL NIL NIL NIL) (NIL NIL NIL (ASSOC) NIL NIL NIL)
 (NIL NIL (QUOTE) (TABLE-ALIST) NIL NIL NIL)
 ((FIXTYPE-ALIST WORLD) NIL (QUOTE) NIL NIL NIL NIL)
 ((FIXTYPES) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/centaur/fty/fixtype.lisp::FIND-FIXTYPE-FOR-PRED"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (LET*) NIL NIL NIL)
 ((ALIST (FIXTYPE (CDAR ALIST))) NIL NIL NIL (IF) NIL NIL)
 ((FIXTYPE) NIL NIL (EQ ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((PRED PRED) NIL (FIXTYPE->PRED CDR) NIL NIL NIL NIL)
 ((FIXTYPE ALIST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/centaur/fty/fixtype.lisp::FIND-FIXTYPE-FOR-EQUIV"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (LET*) NIL NIL NIL)
 ((ALIST (FIXTYPE (CDAR ALIST))) NIL NIL NIL (IF) NIL NIL)
 ((FIXTYPE) NIL NIL (EQ ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((EQUIV EQUIV) NIL (FIXTYPE->EQUIV CDR) NIL NIL NIL NIL)
 ((FIXTYPE ALIST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/centaur/fty/fixtype.lisp::FIND-FIXTYPE-FOR-TYPENAME"
 (NIL NIL (CDR) NIL NIL NIL NIL) (NIL NIL NIL (ASSOC) NIL NIL NIL)
 ((NAME ALIST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/centaur/fty/fixtype.lisp::FIND-FIXTYPE"
 (NIL NIL NIL (OR) NIL NIL NIL)
 (NIL NIL NIL (FIND-FIXTYPE-FOR-TYPENAME FIND-FIXTYPE-FOR-PRED) NIL NIL NIL)
 ((TYPENAME ALIST TYPENAME ALIST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/centaur/fty/fixtype.lisp::DEFFIXEQUIV-BASIC-PARSE"
 (NIL NIL NIL NIL NIL (FORM) NIL)
 ((ARG TYPE KEYS STATE) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/centaur/fty/fixtype.lisp::FIXEQUIV-EVENTS"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (NIL NIL (((UNLESS FIXEQUIV) '(VALUE-TRIPLE :SKIPPED)) SB-INT:QUASIQUOTE) NIL
  NIL NIL NIL)
 (NIL NIL ((FIXEQUIV X)) NIL (PROGN) NIL NIL)
 ((FIXEQUIV ,@(AND X.CONST-THM `((WITH-OUTPUT :ON (ERROR) ,X.CONST-THM)))
   ,@(AND X.CONG-THM
          `((MAKE-EVENT
             '(:OR (WITH-OUTPUT :ON (ERROR) ,X.CONG-THM)
               (WITH-OUTPUT :ON (ERROR)
                            (VALUE-TRIPLE
                             (ER HARD? 'FIXEQUIV
                                 "The congruence theorem failed: this is unexpected because ~
                  this should be automatic once the fixing theorem succeeds.  ~
                  Please try again with :verbosep t to diagnose the problem."))))))))
  NIL NIL NIL (WITH-OUTPUT) NIL NIL)
 ((:STACK :POP ,X.FIX-THM) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/centaur/fty/fixtype.lisp::DEFFIXCONG-PARSE"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (NIL NIL ((FIXTYPES (GET-FIXTYPES-ALIST (W STATE)))) NIL NIL NIL
  (DEFFIXEQUIV-BASIC-PARSE))
 ((FORM VAR STATE) NIL (IN-FIXTYPE FIXTYPE->NAME) NIL (LIST*) NIL NIL)
 ((IN-FIXTYPE :OUT-EQUIV OUT-EQUIV KEYS) NIL NIL (FIND-FIXTYPE-FOR-EQUIV) NIL
  NIL NIL)
 ((IN-EQUIV FIXTYPES) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
