("/home/acl2/books/misc/defp.lisp::DEFPUN-ADD-TEST"
 (NIL NIL (TEST) NIL NIL NIL NIL)
 ((TESTS-AND-STUFF-LST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/defp.lisp::DEFPUN-CALLS-TESTS-AND-ARGS-LST"
 (NIL NIL NIL NIL NIL (CASE-MATCH) NIL)
 ((TERM) NIL ((!FN . ARGS) ('IF TEST TBR FBR) &) NIL NIL NIL NIL)
 ((NIL) NIL (LIST) (LET) NIL NIL NIL)
 (NIL NIL ((TBR-TESTS-AND-ARGS-LST (DEFPUN-CALLS-TESTS-AND-ARGS-LST FN TBR)))
  (CONS APPEND) NIL NIL NIL)
 ((NIL ARGS) NIL (FBR-TESTS-AND-ARGS-LST) (DEFPUN-ADD-TEST DEFPUN-ADD-TEST) NIL
  NIL NIL)
 ((TEST TBR-TESTS-AND-ARGS-LST FBR-TESTS-AND-ARGS-LST) NIL (DUMB-NEGATE-LIT)
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((FN FBR TEST) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/defp.lisp::DEFPUN-TESTS-AND-BASE-LST"
 (NIL NIL NIL NIL NIL (CASE-MATCH) NIL)
 ((TERM) NIL ((!FN . &) ('IF TEST TBR FBR) &) NIL NIL NIL NIL)
 ((NIL) NIL (LIST) (LET) NIL NIL NIL)
 (NIL NIL ((TBR-BASE (DEFPUN-TESTS-AND-BASE-LST FN TBR))) (APPEND CONS) NIL NIL
  NIL)
 ((NIL TERM) NIL (FBR-BASE) (DEFPUN-ADD-TEST DEFPUN-ADD-TEST) NIL NIL NIL)
 ((TEST TBR-BASE FBR-BASE) NIL (DUMB-NEGATE-LIT)
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((FN FBR TEST) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/defp.lisp::MAP-CONJOIN" ((LST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/defp.lisp::DEFPUN-DISJOIN-TESTS"
 ((TESTS-AND-ARGS-LST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/defp.lisp::DEFPUN-MAKE-NTH-ARG"
 (NIL NIL (TESTS-AND-ARGS-LST) NIL NIL NIL NIL) ((N) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/defp.lisp::DEFPUN-MAKE-CALL"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL (ZP) (CONS-TERM LET) NIL NIL NIL)
 ((N FN ACC (N (1- N))) NIL NIL NIL NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL)
 ((FN TESTS-AND-ARGS-LST N) NIL NIL (CONS) NIL NIL NIL)
 ((ACC) NIL NIL (DEFPUN-MAKE-NTH-ARG) NIL NIL NIL)
 ((TESTS-AND-ARGS-LST N) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/defp.lisp::DEFPUN-MAKE-BASE"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL (ENDP CDAR) NIL NIL (FCONS-TERM*) NIL)
 ((TESTS-AND-BASE-LST) NIL
  (CDR QUOTE CONJOIN CDAR ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL
  NIL)
 ((TESTS-AND-BASE-LST IF TESTS-AND-BASE-LST) NIL (CAAR CDR) NIL NIL NIL NIL)
 ((TESTS-AND-BASE-LST TESTS-AND-BASE-LST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
