("/home/acl2/books/projects/apply/loop-lemmas.lisp::FROM-TO-BY-DOWN"
 (NIL NIL (I) NIL NIL NIL NIL) ((J) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/projects/apply/loop-lemmas.lisp::FROM-TO-BY1"
 (NIL NIL NIL (I) NIL NIL NIL) ((J K) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/projects/apply/loop-lemmas.lisp::LOOP$-AS-CDR-CDR"
 (NIL NIL (LST1) NIL NIL NIL NIL) ((LST2) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/projects/apply/loop-lemmas.lisp::LOOP$-AS-CDR-FB"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ENDP LST) T) NIL NIL NIL NIL)
 (NIL NIL NIL NIL (LIST ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 ((LST LO BY BY) NIL (CDR) (+) NIL NIL NIL)
 ((LST BY LO) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/projects/apply/loop-lemmas.lisp::LOOP$-AS-CDR-FTB"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL NIL NIL (COND) (AND LIST) NIL)
 ((LST LO HI BY) NIL (INTEGERP INTEGERP INTEGERP (ENDP LST) (< HI LO) T) (<)
  NIL NIL NIL)
 ((LO HI BY BY) (0) NIL NIL NIL
  (LIST LIST ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL)
 ((LST LO HI BY LST LO HI BY HI BY) NIL (CDR) (+) NIL NIL NIL)
 ((LST BY LO) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/projects/apply/loop-lemmas.lisp::LOOP$-AS-FTB-FTB"
 (NIL NIL NIL NIL NIL NIL (LO1))
 ((HI1 BY1 LO2 HI2 BY2) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
