("/home/acl2/books/misc/file-io.lisp::COLLECT-OBJECTS"
 (NIL NIL NIL NIL (MV-LET) NIL NIL)
 (NIL NIL NIL (EOFP READ-OBJECT) (IF) NIL NIL)
 ((OBJ STATE CHANNEL STATE EOFP) NIL NIL (MV)
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 ((STATE CHANNEL STATE) NIL (REVERSE) (CONS) NIL NIL NIL)
 ((LIST OBJ LIST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/file-io.lisp::READ-LIST"
 (NIL NIL NIL NIL (MV-LET) NIL NIL)
 (NIL NIL (CHANNEL) NIL (OPEN-INPUT-CHANNEL IF) NIL NIL)
 ((STATE FNAME :OBJECT STATE CHANNEL) NIL NIL NIL (MV-LET) (ER) NIL)
 ((SOFT CTX "Unable to open file ~s0 for :object input." FNAME) NIL (RESULT)
  (LET) (COLLECT-OBJECTS) NIL NIL)
 ((STATE NIL CHANNEL STATE (STATE (CLOSE-INPUT-CHANNEL CHANNEL STATE))) NIL
  (VALUE) NIL NIL NIL NIL)
 ((RESULT) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/file-io.lisp::PPRINT-OBJECT-OR-STRING"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL (STRINGP) NIL (PRINC$) (MV-LET) NIL)
 ((OBJ OBJ CHANNEL STATE STATE) NIL (DECLARE) (ERP STATE-GLOBAL-LET*) NIL NIL
  NIL)
 ((VAL STATE (WRITE-FOR-READ T)) NIL NIL (PPROGN IGNORE) NIL NIL NIL)
 ((ERP VAL) NIL (VALUE) NIL NIL NIL (PPR2))
 ((CHANNEL STATE T NIL) (0) NIL NIL NIL NIL NIL)
 ((OBJ PRINT-BASE PRINT-RADIX STATE T) (80 0) NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/file-io.lisp::WRITE-OBJECTS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((STATE) NIL (CONSP) NIL NIL (PPROGN) NIL)
 ((LIST) NIL NIL (NEWLINE NEWLINE)
  (PPRINT-OBJECT-OR-STRING ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 ((CHANNEL STATE CHANNEL STATE CHANNEL STATE CHANNEL STATE) NIL (CAR CDR) NIL
  NIL NIL NIL)
 ((LIST LIST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/file-io.lisp::WRITE-LIST-BODY-FN"
 (NIL NIL (SB-INT:QUASIQUOTE) NIL NIL NIL NIL) (NIL NIL NIL (LET) NIL NIL NIL)
 (((QUIETP ,QUIETP)) NIL NIL NIL (IF) NIL NIL)
 (NIL NIL (NOT) NIL (MV-LET) (ER) NIL)
 ((SOFT CTX "The filename argument of write-list must evaluate to a string, ~
              but it has evaluated to ~x0.  See :DOC write-list."
   FNAME
   ,(IF BANGP
        '(OPEN-OUTPUT-CHANNEL! FNAME :CHARACTER STATE)
        '(OPEN-OUTPUT-CHANNEL FNAME :CHARACTER STATE)))
  NIL (STRINGP CHANNEL) NIL (IF) NIL NIL)
 ((FNAME STATE CHANNEL) NIL NIL NIL NIL (MV-LET ER) NIL)
 ((SOFT CTX "Unable to open file ~s0 for :character output." FNAME) NIL
  (COL DECLARE) (COND LET) NIL NIL NIL))
("/home/acl2/books/misc/file-io.lisp::WRITE-LIST-FN"
 (NIL NIL NIL NIL (IF) NIL NIL)
 ((QUIET) NIL NIL (WRITE-LIST-BODY WRITE-LIST-BODY) NIL NIL NIL)
 ((NIL T NIL NIL) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
