("/home/acl2/books/tools/prove-dollar.lisp::EXTEND-PROVER-ERROR-OUTPUT-OFF"
 (NIL NIL (STRING-ALIST) NIL NIL NIL NIL) ((STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/prove-dollar.lisp::FORMAL-QUOTE-ARGS"
 ((LST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/prove-dollar.lisp::PROVE$-FN"
 (NIL NIL NIL NIL NIL NIL NIL)
 ((STATE HINTS INSTRUCTIONS OTF-FLG IGNORE-OK SKIP-PROOFS
   PROVER-ERROR-OUTPUT-OFF CATCH-HARD-ERROR)
  NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/prove-dollar.lisp::MAKE-WITH-PROVER-TIME-LIMIT"
 (NIL NIL (SB-INT:QUASIQUOTE) NIL NIL NIL NIL) (NIL NIL NIL (LET) NIL NIL NIL)
 (((WITH-PROVER-TIME-LIMIT+-VAR ,TIME)) NIL NIL NIL (IF) NIL NIL)
 ((WITH-PROVER-TIME-LIMIT+-VAR ,FORM) NIL NIL (WITH-PROVER-TIME-LIMIT) NIL NIL
  NIL)
 ((WITH-PROVER-TIME-LIMIT+-VAR) NIL NIL (CHECK-VARS-NOT-FREE) NIL NIL NIL)
 ((WITH-PROVER-TIME-LIMIT+-VAR ,FORM) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/prove-dollar.lisp::PROVE$-MACRO-FN"
 (NIL NIL NIL NIL NIL NIL NIL)
 ((HINTS INSTRUCTIONS OTF-FLG WITH-OUTPUT TIME-LIMIT STEP-LIMIT IGNORE-OK
   SKIP-PROOFS PROVER-ERROR-OUTPUT-OFF CATCH-HARD-ERROR)
  NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
