("/home/acl2/books/projects/numbers/pratt.lisp::FIND-ORDER"
 (NIL NIL NIL (R) NIL NIL NIL) ((K P) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/projects/numbers/pratt.lisp::ORDER"
 (NIL NIL NIL NIL (FIND-ORDER) NIL NIL) ((R P) (1) NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/projects/numbers/pratt.lisp::MAX-ORDER-P"
 (NIL NIL NIL NIL (AND) NIL NIL) (NIL NIL (NOT) (< =) NIL NIL NIL)
 ((R P) NIL (ZP 1-) (ORDER) NIL NIL NIL) ((R R P P) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/projects/numbers/pratt.lisp::MOD-POWERS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ZP) (CONS) NIL NIL NIL)
 ((N) NIL NIL (MOD) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 ((P R P) NIL (1-) (EXPT) NIL NIL NIL) ((R N N) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/projects/numbers/pratt.lisp::FAST-MOD-EXPT-MUL"
 (NIL NIL NIL NIL (IF) NIL NIL) ((R) NIL (ZP) NIL (IF) NIL NIL)
 ((E) NIL (ZP) NIL NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL)
 ((N R N) NIL (FL FL) (MOD MOD MOD MOD) NIL NIL NIL)
 ((E N N N) (2) NIL (* / * / *) NIL NIL NIL)
 ((B B E B B E R B) (2 2) NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/projects/numbers/pratt.lisp::FAST-MOD-EXPT"
 (NIL NIL NIL NIL NIL (FAST-MOD-EXPT-MUL) NIL)
 ((B E N) (1) NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/projects/numbers/pratt.lisp::PROD-POWERS"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL (1) (CONSP) (*) NIL NIL NIL)
 ((F) NIL NIL (EXPT ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 (NIL NIL (CAR CAR CDR CDR) NIL NIL NIL NIL)
 ((F E F E) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/projects/numbers/pratt.lisp::DISTINCT-FACTORS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((T) NIL (CONSP) NIL NIL (AND) NIL)
 ((F) NIL (NATP NOT ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (>) NIL NIL NIL)
 (NIL (1) (CAR CAR CDR) (MEMBER) NIL NIL NIL)
 ((F F F) NIL (CAR CDR) NIL NIL NIL NIL) ((F F) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/projects/numbers/pratt.lisp::ALL-POSITIVE"
 (NIL NIL NIL NIL (IF) NIL NIL) ((T) NIL (CONSP) (AND) NIL NIL NIL)
 ((E) NIL (NOT ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL NIL)
 (NIL NIL (ZP CDR) NIL NIL NIL NIL) ((E) NIL (CAR) NIL NIL NIL NIL)
 ((E) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/projects/numbers/pratt.lisp::FACTORIZATION"
 (NIL NIL NIL NIL NIL (AND) NIL)
 (NIL NIL (DISTINCT-FACTORS ALL-POSITIVE) (= =) NIL NIL NIL)
 ((F E N) NIL (LEN LEN) (PROD-POWERS) NIL NIL NIL)
 ((F E F E) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/projects/numbers/pratt.lisp::ALL-PRIME"
 (NIL NIL NIL NIL (IF) NIL NIL) ((T) NIL (CONSP) (AND) NIL NIL NIL)
 ((F) NIL (PRIMEP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((F F) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/projects/numbers/pratt.lisp::PRIME-FACTORIZATION"
 (NIL NIL NIL (AND) NIL NIL NIL)
 (NIL NIL (ALL-PRIME) NIL (FACTORIZATION) NIL NIL)
 ((N F E F) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/projects/numbers/pratt.lisp::MAX-ORDER-BY-FACTORIZATION"
 (NIL NIL NIL NIL (IF) NIL NIL) ((T) NIL (CONSP) (AND) NIL NIL NIL)
 ((F) NIL (NOT) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 ((R P) NIL (CDR) (=) NIL NIL NIL) ((F) (1) NIL NIL (MOD-EXPT) NIL NIL)
 ((R P) NIL NIL (/) NIL NIL NIL) (NIL NIL (1- CAR) NIL NIL NIL NIL))
("/home/acl2/books/projects/numbers/pratt.lisp::FIND-PRIM-ROOT"
 (NIL NIL NIL (P) NIL NIL NIL) ((F K) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/projects/numbers/pratt.lisp::CERTIFICATE-25519"
 (NIL NIL (QUOTE) NIL NIL NIL NIL) (NIL NIL NIL NIL (2) NIL NIL)
 (NIL NIL NIL NIL (2 2 NIL) NIL NIL)
 ((NIL NIL)
  (3 65147
   74058212732561358302231226437062788676166966415465897661863160754340907 1 1
   1)
  NIL NIL (2) NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL)
 ((NIL NIL NIL NIL NIL)
  (3 353 57467 132049 1923133 31757755568855353
   75445702479781427272750846543864801 1 1 1 1 1 1 1)
  NIL NIL (10 7) NIL NIL)
 (NIL NIL NIL NIL NIL NIL (2 5 NIL)))
("/home/acl2/books/projects/numbers/pratt.lisp::CERTIFY-PRIMES"
 (NIL NIL NIL NIL (IF) NIL NIL) ((LISTP) NIL NIL NIL (IF IF) NIL NIL)
 (NIL NIL (CONSP NULL CONSP PRIMEP) (LET) (AND) NIL NIL)
 ((C P C P) NIL (CONSP) NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL (R (CAR C)))
  NIL NIL)
 ((P NIL T) NIL (CAR CAR CDR CDR F E C NATP NOT) (> < =)
  (FACTORIZATION FAST-MAX-FACT ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL)
 ((P C P C P P F E R P R P F T F C) (1 1) (CADR CADDR CADDDR 1- ZP) NIL
  (FAST-MOD-EXPT) NIL NIL)
 ((C C C P R R P) NIL (1-) NIL NIL NIL NIL))
("/home/acl2/books/projects/numbers/pratt.lisp::CERTIFY-PRIME"
 (NIL NIL NIL NIL (CERTIFY-PRIMES) NIL NIL) ((NIL P C) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
