("/home/acl2/books/sorting/how-many.lisp::HOW-MANY"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL ((ENDP X) (EQUAL E (CAR X)) T) NIL NIL NIL NIL)
 (NIL (0) (1+) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((E) NIL (CDR) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((E X) NIL (CDR) NIL NIL NIL NIL) ((X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
