("/home/acl2/books/std/util/defmapping-templates.lisp::GEN-EQS"
 (NIL NIL NIL (COND) NIL NIL NIL)
 (NIL NIL ((OR (ATOM LEFTS) (ATOM RIGHTS)) T) NIL NIL NIL NIL)
 ((NIL) NIL NIL (CONS) NIL NIL NIL)
 (NIL NIL (SB-INT:QUASIQUOTE) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL NIL)
 (NIL NIL (CDR CDR) (EQUAL) NIL NIL NIL)
 ((,(CAR LEFTS) ,(CAR RIGHTS) LEFTS RIGHTS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
