("/home/acl2/books/arithmetic-3/floor-mod/floor-mod.lisp::RATIONALP-GUARD-FN"
 (NIL NIL NIL NIL (IF) NIL NIL)
 (NIL NIL (ENDP SB-INT:QUASIQUOTE) (CONS) NIL NIL NIL)
 (((RATIONALP ,(CAR ARGS))) NIL
  (CDR . `ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL NIL)
 ((ARGS) NIL (RATIONALP CDR) NIL NIL NIL NIL)
 ((,(CAR ARGS) ARGS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/floor-mod/floor-mod.lisp::FLOOR-INDUCT-FN"
 (NIL NIL (X) NIL NIL NIL NIL) ((Y) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/floor-mod/floor-mod.lisp::MOD-INDUCT-FN"
 (NIL NIL (X) NIL NIL NIL NIL) ((Y) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/floor-mod/floor-mod.lisp::MOD-+-CANCEL-0-FN-1"
 (NIL NIL (X) NIL NIL NIL NIL) ((Z) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/floor-mod/floor-mod.lisp::MOD-+-CANCEL-0-FN"
 (NIL NIL (X) NIL NIL NIL NIL) ((Z) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/floor-mod/floor-mod.lisp::FACTORS-CCC"
 ((PRODUCT) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/floor-mod/floor-mod.lisp::NON-ZERO-INTERSECTION-EQUAL"
 (NIL NIL NIL NIL (X) NIL NIL) ((Y MFC STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/floor-mod/floor-mod.lisp::MAKE-PRODUCT-CCC"
 ((FACTORS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/floor-mod/floor-mod.lisp::FIND-COMMON-FACTORS"
 (NIL NIL NIL NIL (X) NIL NIL) ((Y MFC STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/floor-mod/floor-mod.lisp::FIND-CANCELLING-ADDENDS"
 (NIL NIL NIL NIL (X) NIL NIL) ((Y MFC STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/floor-mod/floor-mod.lisp::SIMPLIFY-MOD-+-MOD-FN"
 (NIL NIL NIL NIL (X) NIL NIL) ((Y MFC STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/floor-mod/floor-mod.lisp::SIMPLIFY-MOD-+-MINUS-MOD-FN"
 (NIL NIL NIL NIL (X) NIL NIL) ((Y MFC STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
