("/home/acl2/books/tools/defmacfun.lisp::MACFUN-FIND-NEXT-&WORD-INDEX"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) NIL (IF) NIL NIL)
 ((FORMALS) (0) NIL (MEMBER-EQ LET) NIL NIL NIL)
 ((*MACFUN-&WORDS* (IDX (MACFUN-FIND-NEXT-&WORD-INDEX (CDR FORMALS)))) NIL
  (CAR) (AND) NIL NIL NIL)
 ((FORMALS IDX) NIL (1+) NIL NIL NIL NIL) ((IDX) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/defmacfun.lisp::MACFUN-SPLIT-FORMALS-AT-NEXT-&WORD"
 (NIL NIL NIL (LET) NIL NIL NIL)
 (((IDX (MACFUN-FIND-NEXT-&WORD-INDEX FORMALS))) NIL NIL NIL (IF) NIL NIL)
 ((IDX) NIL NIL (MV MV) NIL NIL NIL)
 ((FORMALS NIL) NIL NIL (TAKE NTHCDR) NIL NIL NIL)
 ((IDX FORMALS IDX FORMALS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/defmacfun.lisp::MACFUN-FORMALS-TO-MACRO-FORMALS"
 (NIL NIL NIL (LET*) NIL NIL NIL)
 (((MEM (MEMBER-EQ '&AUTO FORMALS))) NIL NIL NIL (IF) NIL NIL)
 ((MEM FORMALS) NIL NIL (LET*) NIL NIL NIL)
 (NIL NIL NIL (APPEND) NIL ((LEN (LEN FORMALS))) NIL)
 ((PREFIX SUFFIX) NIL (LENREST PREFIX SUFFIX-IDX SUFFIX) NIL NIL NIL NIL)
 (NIL NIL (LEN MACFUN-FIND-NEXT-&WORD-INDEX) (TAKE AND) NIL NIL NIL)
 ((MEM FORMALS SUFFIX-IDX) NIL (CDR) (- NTHCDR) NIL NIL NIL))
("/home/acl2/books/tools/defmacfun.lisp::MACFUN-KEY/OPT/AUTOS-TO-FUNCTION-FORMALS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (LET) NIL NIL NIL)
 ((FORMALS (REST (MACFUN-KEY/OPT/AUTOS-TO-FUNCTION-FORMALS (CDR FORMALS)))) NIL
  NIL NIL NIL NIL NIL)
 (NIL NIL (LEN 0 1 2 3 OTHERWISE) NIL NIL NIL NIL)
 ((REST) NIL (CAR) (CONS CONS CONS) (LIST*) NIL NIL)
 ((FORMALS REST REST REST REST) NIL (CAR CAAR CAAR CAAR CADDAR) NIL NIL NIL
  NIL)
 ((FORMALS FORMALS FORMALS FORMALS FORMALS) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/defmacfun.lisp::MACFUN-FORMALS-TO-FUNCTION-FORMALS1"
 (NIL NIL NIL NIL NIL NIL (CASE))
 (NIL NIL
  (CAR (&WHOLE &REST &BODY) (&OPTIONAL &KEY &AUTO) &ALLOW-OTHER-KEYS OTHERWISE)
  NIL NIL NIL NIL)
 ((FORMALS) NIL NIL (MV)
  (IF MV-LET
      MV-LET)
  NIL NIL)
 ((NIL) NIL
  (CONSP KEY/OPT/AUTOS MACFUN-SPLIT-FORMALS-AT-NEXT-&WORD CDR REQS
         MACFUN-SPLIT-FORMALS-AT-NEXT-&WORD)
  (MV MV MV MV) NIL NIL NIL)
 ((NIL NIL FORMALS FORMALS FORMALS REST FORMALS REQS REST) NIL
  (CDR LIST CDDR CDR MACFUN-KEY/OPT/AUTOS-TO-FUNCTION-FORMALS) NIL NIL NIL NIL)
 ((FORMALS FORMALS FORMALS KEY/OPT/AUTOS) NIL (CADR) NIL NIL NIL NIL)
 ((FORMALS) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/defmacfun.lisp::MACFUN-FORMALS-TO-FUNCTION-FORMALS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) NIL (MV-LET) NIL NIL)
 ((FORMALS) NIL (FN-FORMALS MACFUN-FORMALS-TO-FUNCTION-FORMALS1) (APPEND) NIL
  NIL NIL)
 ((REST FORMALS FN-FORMALS) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL NIL NIL)
 ((REST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/defmacfun.lisp::MACFUN-AUTOS-TO-FUNCTION-ACTUALS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (CONS) NIL NIL NIL)
 ((AUTOS) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (LIST) NIL NIL NIL)
 (NIL NIL 'CDR NIL NIL NIL (CASE))
 ('AUTOS NIL (LEN 0 1 2 OTHERWISE) NIL NIL NIL NIL)
 (NIL NIL (CAR CAR CAAR CADAR) NIL NIL (ER) NIL)
 ((AUTOS AUTOS AUTOS AUTOS HARD?
   "An &auto binding should either be just a variable
or a form (variable term), which ~x0 isn't.~%")
  NIL 'CAR NIL NIL NIL NIL))
("/home/acl2/books/tools/defmacfun.lisp::MACFUN-FORMALS-TO-FUNCTION-ACTUALS1"
 (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL
  (CAR (&WHOLE &REST &BODY) &AUTO (&OPTIONAL &KEY) &ALLOW-OTHER-KEYS OTHERWISE)
  NIL NIL NIL NIL)
 ((FORMALS) NIL NIL (MV)
  (IF MV-LET
      MV-LET
      MV-LET)
  NIL NIL)
 ((NIL) NIL
  (CONSP AUTOS MACFUN-SPLIT-FORMALS-AT-NEXT-&WORD KEY/OPTS
         MACFUN-SPLIT-FORMALS-AT-NEXT-&WORD CDR REQS
         MACFUN-SPLIT-FORMALS-AT-NEXT-&WORD)
  (MV MV MV MV MV) NIL NIL NIL)
 ((NIL NIL FORMALS FORMALS FORMALS FORMALS FORMALS REST FORMALS REQS REST) NIL
  (CDR LIST CDDR CDR MACFUN-AUTOS-TO-FUNCTION-ACTUALS CDR
       MACFUN-KEY/OPT/AUTOS-TO-FUNCTION-FORMALS)
  NIL NIL NIL NIL)
 ((FORMALS FORMALS FORMALS AUTOS FORMALS KEY/OPTS) NIL NIL NIL (LIST) NIL NIL)
 (NIL NIL (QUOTE QUOTE CADR) NIL NIL NIL NIL))
("/home/acl2/books/tools/defmacfun.lisp::MACFUN-FORMALS-TO-FUNCTION-ACTUALS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) NIL (MV-LET) NIL NIL)
 ((FORMALS) NIL (ACTUALS MACFUN-FORMALS-TO-FUNCTION-ACTUALS1) (APPEND) NIL NIL
  NIL)
 ((REST FORMALS ACTUALS) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL NIL)
 ((REST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/defmacfun.lisp::MACFUN-GET-NONSTRINGS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) NIL (IF) NIL NIL)
 ((X) NIL (STRINGP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (CONS) NIL NIL
  NIL)
 (NIL NIL (CAR CDR CAR ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL
  NIL)
 ((X X X) NIL (CDR) NIL NIL NIL NIL) ((X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/defmacfun.lisp::MACFUN-GET-STRINGS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) NIL (IF) NIL NIL)
 ((X) NIL (STRINGP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (CONS) NIL NIL
  NIL)
 (NIL NIL (CAR CAR ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL CDR) NIL NIL NIL
  NIL)
 ((X X X) NIL (CDR) NIL NIL NIL NIL) ((X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
