("/home/acl2/books/tools/pattern-match.lisp::INTERN-CHECK"
 (NIL NIL NIL NIL (IF) NIL NIL)
 (NIL NIL NIL (EQUAL INTERN INTERN-IN-PACKAGE-OF-SYMBOL) NIL NIL NIL)
 (("COMMON-LISP" STR "ACL2" STR SYM) NIL (SYMBOL-PACKAGE-NAME) NIL NIL NIL NIL)
 ((SYM) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/pattern-match.lisp::PATTERN-BINDINGS-LIST"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL NIL (OR LET* LET) NIL NIL NIL)
 (NIL NIL (ATOM ATOM . `(LHS (CAR LHSES))) NIL NIL (COND) NIL)
 ((LHSES RHSES) NIL
  (FINAL-TESTS DECLARE BODY NEXTCALL ACTION FINAL-TEST BINDINGS-AND-BODY TESTS
   TESTCLAUSE RHS (SYMBOLP LHS) (ATOM LHS) (EQ (CAR LHS) 'QUOTE) T)
  NIL (,ACTION) NIL NIL)
 ((,TESTCLAUSE ,BINDINGS-AND-BODY ,NEXTCALL) NIL (CAR)
  (NTH NTH NTH NTH NTH REVAPPEND PBL-TESTS-BINDINGS PBL-TESTS-BINDINGS LET*)
  (IF IF
      IF)
  NIL (COND))
 ((PMSTATE PMSTATE PMSTATE PMSTATE PMSTATE FINAL-TESTS NIL BODY TESTS
   FINAL-TEST RHSES BINDINGS BINDINGS)
  (1 2 3 4 5)
  (SB-INT:QUASIQUOTE SB-INT:QUASIQUOTE SB-INT:QUASIQUOTE
   (OR (EQ LHS T) (EQ LHS NIL))
   (AND (> (LENGTH (SYMBOL-NAME LHS)) 0) (EQL #\* (CHAR (SYMBOL-NAME LHS) 0)))
   (AND (> (LENGTH (SYMBOL-NAME LHS)) 0) (EQL #\! (CHAR (SYMBOL-NAME LHS) 0)))
   (EQ LHS '&) T)
  (OR < CONS CONS (FUNC (CAR LHS))) (IF) NIL NIL)
 (((LET ,(REVERSE BINDINGS)
     ,@TESTS-DECLARE
     (AND ,@FINAL-TESTS))
   NIL TESTS TESTS FUNC-PM-MACRO RHS ARGS TESTS BINDINGS PMSTATE)
  (1) (LEN AND CONSP CAR ARGS FUNC-PM-MACRO CDR CDR)
  (EQ EQ PBL-TESTS-BINDINGS PBL-TESTS-BINDINGS PBL-TESTS-BINDINGS
      PBL-TESTS-BINDINGS LET EQUAL-X-CONSTANT EQUAL-X-CONSTANT)
  (LET) NIL NIL))
("/home/acl2/books/tools/pattern-match.lisp::TEST-DECLARE"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (LIST) (AND) NIL NIL NIL)
 ((ELT) NIL (CONSP) (EQ) NIL NIL NIL) ((ELT) NIL (CAR QUOTE) NIL NIL NIL NIL)
 ((ELT DECLARE) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/pattern-match.lisp::SLICE-CLAUSE"
 (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL (LEN 0 1 2 3 OTHERWISE) NIL NIL NIL NIL)
 ((CLAUSE) NIL NIL (LET LET*) NIL NIL (MV MV MV))
 ((NIL NIL NIL NIL NIL NIL NIL NIL NIL NIL NIL
   (DECL (TEST-DECLARE (CADR CLAUSE))))
  NIL (CAR CADR) NIL (ER ER IF) NIL ((N (LEN CLAUSE)) MV))
 ((HARD "Empty clause" HARD "Pattern needs a body" CLAUSE CLAUSE DECL PATTERN
   MAYBE-TEST-DECLARE TESTS MAYBE-BODY-DECLARE BODY)
  NIL (QUOTE QUOTE PATTERN MAYBE-TEST-DECLARE MAYBE-BODY-DECLARE BODY TESTS)
  NIL NIL NIL (MV MV))
 ((TOP-LEVEL TOP-LEVEL NIL NIL DECL NIL NIL) NIL
  (CAR CADDR CAR LIST CADDR CAR TEST-DECLARE TEST-DECLARE) (NTH) (IF) NIL NIL)
 ((CLAUSE CLAUSE CLAUSE CLAUSE CLAUSE CLAUSE MAYBE-TEST-DECLARE) NIL (CADR)
  (NTH NTH -) (IF IF) NIL NIL))
("/home/acl2/books/tools/pattern-match.lisp::PATTERN-MATCH-CLAUSES"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) NIL (MV-LET) NIL NIL)
 ((CLAUSES) NIL (SLICE-CLAUSE) (COND) NIL (PATTERN) NIL)
 ((TEST-DECL FINAL-TESTS BODY-DECL BODY) NIL
  (CAR (AND (EQ PATTERN '&) (NULL FINAL-TESTS)) T) NIL NIL NIL NIL)
 ((CLAUSES BODY) NIL NIL NIL NIL NIL (PATTERN-BINDINGS-LIST))
 ((NIL NIL) NIL (LIST LIST) NIL NIL NIL NIL)
 ((PATTERN TERM TEST-DECL FINAL-TESTS BODY-DECL BODY ACTION) NIL
  (SB-INT:QUASIQUOTE) NIL NIL NIL NIL))
("/home/acl2/books/tools/pattern-match.lisp::PATTERN-MATCH-LIST-CLAUSES"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) NIL (MV-LET) NIL NIL)
 ((CLAUSES) NIL (SLICE-CLAUSE) NIL (COND) (PATTERNS) NIL)
 ((TEST-DECL FINAL-TESTS BODY-DECL BODY) NIL
  (CAR (AND (EQ PATTERNS '&) (NULL FINAL-TESTS))
       (= (LEN PATTERNS) (LEN TERM-LIST)) T)
  NIL NIL NIL NIL)
 ((CLAUSES BODY) NIL NIL NIL NIL NIL (PATTERN-BINDINGS-LIST ER))
 ((PATTERNS TERM-LIST NIL NIL HARD
   "Lengths of term list ~x0 and pattern list ~x1 are unequal" TERM-LIST
   PATTERNS)
  NIL (QUOTE) NIL NIL NIL NIL)
 ((TEST-DECL FINAL-TESTS BODY-DECL BODY ACTION TOP-LEVEL) NIL
  (SB-INT:QUASIQUOTE) NIL NIL NIL NIL))
("/home/acl2/books/tools/pattern-match.lisp::DESTRUCTOR-SUBST-LIST"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (CONS) NIL NIL NIL)
 ((DESTRUCTORS) NIL NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (IF) NIL
  NIL)
 ((TERM) NIL (CONSP . `CDR) NIL (SUBST) NIL NIL)
 ((TERM DESTRUCTORS) NIL (CAR QUOTE EXPLODE-TERM) (LIST) NIL NIL NIL)
 ((DESTRUCTORS TERM TERM) NIL (CAR QUOTE) NIL NIL NIL NIL)
 ((DESTRUCTORS ,(CAR DESTRUCTORS)) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/pattern-match.lisp::DESTRUCTOR-LIST"
 (NIL NIL NIL NIL (IF) NIL NIL)
 ((NIL) NIL (ATOM SB-INT:QUASIQUOTE) NIL NIL NIL NIL)
 ((DESTRUCTORS) NIL ((LIST ',(CAR DESTRUCTORS) TERM)) NIL NIL NIL NIL)
 ((,@(DESTRUCTOR-LIST (CDR DESTRUCTORS))) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/pattern-match.lisp::LIST-OF-NTHS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (SB-INT:QUASIQUOTE) (=) NIL NIL NIL)
 ((N LEN) NIL ((NTH ,N ,TERM)) NIL NIL NIL NIL)
 ((,@(LIST-OF-NTHS (1+ N) LEN TERM)) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/pattern-match.lisp::EQUAL-ANY-LIST"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ENDP) (CONS) NIL NIL NIL)
 ((ARGS) NIL (SB-INT:QUASIQUOTE) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL NIL)
 ((TERM) NIL (CDR) (EQUAL) NIL NIL NIL)
 ((,TERM ,(CAR ARGS) ARGS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/pattern-match.lisp::REMOVE-UP-TO"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) NIL (IF) NIL NIL)
 ((LIST) NIL (CDR) (EQUAL ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL)
 ((ITEM LIST ITEM) NIL (CAR CDR) NIL NIL NIL NIL)
 ((LIST LIST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
