("/home/acl2/books/misc/simp.lisp::SIMP-PAIRS"
 (NIL NIL NIL NIL (CLAUSES) NIL NIL) ((WRLD STATE ACC) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
