("/home/acl2/books/std/stobjs/clone.lisp::CLONE-STOBJ-CHANGE-SYMBOL"
 (NIL NIL NIL NIL (IF) NIL NIL) ((RENAMING SYM) NIL NIL (B*) NIL NIL NIL)
 (NIL NIL (((LIST PREFIX SUFFIX STRSUBST PKG) RENAMING))
  (INTERN-IN-PACKAGE-OF-SYMBOL) NIL NIL NIL)
 (NIL NIL ((MV SUB PKG?)) (OR) NIL (CONCATENATE) NIL)
 ((PREFIX SUB SUFFIX PKG? PKG) NIL (QUOTE) (TMPL-STR-SUBLIS) NIL NIL NIL)
 ((STRSUBST STRING) NIL (SYMBOL-NAME) NIL NIL NIL NIL)
 ((SYM) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/stobjs/clone.lisp::CLONE-STOBJ-PROCESS-RENAME-ALIST"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (CONS) NIL NIL NIL)
 ((RENAME-ALIST) NIL NIL (LIST ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL NIL)
 ((RENAMING) NIL (CDR) (CLONE-STOBJ-CHANGE-SYMBOL CLONE-STOBJ-CHANGE-SYMBOL)
  NIL NIL NIL)
 ((RENAMING RENAMING RENAME-ALIST) NIL (CAAR CADAR) NIL NIL NIL NIL)
 ((RENAME-ALIST RENAME-ALIST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/stobjs/clone.lisp::CLONE-STOBJ-PROCESS-FIELDS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (CONS) NIL NIL NIL)
 ((FIELDS) NIL NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (IF) NIL NIL)
 ((RENAMING) NIL (CONSP CDR) (CONS CLONE-STOBJ-CHANGE-SYMBOL) NIL NIL NIL)
 ((RENAMING FIELDS) NIL (CAR CDAR CAR) (CLONE-STOBJ-CHANGE-SYMBOL) NIL NIL NIL)
 ((FIELDS RENAMING FIELDS FIELDS) NIL (CAAR) NIL NIL NIL NIL)
 ((FIELDS) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/stobjs/clone.lisp::KEEP-NONBOOL-SYMBOLS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (LET*) NIL NIL NIL)
 ((X (K (CAR X))) NIL NIL NIL (IF) NIL NIL)
 (NIL NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (CONS) (AND) NIL NIL)
 ((K K) NIL (NOT SYMBOLP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL CDR) NIL NIL
  NIL NIL)
 ((K X) NIL (CDR) (EQ) NIL NIL NIL) ((K T X) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/stobjs/clone.lisp::STOBJ-FIELD-TEMPLATE-FNNAMES"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (CONS) NIL NIL NIL)
 ((FIELD-TEMPLATES) NIL (CAAR) (APPEND) NIL NIL NIL)
 ((FIELD-TEMPLATES) NIL
  (KEEP-NONBOOL-SYMBOLS ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL
  NIL)
 (NIL NIL (CDDDAR CDR) NIL NIL NIL NIL)
 ((FIELD-TEMPLATES FIELD-TEMPLATES) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/stobjs/clone.lisp::STOBJ-TEMPLATE-FNNAMES"
 (NIL NIL NIL NIL (LIST*) NIL NIL)
 (NIL NIL (CAR CADR STOBJ-FIELD-TEMPLATE-FNNAMES) NIL NIL NIL NIL)
 ((TEMPLATE TEMPLATE) NIL (CADDR) NIL NIL NIL NIL)
 ((TEMPLATE) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/stobjs/clone.lisp::CLONE-STOBJ-PROCESS-ARGS"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (NIL NIL NIL NIL
  (((MV ERP FIELD-DESCRIPTORS KEY-ALIST)
    (PARTITION-REST-AND-KEYWORD-ARGS ARGS *DEFSTOBJ-KEYWORDS*))
   APPEND)
  NIL NIL)
 ((FIELDS) NIL ((WHEN ERP) INLINE FIELDS) (AND LIST) NIL NIL NIL)
 ((INLINE :CONGRUENT-TO STOBJNAME) NIL NIL
  (ASSOC-EQ CLONE-STOBJ-PROCESS-FIELDS LIST) (ER) NIL NIL)
 ((HARD? "The stobj to be cloned had bad keyword args~%" :INLINE KEY-ALIST
   FIELD-DESCRIPTORS RENAMING :INLINE)
  NIL 'CDR NIL NIL NIL NIL)
 ((DEFSTOBJ-CLONE INLINE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/stobjs/clone.lisp::CLONE-STOBJ-REWRITE"
 (NIL NIL NIL (LET) NIL NIL NIL)
 (((THMNAME
    (INTERN-IN-PACKAGE-OF-SYMBOL
     (CONCATENATE 'STRING (SYMBOL-NAME NEWFN) "-IS-" (SYMBOL-NAME OLDFN))
     NEWFN)))
  NIL (SB-INT:QUASIQUOTE) NIL NIL NIL NIL)
 (NIL NIL
  ((DEFTHM ,THMNAME (EQUAL (,NEWFN . ,FORMALS) (,OLDFN . ,FORMALS)) :HINTS
           (("goal" :IN-THEORY '(,NEWFN ,OLDFN))
            (AND STABLE-UNDER-SIMPLIFICATIONP
                 '(:IN-THEORY (E/D** (CLONE-STOBJ-TMP-RULES))))
            (AND STABLE-UNDER-SIMPLIFICATIONP
                 '(:IN-THEORY '(,NEWFN ,OLDFN (:INDUCTION ,NEWFN)))))))
  NIL NIL NIL NIL)
 (NIL NIL (LOCAL) NIL NIL NIL NIL) (NIL NIL NIL (ADD-TO-RULESET!) NIL NIL NIL)
 ((CLONE-STOBJ-TMP-RULES ,THMNAME) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/stobjs/clone.lisp::CLONE-STOBJ-REWRITES"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (NIL NIL NIL (APPEND) (((WHEN (ATOM NEW)) NIL)) NIL NIL)
 (NIL NIL (NEWFN FORMALS OLDFN) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  (CLONE-STOBJ-REWRITE) NIL NIL)
 ((NEWFN OLDFN FORMALS) NIL (CAAR CADAR CAAR CDR CDR) NIL NIL NIL NIL)
 ((NEW NEW OLD NEW OLD) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/stobjs/clone.lisp::CLONE-ABSSTOBJ-EXPORTS"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (NIL NIL NIL (CONS) NIL NIL (((WHEN (ATOM ABSSTOBJ-TUPLES)) NIL)))
 (NIL NIL
  ((LIST* NAME LOGIC EXEC UPDATER) NAME-EXPORT-LOOKUP NEW-SYM UPDATER PROTECT
   SB-INT:QUASIQUOTE)
  NIL NIL NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL))
 ((EXPORTS RENAMING FOUNDATION WORLD) NIL (CAR CDR) (ASSOC-EQ AND)
  (IF UNPROTECTED-EXPORT-P) NIL NIL)
 ((ABSSTOBJ-TUPLES NAME EXPORTS NAME-EXPORT-LOOKUP UPDATER FOUNDATION EXEC
   WORLD :LOGIC ,LOGIC :EXEC ,EXEC ,@(AND UPDATER `(:UPDATER ,UPDATER))
   :PROTECT ,PROTECT ABSSTOBJ-TUPLES)
  NIL (CDR) (CLONE-STOBJ-CHANGE-SYMBOL B*) NIL NIL NIL)
 ((NAME-EXPORT-LOOKUP NAME RENAMING
   (UPDATER-EXPORT-LOOKUP (ASSOC-EQ UPDATER EXPORTS)))
  NIL NIL NIL (IF) NIL NIL)
 ((UPDATER-EXPORT-LOOKUP) NIL (CDR) (CLONE-STOBJ-CHANGE-SYMBOL) NIL NIL NIL))
("/home/acl2/books/std/stobjs/clone.lisp::CLONE-ABSSTOBJ-FN"
 (NIL NIL NIL (B*) NIL NIL NIL) (NIL NIL (SB-INT:QUASIQUOTE) NIL NIL NIL NIL)
 (NIL NIL
  (STOBJ-INFO
   `(,FOUNDATION (,?!RECOG-NAME ,RECOG-LOGIC ,RECOG-EXEC)
     (,?!CREATOR-NAME ,CREATE-LOGIC ,CREATE-EXEC) . ,EXPORT-ABSSTOBJ-TUPLES)
   ?PRED ?CREATE ?EXPORTS EXPORTS CREATOR RECOGNIZER)
  NIL NIL NIL NIL)
 ((ABS-INFO ,NAME :FOUNDATION ,FOUNDATION :RECOGNIZER :CREATOR :EXPORTS
   ,(CLONE-ABSSTOBJ-EXPORTS EXPORT-ABSSTOBJ-TUPLES EXPORTS RENAMING FOUNDATION
     WORLD)
   :CONGRUENT-TO ,STOBJNAME)
  NIL NIL (AND) (ACCESS ACCESS ACCESS)
  (FGETPROP DEFSTOBJ-FNNAME DEFSTOBJ-FNNAME ,RECOGNIZER ,CREATOR) NIL)
 ((STOBJNAME NIL WORLD STOBJ-PROPERTY STOBJ-INFO :RECOGNIZER STOBJ-PROPERTY
   STOBJ-INFO :CREATOR STOBJ-PROPERTY STOBJ-INFO :NAMES USER-EXPORTS NAME
   :CREATOR :TOP NIL NAME :RECOGNIZER :TOP NIL :LOGIC ,RECOG-LOGIC :EXEC
   ,RECOG-EXEC :LOGIC ,CREATE-LOGIC :EXEC ,CREATE-EXEC)
  NIL (QUOTE) (PAIRLIS$) NIL NIL NIL)
 ((STOBJ USER-EXPORTS) NIL (STRIP-CARS) NIL NIL NIL NIL)
 ((EXPORT-ABSSTOBJ-TUPLES) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/stobjs/clone.lisp::CLONE-STOBJ-FN"
 (NIL NIL NIL NIL NIL NIL NIL)
 ((NAME PREFIX SUFFIX STRSUBST PKG EXPORTS WORLD) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
