("/home/acl2/books/data-structures/utilities.lisp::IMPORT-AS-MACROS-FN"
 (NIL NIL (PACKAGE-SYMBOL) NIL NIL NIL NIL) ((SYMBOLS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/data-structures/utilities.lisp::GET-OPTION-CHECK-MUTEX-MV"
 (NIL NIL (OPTIONS) NIL NIL NIL NIL) ((MUTEX-OPTIONS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/data-structures/utilities.lisp::GET-OPTION-CHECK-SYNTAX-MV"
 (NIL NIL NIL NIL (OPTION-LIST) NIL NIL)
 ((VALID-OPTIONS DUPLICATE-OPTIONS MUTEX-OPTIONS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/data-structures/utilities.lisp::GET-OPTION-AS-FLAG-MV"
 (NIL NIL (OPTION) NIL NIL NIL NIL) ((OPTION-LIST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/data-structures/utilities.lisp::GET-OPTION-MEMBER-MV"
 (NIL NIL NIL NIL NIL (OPTION) NIL)
 ((OPTION-LIST CHOICES DEFAULT-IF-MISSING DEFAULT-IF-UNSPECIFIED) NIL NIL NIL
  NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/data-structures/utilities.lisp::GET-OPTION-SUBSET-MV"
 (NIL NIL NIL NIL (OPTION) NIL NIL)
 ((OPTION-LIST THE-SET DEFAULT) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/data-structures/utilities.lisp::GET-OPTION-ARGUMENT-MV"
 (NIL NIL NIL NIL NIL (OPTION) NIL)
 ((OPTION-LIST KIND DEFAULT-IF-MISSING DEFAULT-IF-UNSPECIFIED) NIL NIL NIL NIL
  NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/data-structures/utilities.lisp::UNIQUE-SYMBOLS1"
 (NIL NIL NIL NIL NIL (N) NIL)
 ((SEED SYM-LIST COUNTER GEN-LIST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
