("/home/acl2/books/xdoc/fmt-to-str-orig.lisp::FMT-TO-STR-ORIG-AUX"
 (NIL NIL NIL (B*) NIL NIL NIL) (NIL NIL NIL (MV) NIL NIL NIL)
 ((STR STATE) NIL
  (SOFT-RIGHT-MARGIN PRINT-CASE PKG BASE-PKG-NAME (MV ER ?VAL STATE) STATE
   STATE STATE (MV CHANNEL STATE) (MV ?COL STATE) (MV ER1 STR STATE)
   (MV ER2 ?VAL STATE) STATE STATE STATE)
  ((WHEN ER) (WHEN ER1) (WHEN ER2)) NIL NIL NIL)
 (NIL NIL (CURRENT-PACKAGE SYMBOL-PACKAGE-NAME)
  (F-GET-GLOBAL F-GET-GLOBAL IN-PACKAGE-FN MV SET-FMT-HARD-RIGHT-MARGIN
                SET-FMT-SOFT-RIGHT-MARGIN SET-PRINT-CASE
                GET-OUTPUT-STREAM-STRING$ IN-PACKAGE-FN
                SET-FMT-HARD-RIGHT-MARGIN SET-FMT-SOFT-RIGHT-MARGIN
                SET-PRINT-CASE MV MV)
  (OPEN-OUTPUT-CHANNEL ER) (ER ER) NIL)
 ((STATE STATE STATE BASE-PKG BASE-PKG-NAME STATE HARD?
   "Error switching to package ~x0" BASE-PKG-NAME "" STATE STATE STATE
   :DOWNCASE STATE :STRING :CHARACTER STATE STRING ALIST CHANNEL STATE NIL
   CHANNEL STATE PKG STATE HARD-RIGHT-MARGIN STATE SOFT-RIGHT-MARGIN STATE
   PRINT-CASE STATE HARD? "Error with get-output-stream-string$?" "" STATE
   HARD? "Error switching back to package ~x0" PKG "" STATE)
  (68 62 0) (QUOTE QUOTE QUOTE QUOTE QUOTE) NIL NIL NIL NIL)
 ((FMT-SOFT-RIGHT-MARGIN PRINT-CASE ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
                         ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
                         ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/xdoc/fmt-to-str-orig.lisp::FMT-TO-STR-ORIG"
 (NIL NIL NIL NIL NIL (FMT-TO-STR-ORIG-AUX) NIL)
 (("~x0" BASE-PKG STATE) NIL (LIST) NIL NIL NIL NIL)
 (NIL NIL NIL (CONS) NIL NIL NIL) ((#\0 X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
