("/home/acl2/books/tools/match-tree.lisp::MATCH-TREE-BINDER-P"
 ((PAT) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/match-tree.lisp::MATCH-TREE-CHECK-BINDING"
 (NIL NIL (KW) NIL NIL NIL NIL) ((X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/match-tree.lisp::MATCH-TREE"
 (NIL NIL NIL (PAT) NIL NIL NIL) ((X ALIST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/match-tree.lisp::SUBST-TREE"
 (NIL NIL (PAT) NIL NIL NIL NIL) ((ALIST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/match-tree.lisp::MATCH-TREE-BINDERS"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (NIL NIL (((WHEN (ATOM PAT)) NIL)) (APPEND) NIL NIL NIL)
 (NIL NIL
  ((WHEN (MATCH-TREE-BINDER-P PAT)) ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 (NIL NIL (LIST CAR CDR) NIL NIL NIL NIL)
 ((PAT PAT) NIL (CADR) NIL NIL NIL NIL) ((PAT) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/match-tree.lisp::KEYS-SUBSET"
 (NIL NIL (KEYS) NIL NIL NIL NIL) ((ALIST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/match-tree.lisp::MATCH-TREE-!VARS"
 (NIL NIL (PAT) NIL NIL NIL NIL) ((ACC) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/match-tree.lisp::MATCH-TREE-INITIAL-ALIST-LST"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (CONS) NIL NIL NIL)
 ((VARS) NIL `ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL NIL NIL NIL NIL)
 (NIL NIL (CDR) (CONS) NIL NIL NIL)
 ((,(CAR VARS) VARS) NIL (QUOTE) NIL NIL NIL NIL)
 ((,(CAR VARS)) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/match-tree.lisp::PREFIX-?-VARS"
 ((VARS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/match-tree.lisp::TREEMATCH-FN"
 (NIL NIL NIL (LET*) NIL NIL NIL)
 (NIL NIL (SB-INT:QUASIQUOTE)
  ((ALLVARS (REMOVE-DUPLICATES-EQ (MATCH-TREE-BINDERS PAT)))) NIL NIL NIL)
 (NIL NIL (VARS! VARS?) (B*) NIL NIL NIL)
 (NIL NIL (REMOVE-DUPLICATES-EQ)
  (SET-DIFFERENCE-EQ
   ((MV _TREEMATCH-OK ?_TREEMATCH-ALIST)
    (MATCH-TREE ',PAT ,X ,(MATCH-TREE-INITIAL-ALIST-TERM VARS!)))
   CHECK-VARS-NOT-FREE)
  NIL NIL NIL)
 ((ALLVARS VARS! ,MATCH-BODY) NIL
  ((UNLESS _TREEMATCH-OK) (ASSOCS . ,(PREFIX-?-VARS VARS?)) _TREEMATCH-OK)
  (MATCH-TREE-!VARS) NIL NIL NIL)
 ((PAT NIL _TREEMATCH-ALIST _TREEMATCH-ALIST) NIL NIL (CHECK-VARS-NOT-FREE) NIL
  NIL NIL)
 ((,NOMATCH-BODY) NIL (_TREEMATCH-OK) NIL NIL NIL NIL))
("/home/acl2/books/tools/match-tree.lisp::MATCH-TREE-RESTRICTIONS"
 ((PAT) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/match-tree.lisp::REPLACE-EQUALITIES-THM-FNSYM"
 (NIL NIL (THMNAME) NIL NIL NIL NIL) ((W) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/match-tree.lisp::MATCH-TREE-RW-FNAME"
 (NIL NIL (PREFIX) NIL NIL NIL NIL) ((VAR) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/match-tree.lisp::MATCH-TREE-REWRITES-FNS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (CONS) NIL NIL NIL)
 ((VARS) NIL NIL NIL NIL
  (MATCH-TREE-REWRITES-VAR-FN ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL)
 ((VARS! PAT PREFIX VARS! PAT PREFIX) NIL (CAR CDR) NIL NIL NIL NIL)
 ((VARS VARS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/match-tree.lisp::MATCH-TREE-RW-MEASURE-THMS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (APPEND) NIL NIL NIL)
 ((VARS) NIL NIL NIL NIL
  (MATCH-TREE-RW-MEASURE-THM ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL)
 ((VARS! PAT PREFIX VARS! PAT PREFIX) NIL (CAR CDR) NIL NIL NIL NIL)
 ((VARS VARS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/match-tree.lisp::MATCH-TREE-BLOCK-SUBSTS-VAR-FN"
 (NIL NIL NIL (LET*) NIL NIL NIL)
 (NIL NIL ((FNNAME (MATCH-TREE-RW-FNAME PREFIX VAR)) SB-INT:QUASIQUOTE) NIL NIL
  NIL NIL)
 (NIL NIL
  (THMNAME
   (DEFTHM ,THMNAME
           (IMPLIES
            (MV-NTH 0
                    (MATCH-TREE ',PAT X
                     ,(MATCH-TREE-INITIAL-ALIST-TERM VARS!)))
            (EQUAL (,FNNAME X . ,VARS!) (,FNNAME X . ,VARS!)))
           :RULE-CLASSES NIL))
  NIL NIL NIL NIL)
 (NIL NIL (ADD-REPLACE-EQUALITIES-RULE) (INTERN-IN-PACKAGE-OF-SYMBOL) NIL NIL
  NIL)
 ((FNNAME ,THMNAME) NIL NIL NIL (CONCATENATE) NIL NIL)
 (("-BLOCK-EQUALITY-SUBST") NIL 'SYMBOL-NAME NIL NIL NIL NIL)
 ((STRING FNNAME) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/match-tree.lisp::MATCH-TREE-BLOCK-SUBSTS-FNS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (APPEND) NIL NIL NIL)
 ((VARS) NIL NIL NIL NIL
  (MATCH-TREE-BLOCK-SUBSTS-VAR-FN ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL)
 ((VARS! PAT PREFIX VARS! PAT PREFIX) NIL (CAR CDR) NIL NIL NIL NIL)
 ((VARS VARS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/match-tree.lisp::MATCH-TREE-REWRITES-RWS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (CONS) NIL NIL NIL)
 ((VARS) NIL NIL NIL NIL
  (MATCH-TREE-REWRITES-VAR-RW ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL)
 ((VARS! PAT PREFIX VARS! PAT PREFIX) NIL (CAR CDR) NIL NIL NIL NIL)
 ((VARS VARS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/match-tree.lisp::MATCH-TREE-RESTR-EVENTS"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (NIL NIL (((LIST KW VAR) RESTR)) (AND) NIL NIL NIL)
 (NIL NIL (FNNAME SB-INT:QUASIQUOTE) (MEMBER) NIL NIL NIL)
 ((KW
   (DEFTHM
    ,(INTERN-IN-PACKAGE-OF-SYMBOL
      (CONCATENATE 'STRING (SYMBOL-NAME FNNAME) "-TYPE") FNNAME)
    (IMPLIES
     (MV-NTH 0 (MATCH-TREE ',PAT X ,(MATCH-TREE-INITIAL-ALIST-TERM VARS!)))
     ,(CASE KW
        (:?S `(SYMBOLP (,FNNAME X . ,VARS!)))
        (:?V `(AND (SYMBOLP (,FNNAME X . ,VARS!)) (,FNNAME X . ,VARS!)))
        (:?F
         `(AND (SYMBOLP (,FNNAME X . ,VARS!))
               (NOT (EQUAL (,FNNAME X . ,VARS!) 'QUOTE))))
        (:?L `(NOT (EQUAL (,FNNAME X . ,VARS!) 'QUOTE)))))
    :HINTS (("Goal" :IN-THEORY (ENABLE ,FNNAME)))))
  NIL (QUOTE) (MATCH-TREE-RW-FNAME) NIL NIL NIL)
 ((PREFIX VAR) NIL NIL NIL (:?S) NIL NIL)
 ((:?V :?F :?L) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/tools/match-tree.lisp::MATCH-TREE-RESTRS-EVENTS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (APPEND) NIL NIL NIL)
 ((RESTRS) NIL NIL NIL NIL
  (MATCH-TREE-RESTR-EVENTS ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL)
 ((VARS! PAT PREFIX VARS! PAT PREFIX) NIL (CAR CDR) NIL NIL NIL NIL)
 ((RESTRS RESTRS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
