("/home/acl2/books/std/util/defretgen.lisp::FUNCTION-DEPS"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (((BODY (GETPROPC FN 'UNNORMALIZED-BODY NIL WRLD))) NIL (ALL-FNNAMES) NIL NIL
  NIL NIL)
 ((BODY) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defretgen.lisp::FUNCTION-DEPS-LST"
 (NIL NIL NIL NIL (IF) NIL NIL) ((ACC) NIL (ATOM) (B*) NIL NIL NIL)
 ((FNS (BODY (GETPROPC (CAR FNS) 'UNNORMALIZED-BODY NIL WRLD))) NIL NIL NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 ((WRLD) NIL (CDR) NIL (ALL-FNNAMES1) NIL NIL)
 ((FNS NIL BODY ACC) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defretgen.lisp::DRG-MAP-FUNCTION-DEPS"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (NIL NIL NIL (((WHEN (ATOM DEPS)) NIL) ADD-TO-SET-EQUAL) NIL NIL NIL)
 (NIL NIL (LOOK (UNLESS LOOK) CDR) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL)
 ((LOOK ELEM-MAP) NIL (CDR) (ASSOC-EQ ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL)
 ((ELEM-MAP ELEM-MAP DEPS) NIL (CAR CDR) NIL NIL NIL NIL)
 ((DEPS DEPS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defretgen.lisp::DRG-FUNCTION-DEPS"
 (NIL NIL NIL (DRG-MAP-FUNCTION-DEPS) NIL NIL NIL)
 ((ELEM-MAP) NIL NIL (FUNCTION-DEPS) NIL NIL NIL)
 ((WRLD) NIL (DEFGUTS->NAME-FN) NIL NIL NIL NIL)
 ((GUTS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defretgen.lisp::DRG-MUTREC-DEPS"
 (NIL NIL NIL (DRG-MAP-FUNCTION-DEPS) NIL NIL NIL)
 ((ELEM-MAP) NIL NIL NIL (FUNCTION-DEPS-LST) NIL NIL)
 ((WRLD NIL) NIL (DEFGUTSLIST->NAME-FNS) NIL NIL NIL NIL)
 (NIL NIL (DEFINES-GUTS->GUTSLIST) NIL NIL NIL NIL)
 ((GUTS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defretgen.lisp::DRG-FUNCTION-GUTS?"
 (NIL NIL (CDR) NIL NIL NIL NIL) (NIL NIL NIL (ASSOC-EQ) NIL NIL NIL)
 ((NAME) NIL (GET-DEFINE-GUTS-ALIST) NIL NIL NIL NIL)
 ((WRLD) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defretgen.lisp::DRG-MUTREC-GUTS?"
 (NIL NIL (CDR) NIL NIL NIL NIL) (NIL NIL NIL (ASSOC-EQ) NIL NIL NIL)
 ((NAME) NIL (GET-DEFINES-ALIST) NIL NIL NIL NIL)
 ((WRLD) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defretgen.lisp::DRG-FUNCTION-GUTS"
 (NIL NIL NIL (B*) NIL NIL NIL)
 ((GUTS) NIL ((GUTS (DRG-FUNCTION-GUTS? NAME WRLD))) NIL NIL NIL NIL)
 (NIL NIL ((UNLESS GUTS)) NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL (ER))
 ((HARD? "Error: function must be introduced with ~x0, but ~x1 is not" NAME)
  NIL 'QUOTE NIL NIL NIL NIL)
 ((DEFRETGEN DEFINE) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defretgen.lisp::DRG-MUTREC-GUTS"
 (NIL NIL NIL (B*) NIL NIL NIL)
 ((GUTS) NIL ((GUTS (DRG-MUTREC-GUTS? NAME WRLD))) NIL NIL NIL NIL)
 (NIL NIL ((UNLESS GUTS)) NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL (ER))
 ((HARD? "Error: mutrec must be introduced with ~x0, but ~x1 is not" NAME) NIL
  'QUOTE NIL NIL NIL NIL)
 ((DEFRETGEN DEFINES) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defretgen.lisp::DRG-FUNCTION->ELEM-MAP"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (NIL NIL (((WHEN (ATOM ELEMS)) NIL)) NIL NIL (CASE-MATCH) NIL)
 ((X) NIL (X (':FUNCTION NAME) (':MUTREC NAME) &) NIL NIL NIL NIL)
 (NIL NIL (CAR) (B* B*) NIL (ER) NIL)
 ((ELEMS (GUTS (DRG-FUNCTION-GUTS NAME WRLD)) HARD? "Bad element: ~x0" X) NIL
  ((GUTS (DRG-MUTREC-GUTS NAME WRLD)) QUOTE) (CONS APPEND) NIL NIL NIL)
 ((DEFRETGEN) NIL (GUTSLIST)
  (CONS ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL PAIRLIS$
        ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL)
 ((X WRLD WRLD) NIL
  (DEFGUTS->NAME-FN CDR DEFINES-GUTS->GUTSLIST DEFGUTSLIST->NAME-FNS CDR) NIL
  (MAKE-LIST) NIL NIL))
("/home/acl2/books/std/util/defretgen.lisp::DRG-DEPENDENCY-GRAPH-AUX"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (NIL NIL (((WHEN (ATOM ELEMS)) NIL)) NIL NIL (CASE-MATCH) NIL)
 ((X) NIL (X (':FUNCTION NAME) (':MUTREC NAME) &) NIL NIL NIL NIL)
 (NIL NIL (CAR) (B* B*) NIL (ER) NIL)
 ((ELEMS HARD? "Bad element: ~x0" X) NIL
  ((GUTS (DRG-FUNCTION-GUTS NAME WRLD)) (GUTS (DRG-MUTREC-GUTS NAME WRLD))
   QUOTE)
  (CONS CONS) NIL NIL NIL)
 ((DEFRETGEN) NIL (DEPS DEPS) (CONS CONS)
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL)
 ((X ELEM-MAP WRLD X ELEM-MAP WRLD) NIL (CDR CDR) (REMOVE-EQUAL REMOVE-EQUAL)
  (DRG-FUNCTION-DEPS DRG-MUTREC-DEPS) NIL NIL))
("/home/acl2/books/std/util/defretgen.lisp::DRG-DEPENDENCY-GRAPH"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (((ELEM-MAP (DRG-FUNCTION->ELEM-MAP ELEMS WRLD))) NIL NIL NIL
  (DRG-DEPENDENCY-GRAPH-AUX) NIL NIL)
 ((ELEMS ELEM-MAP WRLD) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defretgen.lisp::DRG-ADD-TO-EACH"
 (NIL NIL NIL NIL (IF) NIL NIL)
 ((ACC) NIL (ATOM) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL)
 ((KEYS NEW-VAL) NIL (CDR) (LET) NIL NIL NIL)
 ((KEYS (KEY (CAR KEYS))) NIL NIL NIL (HONS-ACONS) NIL NIL)
 ((KEY ACC) NIL NIL (CONS) NIL NIL NIL) ((NEW-VAL) NIL (CDR) NIL NIL NIL NIL)
 (NIL NIL NIL (HONS-GET) NIL NIL NIL))
("/home/acl2/books/std/util/defretgen.lisp::DRG-REVERSE-GRAPH"
 (NIL NIL NIL NIL (IF) NIL NIL)
 (NIL NIL (ATOM FAST-ALIST-FREE) (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL NIL)
 ((GRAPH) NIL (FAST-ALIST-CLEAN CDR) NIL (DRG-ADD-TO-EACH) NIL NIL)
 ((ACC GRAPH ACC) NIL (CDAR CAAR) NIL NIL NIL NIL)
 ((GRAPH GRAPH) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defretgen.lisp::DRG-DEPENDENCY-ORDER"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (NIL NIL ((DEPGRAPH (DRG-DEPENDENCY-GRAPH ELEMS WRLD))) NIL
  (DRG-TOPOSORT-AUX-LIST) NIL NIL)
 ((ELEMS REV-DEPGRAPH NIL) NIL (REV-DEPGRAPH) NIL NIL NIL NIL)
 (NIL NIL NIL (DRG-REVERSE-GRAPH) NIL NIL NIL)
 ((DEPGRAPH NIL) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defretgen.lisp::DRG-FNSETS-TABLE"
 (NIL NIL NIL (TABLE-ALIST) NIL NIL NIL) ((WRLD) NIL (QUOTE) NIL NIL NIL NIL)
 ((DRG-FNSETS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defretgen.lisp::DRG-FNSETNAME-EXPAND"
 (NIL NIL NIL (B*) NIL NIL NIL)
 (NIL NIL ((LOOK (ASSOC-EQ NAME (DRG-FNSETS-TABLE WRLD))) CDR) NIL NIL NIL NIL)
 ((LOOK) NIL ((UNLESS LOOK)) NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL (ER))
 ((HARD? "Error: fnset must be introduced with ~x0, but ~x1 is not" NAME) NIL
  'QUOTE NIL NIL NIL NIL)
 ((DEFRETGEN DEF-RETGEN-FNSET) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defretgen.lisp::DRG-FNSETNAME-P"
 (NIL NIL (CONSP) NIL NIL NIL NIL) (NIL NIL NIL (ASSOC-EQ) NIL NIL NIL)
 ((NAME) NIL (DRG-FNSETS-TABLE) NIL NIL NIL NIL)
 ((WRLD) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defretgen.lisp::DRG-FNSET-FULLY-EXPAND"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (LET) NIL NIL NIL)
 ((ELEMS (ELEM (CAR ELEMS))) NIL NIL NIL NIL NIL (CASE-MATCH))
 ((ELEM) NIL ((':FNSET NAME) (':FUNCTION NAME) (':MUTREC NAME) NAME) NIL NIL
  NIL NIL)
 (NIL NIL NIL (APPEND B* B* B*) NIL NIL NIL)
 (((?IGNORE (DRG-FUNCTION-GUTS NAME WRLD))
   (?IGNORE (DRG-MUTREC-GUTS NAME WRLD)))
  NIL NIL
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL DRG-FUNCTION->ELEM-MAP CONS CONS
   CONS)
  (((UNLESS (AND NAME (SYMBOLP NAME)))
    (ER HARD? 'DEFRETGEN "Bad elem: ~x0" NAME)))
  NIL NIL)
 ((WRLD WRLD) NIL
  (CDR CAR CAR (WHEN (DRG-FNSETNAME-P NAME WRLD))
       (WHEN (DRG-MUTREC-GUTS? NAME WRLD)) ?IGN SB-INT:QUASIQUOTE)
  (DRG-FNSETNAME-EXPAND ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL))
("/home/acl2/books/std/util/defretgen.lisp::DEFRETGEN-ENTRY-EVENTS"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((ELEM) NIL ((':FUNCTION NAME) (':MUTREC NAME)) NIL NIL NIL NIL)
 (NIL NIL NIL (B*) NIL (DMGEN-GENERATE-DEFRETS-FOR-FN) NIL)
 ((THMNAME DMGEN-RULES WRLD) NIL (SB-INT:QUASIQUOTE) (DRG-FUNCTION-GUTS)
  ((GUTS (DRG-MUTREC-GUTS NAME WRLD))) NIL NIL)
 ((NAME WRLD
   (DEFRET-MUTUAL ,THMNAME ,@DEFRETS :SKIP-OTHERS T :MUTUAL-RECURSION ,NAME
    ,@(KWD-ALIST-TO-KEYWORD-VALUE-LIST
       '(:HINTS :NO-INDUCTION-HINT :INSTRUCTIONS :OTF-FLG) KWD-ALIST)))
  NIL (GUTSLIST DEFRETS (WHEN (ATOM DEFRETS))) NIL NIL NIL NIL)
 ((NIL) NIL (DEFINES-GUTS->GUTSLIST) NIL NIL (DMGEN-GENERATE-DEFRETS) NIL)
 ((GUTS THMNAME DMGEN-RULES GUTSLIST WRLD) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defretgen.lisp::DEFRETGEN-ORDERED-EVENTS"
 (NIL NIL NIL NIL (IF) NIL NIL) ((NIL) NIL (ATOM) (APPEND) NIL NIL NIL)
 ((ORDER) NIL NIL NIL NIL NIL
  (DEFRETGEN-ENTRY-EVENTS ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL))
 ((THMNAME DMGEN-RULES KWD-ALIST WRLD THMNAME DMGEN-RULES KWD-ALIST WRLD) NIL
  (CAR CDR) NIL NIL NIL NIL)
 ((ORDER ORDER) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/defretgen.lisp::DEFRETGEN-FN"
 (NIL NIL NIL (B*) NIL NIL NIL) (NIL NIL NIL (CONS) NIL NIL NIL)
 (NIL NIL
  ((WHEN REST-ARGS) FNSET-LOOK (UNLESS FNSET-LOOK) FNSET FNSET FNSET-ELEMS
   ORDER DMGEN-RULES ERRMSG (WHEN ERRMSG) QUOTE)
  NIL NIL NIL (DEFRETGEN-ORDERED-EVENTS))
 ((PROGN ORDER NAME DMGEN-RULES KWD-ALIST WRLD) NIL (CDR DMGEN-CHECK-RULES)
  (ASSOC DRG-FNSET-FULLY-EXPAND DRG-DEPENDENCY-ORDER) (IF) (ER ER APPEND ER)
  NIL)
 ((HARD? "Extra junk: ~x0" REST-ARGS :FUNCTIONS KWD-ALIST HARD?
   "A ~x0 argument is required" :FUNCTIONS FNSET-LOOK FNSET FNSET WRLD
   FNSET-ELEMS WRLD DMGEN-RULES HARD? "Bad rule found: ~@0" ERRMSG)
  NIL
  (QUOTE QUOTE SYMBOLP LIST DMGEN-PROCESS-FORMAL-HYPS
   DMGEN-PROCESS-RETURN-CONCLS DMGEN-PROCESS-FUNCTION-KEYS CDR QUOTE)
  NIL NIL NIL NIL)
 ((DEFRETGEN DEFRETGEN FNSET FNSET DEFRETGEN) NIL (CDR CDR CDR) (ASSOC) NIL NIL
  NIL)
 ((:RULES KWD-ALIST) NIL NIL (ASSOC ASSOC ASSOC) NIL NIL NIL))
("/home/acl2/books/std/util/defretgen.lisp::DEF-RETGEN-FNSET-FN"
 (NIL NIL NIL (NAME) NIL NIL NIL) ((FNSET WRLD) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
