("/home/acl2/books/arithmetic-5/lib/basic-ops/expt.lisp::P-O-2-G-FN"
 (NIL NIL NIL (LET) NIL NIL NIL)
 (((X (POWER-OF-2-GENERALIZED C))) NIL NIL NIL (IF) NIL NIL)
 ((X NIL) NIL (LIST) NIL NIL NIL NIL) (NIL NIL NIL (CONS) NIL NIL NIL)
 (NIL NIL 'KWOTE NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/expt.lisp::MFC-POT-LST"
 (NIL NIL NIL NIL (ACCESS) NIL NIL)
 ((METAFUNCTION-CONTEXT MFC :SIMPLIFY-CLAUSE-POT-LST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/expt.lisp::MFC-PT"
 (NIL NIL NIL (LET) NIL NIL NIL)
 (((RCNST (ACCESS METAFUNCTION-CONTEXT MFC :RCNST))) NIL NIL NIL (ACCESS) NIL
  NIL)
 ((REWRITE-CONSTANT RCNST :PT) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/expt.lisp::BOUNDS-FOR-EXPT-LINEAR-FNS-1"
 (NIL NIL NIL (N) NIL NIL NIL) ((MFC STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/expt.lisp::BOUNDS-FOR-EXPT-LINEAR-FNS"
 (NIL NIL NIL (N) NIL NIL NIL) ((MFC STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/expt.lisp::EXPT-LINEAR-UPPER-<-FN"
 (NIL NIL NIL (N) NIL NIL NIL) ((MFC STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/expt.lisp::EXPT-LINEAR-UPPER-<=-FN"
 (NIL NIL NIL (N) NIL NIL NIL) ((MFC STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/expt.lisp::EXPT-LINEAR-LOWER-<-FN"
 (NIL NIL NIL (N) NIL NIL NIL) ((MFC STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/expt.lisp::EXPT-LINEAR-LOWER-<=-FN"
 (NIL NIL NIL (N) NIL NIL NIL) ((MFC STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
