("/home/acl2/books/arithmetic/binomial.lisp::CHOOSE"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL (0) NIL (/) NIL (AND) NIL)
 (NIL NIL (INTEGERP INTEGERP FACTORIAL) (<= <= *) NIL NIL NIL)
 ((K N K K N N) (0) (FACTORIAL FACTORIAL) NIL NIL NIL NIL)
 ((K) NIL NIL (-) NIL NIL NIL) ((N K) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic/binomial.lisp::CHOOSE-MK"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL (0) NIL (AND) (IF) NIL NIL)
 (NIL NIL (INTEGERP INTEGERP) (AND +) (IF) NIL NIL)
 ((K N) (1 0) NIL
  (< < ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
     ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL AND)
  NIL NIL NIL)
 ((K K N K) (0) (1- 1- 1-) (<= <=) NIL NIL NIL)
 ((K N N K K N) (0) NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic/binomial.lisp::BINOMIAL-EXPANSION"
 (NIL NIL NIL NIL (X) NIL NIL) ((Y K N) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic/binomial.lisp::BINOMIAL-EXPANSION-TIMES-X"
 (NIL NIL NIL NIL (X) NIL NIL) ((Y K N) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic/binomial.lisp::BINOMIAL-EXPANSION-TIMES-Y"
 (NIL NIL NIL NIL (X) NIL NIL) ((Y K N) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic/binomial.lisp::BINOMIAL-EXPANSION-TRIANGLE"
 (NIL NIL NIL NIL (X) NIL NIL) ((Y K N) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic/binomial.lisp::BINOMIAL-EXPANSION-PASCAL-TRIANGLE"
 (NIL NIL NIL NIL (X) NIL NIL) ((Y K N) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic/binomial.lisp::N-EXPT"
 (NIL NIL (X) NIL NIL NIL NIL) ((N) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
