("/home/acl2/books/misc/getprop.lisp::FAST-NO-DUPLICATESP1"
 (NIL NIL (LST) NIL NIL NIL NIL) ((PROPS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/getprop.lisp::FAST-NO-DUPLICATESP"
 ((LST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/getprop.lisp::ALL-MARKED-T"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ENDP PROPS) T) NIL NIL NIL NIL)
 ((T) NIL NIL NIL (AND) NIL NIL)
 (NIL NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (EQ EQ) NIL NIL NIL)
 ((T) NIL (CADR QUOTE CDDR CDR) NIL NIL NIL NIL)
 ((MARK PROPS) NIL (CAR CAR) NIL NIL NIL NIL)
 ((PROPS PROPS) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/getprop.lisp::TIMED-FND"
 (NIL NIL NIL (PPROGN) NIL NIL NIL) (NIL NIL NIL (LET) (SET-TIMER) NIL NIL)
 ((STATE (ANS (FAST-NO-DUPLICATESP LST))) NIL 'QUOTE NIL NIL NIL NIL)
 ((FAST-NO-DUPLICATESP-TIME) (0) (VALUE) (INCREMENT-TIMER)
  (PRINT-TIMER PRINC$ PRINC$ POP-TIMER) NIL NIL)
 ((STATE *STANDARD-CO* STATE " secs" *STANDARD-CO* STATE #\Newline
   *STANDARD-CO* STATE NIL STATE ANS)
  NIL (QUOTE QUOTE QUOTE) NIL NIL NIL NIL)
 ((FAST-NO-DUPLICATESP-TIME FAST-NO-DUPLICATESP-TIME FAST-NO-DUPLICATESP-TIME)
  NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/misc/getprop.lisp::MAKE-TEMP-SYMBOLS"
 (NIL NIL (N) NIL NIL NIL NIL) ((ACC) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
