("/home/acl2/books/arithmetic-5/lib/basic-ops/integerp.lisp::REDUCE-INTEGERP-+-FN-1"
 (NIL NIL NIL NIL (X) NIL NIL) ((INTP-FLAG MFC STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/integerp.lisp::REDUCE-INTEGERP-+-FN"
 (NIL NIL NIL NIL (X) NIL NIL) ((INTP-FLAG MFC STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/integerp.lisp::REDUCE-RATIONALP-*-FN-1"
 (NIL NIL NIL (X) NIL NIL NIL) ((MFC STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-5/lib/basic-ops/integerp.lisp::REDUCE-RATIONALP-*-FN"
 (NIL NIL NIL (X) NIL NIL NIL) ((MFC STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
