("/home/acl2/books/std/util/tests/bstar.lisp::RETURN-TWO-VALUES"
 (NIL NIL NIL (MV) NIL NIL NIL) ((A B) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/tests/bstar.lisp::TRANSL-EQUAL-TESTS-FN"
 (NIL NIL NIL NIL (IF) NIL NIL)
 (NIL NIL (ATOM . `SB-INT:QUASIQUOTE) NIL NIL NIL NIL)
 ((TESTS) NIL NIL (MV) (MV-LET) NIL NIL)
 ((NIL STATE) NIL NIL (ERR TRANSL-EQUAL) (IF) NIL NIL)
 ((VAL STATE ,(TRANSL-EQUAL-TESTS-FN (CDR TESTS))) NIL 'QUOTE (OR MV) NIL NIL
  NIL)
 ((,(CAAR TESTS) ,(CADAR TESTS) ERR STATE) NIL (NOT QUOTE) NIL NIL NIL NIL)
 ((VAL ,(CAR TESTS)) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/tests/bstar.lisp::PATBIND-TESTS-FN"
 (NIL NIL (TESTS) NIL NIL NIL NIL) ((STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/std/util/tests/bstar.lisp::LOCALSTOBJTEST"
 (NIL NIL NIL (A) NIL NIL NIL) ((B C) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
