("/home/acl2/books/system/pseudo-good-worldp.lisp::SAFE-ACCESS-EVENT-TUPLE-NUMBER"
 (NIL NIL NIL (LET) NIL NIL NIL)
 (((X (SAFE-REMOVE-LOCAL X))) NIL NIL NIL (IF) NIL NIL)
 (NIL (-2) (CONSP) NIL (IF) NIL NIL) ((X) NIL (INTEGERP CAR) NIL (IF) NIL NIL)
 ((X) (-2) (CAR CONSP) NIL (IF) NIL NIL)
 ((X) (-2) (CAR INTEGERP CAAR) NIL NIL NIL NIL)
 ((X X) NIL (CAAR) NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-EVENT-INDEXP"
 (NIL NIL (X) NIL NIL NIL NIL) ((W) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::SAFE-ACCESS-COMMAND-TUPLE-NUMBER"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL (-2) (CONSP) NIL (IF) NIL NIL)
 ((X) (-2) (INTEGERP CAR) NIL NIL NIL NIL) ((X) NIL (CAR) NIL NIL NIL NIL)
 ((X) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-COMMAND-INDEXP"
 (NIL NIL (X) NIL NIL NIL NIL) ((W) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-RUNEP"
 (NIL NIL NIL NIL NIL NIL (AND))
 (NIL NIL (CONSP KEYWORDP CONSP SYMBOLP) (OR) NIL NIL NIL)
 ((RUNE) NIL (CAR CDR CADR NULL NATP) NIL NIL NIL NIL)
 ((RUNE RUNE RUNE) NIL (CDDR CDDR) NIL NIL NIL NIL)
 ((RUNE RUNE) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-FUNCTION-SYMBOLP"
 (NIL NIL (FN) NIL NIL NIL NIL) ((N) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-FUNCTION-SYMBOL-LISTP"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL (ATOM NULL) (AND) NIL NIL NIL)
 ((LST LST) NIL NIL
  (PSEUDO-FUNCTION-SYMBOLP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL)
 ((N N) NIL (CAR CDR) NIL NIL NIL NIL) ((LST LST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-WELL-FOUNDED-RELATION-ALISTP"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL ((ATOM VAL) (AND (CONSP (CAR VAL)) (CONSP (CDR (CAR VAL)))) T) NIL
  NIL NIL NIL)
 ((NIL) NIL (NULL) (LET) NIL NIL NIL)
 ((VAL) NIL NIL ((REL (CAR (CAR VAL)))) NIL (AND) NIL)
 (NIL NIL (M RUNE PSEUDO-RUNEP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  (PSEUDO-FUNCTION-SYMBOLP PSEUDO-FUNCTION-SYMBOLP) NIL NIL NIL)
 ((REL M RUNE) (2 1) (CADR CDDR CDR) NIL NIL NIL NIL)
 ((VAL) NIL (CAR CAR) NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-NUMEP"
 (NIL NIL (NATP) NIL NIL NIL NIL) ((N) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-BUILT-IN-CLAUSE-RECORDP"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((X) NIL (((NUME . ALL-FNNAMES) CLAUSE . RUNE) &) NIL NIL NIL NIL)
 ((NIL) NIL NIL NIL NIL (AND) NIL)
 (NIL NIL (PSEUDO-TERM-LISTP PSEUDO-RUNEP) (OR PSEUDO-FUNCTION-SYMBOL-LISTP)
  NIL NIL NIL)
 ((ALL-FNNAMES NIL CLAUSE RUNE) NIL (NULL PSEUDO-NUMEP) NIL NIL NIL NIL)
 ((NUME NUME) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-BUILT-IN-CLAUSE-RECORD-LISTP"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL (ATOM NULL) (AND) NIL NIL NIL)
 ((X X) NIL
  (PSEUDO-BUILT-IN-CLAUSE-RECORDP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-BUILT-IN-CLAUSESP"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL (ATOM NULL) NIL NIL (AND) NIL)
 ((X X) NIL
  (CONSP PSEUDO-BUILT-IN-CLAUSE-RECORD-LISTP
         ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  (PSEUDO-FUNCTION-SYMBOLP) NIL NIL NIL)
 ((NIL) NIL (CAR CAR CDR CDR) NIL NIL NIL NIL)
 ((X X) NIL (CAR CAR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-ATTACH-NIL-LST"
 (NIL NIL NIL (PSEUDO-FUNCTION-SYMBOL-LISTP) NIL NIL NIL)
 ((LST NIL) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::ATTACHMENT-COMPONENTS-PATHP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM PATH) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) (AND) NIL NIL NIL)
 ((PATH) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  (PSEUDO-FUNCTION-SYMBOLP) NIL NIL NIL)
 ((NIL) NIL (CAR CDR) NIL NIL NIL NIL) ((PATH PATH) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::ATTACHMENT-COMPONENT-P"
 (NIL NIL NIL (CASE-MATCH) NIL NIL NIL)
 ((C) NIL (('ATTACHMENT-COMPONENT (EXT-ANC . ORD-ANC) . PATH)) NIL NIL NIL NIL)
 (NIL NIL NIL NIL (AND) NIL NIL)
 (NIL NIL (ATTACHMENT-COMPONENTS-PATHP)
  (PSEUDO-FUNCTION-SYMBOL-LISTP PSEUDO-FUNCTION-SYMBOL-LISTP) NIL NIL NIL)
 ((EXT-ANC NIL ORD-ANC NIL PATH) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::ATTACHMENT-COMPONENTS-P"
 (NIL NIL NIL (COND) NIL NIL NIL)
 (NIL NIL ((ATOM COMPONENTS) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) (AND) NIL NIL NIL)
 ((COMPONENTS) NIL
  (ATTACHMENT-COMPONENT-P ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL
  NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL)
 ((COMPONENTS COMPONENTS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-ATTACHMENT-RECORDP"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((X) NIL (('ATTACHMENT (G . EXT-SUCC) COMPONENTS . PAIRS) &) NIL NIL NIL NIL)
 ((NIL) NIL NIL NIL NIL NIL (AND))
 (NIL NIL (ATTACHMENT-COMPONENTS-P SYMBOL-ALISTP R-SYMBOL-ALISTP)
  (PSEUDO-FUNCTION-SYMBOL-LISTP PSEUDO-FUNCTION-SYMBOLP) NIL NIL NIL)
 ((EXT-SUCC NIL G NIL COMPONENTS PAIRS PAIRS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-ATTACHMENT-RECORDSP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM X) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) (AND) NIL NIL NIL)
 ((X) NIL (PSEUDO-ATTACHMENT-RECORDP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-ATTACHMENTS-AT-GROUND-ZEROP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM X) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) NIL NIL (AND) NIL)
 ((X) NIL (CONSP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  (PSEUDO-FUNCTION-SYMBOLP PSEUDO-FUNCTION-SYMBOLP) NIL NIL NIL)
 ((NIL NIL) NIL (CAR CAAR CDAR CDR) NIL NIL NIL NIL)
 ((X X X X) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-HALF-LENGTH-BUILT-IN-CLAUSESP"
 (NIL NIL (NATP) NIL NIL NIL NIL) ((N) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::TYPE-SETP"
 (NIL NIL NIL NIL (AND) NIL NIL) (NIL NIL (INTEGERP) (<= <=) NIL NIL NIL)
 ((N *MIN-TYPE-SET* N N *MAX-TYPE-SET*) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-TYPE-SET-INVERTER-RULE-RECORDP"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((X) NIL (('TYPE-SET-INVERTER-RULE (NUME . TS) TERMS . RUNE) &) NIL NIL NIL
  NIL)
 ((NIL) NIL NIL NIL NIL (AND) NIL)
 (NIL NIL (TYPE-SETP PSEUDO-TERM-LISTP PSEUDO-RUNEP) (OR) NIL NIL NIL)
 ((TS TERMS RUNE) NIL (NULL PSEUDO-NUMEP) NIL NIL NIL NIL)
 ((NUME NUME) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-TYPE-SET-INVERTER-RULESP"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL (ATOM NULL) (AND) NIL NIL NIL)
 ((VAL VAL) NIL
  (PSEUDO-TYPE-SET-INVERTER-RULE-RECORDP
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((VAL VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-RUNE-ARRAY1P"
 ((A) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-ENABLED-STRUCTURE-RECORDP"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((VAL) NIL
  (((INDEX-OF-LAST-ENABLING . THEORY-ARRAY) (ARRAY-NAME . ARRAY-LENGTH)
    ARRAY-NAME-ROOT . ARRAY-NAME-SUFFIX)
   &)
  NIL NIL NIL NIL)
 ((NIL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL (INTEGERP SYMBOLP PSEUDO-RUNE-ARRAY1P NATP CHARACTER-LISTP NATP)
  (<= ARRAY1P) NIL NIL NIL)
 ((INDEX-OF-LAST-ENABLING INDEX-OF-LAST-ENABLING ARRAY-NAME ARRAY-NAME
   THEORY-ARRAY THEORY-ARRAY ARRAY-LENGTH ARRAY-NAME-ROOT ARRAY-NAME-SUFFIX)
  (-1) NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-GLOBAL-ARITHMETIC-ENABLED-STRUCTUREP"
 (NIL NIL (PSEUDO-ENABLED-STRUCTURE-RECORDP) NIL NIL NIL NIL)
 ((VAL) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::OPERATING-SYSTEMP"
 (NIL NIL NIL (MEMBER-EQ) NIL NIL NIL) ((VAL) NIL (QUOTE) NIL NIL NIL NIL)
 (NIL NIL NIL (:UNIX) NIL NIL NIL)
 ((:APPLE :MSWINDOWS) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::EVENT-NUMBER-BASELINEP"
 (NIL NIL (NATP) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::COMMAND-NUMBER-BASELINE-INFOP"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((VAL) NIL (('COMMAND-NUMBER-BASELINE-INFO CURRENT PERMAMENT-P . ORIGINAL) &)
  NIL NIL NIL NIL)
 ((NIL) NIL NIL NIL (AND) NIL NIL)
 (NIL NIL (NATP BOOLEANP NATP) NIL NIL NIL NIL)
 ((CURRENT PERMAMENT-P ORIGINAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-ARGLISTP"
 (NIL NIL (SYMBOL-LISTP) NIL NIL NIL NIL) ((X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-INTERNAL-SIGNATUREP"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((INSIG) NIL ((FN FORMALS STOBJS-IN STOBJS-OUT) &) NIL NIL NIL NIL)
 ((NIL) NIL NIL NIL NIL NIL (AND))
 (NIL NIL (PSEUDO-ARGLISTP SYMBOL-LISTP SYMBOL-LISTP)
  (PSEUDO-FUNCTION-SYMBOLP EQUAL) NIL NIL NIL)
 ((FN NIL FORMALS STOBJS-IN STOBJS-OUT) NIL (LEN LEN) NIL NIL NIL NIL)
 ((FORMALS STOBJS-IN) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-INTERNAL-SIGNATURE-LISTP"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL (ATOM NULL) (AND) NIL NIL NIL)
 ((X X) NIL
  (PSEUDO-INTERNAL-SIGNATUREP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-EMBEDDED-EVENT-LST-ENTRYP"
 (NIL NIL NIL NIL (AND) NIL NIL) (NIL NIL (CONSP) NIL (IF IF) NIL NIL)
 ((EE-ENTRY T T) NIL NIL (EQ AND EQ AND) NIL NIL NIL)
 (NIL NIL
  (CAR QUOTE CONSP PSEUDO-INTERNAL-SIGNATURE-LISTP CAR QUOTE CONSP BOOK-NAME-P)
  NIL NIL NIL NIL)
 ((EE-ENTRY ENCAPSULATE EE-ENTRY INCLUDE-BOOK) NIL (CDR CADR CDR CADR) NIL NIL
  NIL NIL)
 ((EE-ENTRY EE-ENTRY EE-ENTRY EE-ENTRY) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-EMBEDDED-EVENT-LSTP"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL (ATOM NULL) (AND) NIL NIL NIL)
 ((VAL VAL) NIL
  (PSEUDO-EMBEDDED-EVENT-LST-ENTRYP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((VAL VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-CLTL-COMMANDP"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((VAL) NIL (('DEFUNS DEFUN-MODE IGNOREP . DEFS) &) NIL NIL NIL NIL)
 ((T) NIL NIL NIL (AND) NIL NIL) (NIL NIL (TRUE-LISTP) NIL (OR OR) NIL NIL)
 ((DEFS) NIL (NULL NULL) (EQ EQ EQ) (AND) NIL NIL)
 ((DEFUN-MODE DEFUN-MODE :PROGRAM DEFUN-MODE :LOGIC IGNOREP IGNOREP) NIL 'CONSP
  (EQ PSEUDO-FUNCTION-SYMBOLP) NIL NIL NIL)
 ((RECLASSIFYING IGNOREP NIL) NIL (CAR QUOTE CDR) NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-CLTL-COMMAND-LISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM VAL) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) (AND) NIL NIL NIL)
 ((VAL) NIL (PSEUDO-CLTL-COMMANDP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((VAL VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-INCLUDE-BOOK-ALIST-ENTRYP"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((ENTRY) NIL
  ((FULL-NAME USER-NAME FAMILIAR-NAME CERT-ANNOTATIONS . CHK-SUM) &) NIL NIL
  NIL NIL)
 ((NIL) NIL NIL NIL NIL NIL (AND))
 (NIL NIL (BOOK-NAME-P STRINGP STRINGP) (OR) (CASE-MATCH) NIL NIL)
 ((FULL-NAME USER-NAME FAMILIAR-NAME CHK-SUM) NIL
  (NULL CERT-ANNOTATIONSP
        ((':BOOK-LENGTH . BOOK-LENGTH) (':BOOK-WRITE-DATE . BOOK-WRITE-DATE))
        &)
  NIL NIL NIL NIL)
 ((CERT-ANNOTATIONS CERT-ANNOTATIONS) NIL NIL (AND OR) NIL NIL NIL)
 (NIL NIL (NATP NATP INTEGERP) (EQ) NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-INCLUDE-BOOK-ALIST-ENTRY-LISTP"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL
  ((ATOM X)
   (AND LOCAL-MARKERS-ALLOWEDP (CONSP (CAR X)) (EQ (CAR (CAR X)) 'LOCAL)
        (CONSP (CDR (CAR X))) (EQUAL (CDDR (CAR X)) NIL))
   T)
  NIL NIL NIL NIL)
 (NIL NIL NIL (EQUAL AND AND) NIL NIL NIL)
 ((X NIL) NIL
  (PSEUDO-INCLUDE-BOOK-ALIST-ENTRYP PSEUDO-INCLUDE-BOOK-ALIST-ENTRYP)
  (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL)
 ((LOCAL-MARKERS-ALLOWEDP LOCAL-MARKERS-ALLOWEDP) NIL (CADR CDR CAR CDR) NIL
  NIL NIL NIL)
 ((X X X) NIL (CAR) NIL NIL NIL NIL) ((X) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-INCLUDE-BOOK-ALISTP"
 (NIL NIL NIL (PSEUDO-INCLUDE-BOOK-ALIST-ENTRY-LISTP) NIL NIL NIL)
 ((VAL T) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-INCLUDE-BOOK-ALIST-ALLP"
 (NIL NIL (PSEUDO-INCLUDE-BOOK-ALISTP) NIL NIL NIL NIL)
 ((VAL) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-PCERT-BOOKSP"
 (NIL NIL (BOOK-NAME-LISTP) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-INCLUDE-BOOK-PATHP"
 (NIL NIL (BOOK-NAME-LISTP) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::CERTIFICATION-TUPLEP"
 (NIL NIL NIL (OR) NIL NIL NIL)
 (NIL NIL (NULL PSEUDO-INCLUDE-BOOK-ALIST-ENTRYP) NIL NIL NIL NIL)
 ((VAL VAL) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-FUNCTIONAL-SUBSTITUTION-PAIRP"
 (NIL NIL NIL NIL NIL (CASE-MATCH) NIL)
 ((X) NIL ((FN 'LAMBDA VARS BODY) (FN . FN1) &) NIL NIL NIL NIL)
 ((NIL) NIL NIL (AND) (AND) NIL NIL)
 (NIL NIL (PSEUDO-ARGLISTP PSEUDO-TERMP)
  (PSEUDO-FUNCTION-SYMBOLP PSEUDO-FUNCTION-SYMBOLP PSEUDO-FUNCTION-SYMBOLP) NIL
  NIL NIL)
 ((FN NIL VARS BODY FN NIL FN1 NIL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-FUNCTIONAL-SUBSTITUTIONP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM X) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) (AND) NIL NIL NIL)
 ((X) NIL
  (PSEUDO-FUNCTIONAL-SUBSTITUTION-PAIRP
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PROVED-FUNCTIONAL-INSTANCES-ALIST-ENTRYP"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((X) NIL ((NAME FN-SUBST . ON-BEHALF) &) NIL NIL NIL NIL)
 ((NIL) NIL NIL NIL (AND) NIL NIL)
 (NIL NIL (SYMBOLP PSEUDO-FUNCTIONAL-SUBSTITUTIONP) (OR) NIL NIL NIL)
 ((NAME FN-SUBST) NIL (SYMBOLP) (EQUAL) NIL NIL NIL)
 ((ON-BEHALF ON-BEHALF) (0) NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PROVED-FUNCTIONAL-INSTANCES-ALISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM VAL) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) (AND) NIL NIL NIL)
 ((VAL) NIL
  (PROVED-FUNCTIONAL-INSTANCES-ALIST-ENTRYP
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((VAL VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::NONCONSTRUCTIVE-AXIOM-NAMESP"
 (NIL NIL (SYMBOL-LISTP) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-THEORYP1"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM LST) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) (AND) NIL NIL NIL)
 ((LST) NIL (PSEUDO-RUNEP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL
  NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((LST LST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-STANDARD-THEORIESP"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((VAL) NIL ((R-UNV R-FN1 R-FN2 R-FN3) &) NIL NIL NIL NIL)
 ((NIL) NIL NIL NIL NIL (AND) NIL)
 (NIL NIL (PSEUDO-THEORYP1 PSEUDO-THEORYP1 PSEUDO-THEORYP1 PSEUDO-THEORYP1) NIL
  NIL NIL NIL)
 ((R-UNV R-FN1 R-FN2 R-FN3) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-CURRENT-THEORYP"
 (NIL NIL (PSEUDO-THEORYP1) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-AUGMENTED-THEORYP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM LST) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) NIL NIL (AND) NIL)
 ((LST) NIL
  (CONSP PSEUDO-NUMEP PSEUDO-RUNEP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 (NIL NIL (CAR CAR CDR CDR) NIL NIL NIL NIL)
 ((LST LST) NIL (CAR CAR) NIL NIL NIL NIL) ((LST LST) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-CURRENT-THEORY-AUGMENTEDP"
 (NIL NIL (PSEUDO-AUGMENTED-THEORYP) NIL NIL NIL NIL)
 ((VAL) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-CURRENT-THEORY-INDEXP"
 (NIL NIL NIL (OR) NIL NIL NIL) (NIL NIL (PSEUDO-NUMEP) (EQUAL) NIL NIL NIL)
 ((VAL VAL) (-1) NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-GENERALIZE-RULEP"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((X) NIL (('GENERALIZE-RULE NUME FORMULA . RUNE) &) NIL NIL NIL NIL)
 ((NIL) NIL NIL NIL (AND) NIL NIL)
 (NIL NIL (PSEUDO-NUMEP PSEUDO-TERMP PSEUDO-RUNEP) NIL NIL NIL NIL)
 ((NUME FORMULA RUNE) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-GENERALIZE-RULESP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM VAL) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) (AND) NIL NIL NIL)
 ((VAL) NIL (PSEUDO-GENERALIZE-RULEP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((VAL VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-CLAUSE-PROCESSOR-RULESP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM VAL) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) NIL NIL (AND) NIL)
 ((VAL) NIL
  (CONSP SYMBOLP PSEUDO-TERMP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL NIL)
 (NIL NIL (CAR CAR CDR CDR) NIL NIL NIL NIL)
 ((VAL VAL) NIL (CAR CAR) NIL NIL NIL NIL) ((VAL VAL) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::BOOT-STRAP-FLGP"
 (NIL NIL (BOOLEANP) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::BOOT-STRAP-PASS-2P"
 (NIL NIL (BOOLEANP) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::SKIP-PROOFS-SEENP"
 (NIL NIL NIL NIL (OR) NIL NIL)
 (NIL NIL (NULL PSEUDO-EVENT-FORMP) NIL NIL (AND) NIL)
 ((VAL VAL) NIL (TRUE-LISTP BOOK-NAME-P) (EQUAL EQ) NIL NIL NIL)
 ((VAL :INCLUDE-BOOK) (2) (LEN CAR CADR) NIL NIL NIL NIL)
 ((VAL VAL VAL) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::REDEF-SEENP"
 (NIL NIL NIL NIL (OR) NIL NIL)
 (NIL NIL (NULL PSEUDO-EVENT-FORMP) NIL NIL (AND) NIL)
 ((VAL VAL) NIL (TRUE-LISTP STRINGP) (EQUAL EQ) NIL NIL NIL)
 ((VAL :INCLUDE-BOOK) (2) (LEN CAR CADR) NIL NIL NIL NIL)
 ((VAL VAL VAL) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::CERT-REPLAYP"
 (NIL NIL NIL NIL (OR) NIL NIL) (NIL NIL (NULL) (EQ) (AND) NIL NIL)
 ((VAL VAL T) NIL (CONSP TRUE-LISTP POSP) NIL NIL NIL NIL)
 ((VAL) NIL (CDR CAR) NIL NIL NIL NIL) ((VAL VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PROOF-SUPPORTERS-ALISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM VAL) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) NIL NIL NIL (AND))
 ((VAL) NIL (CONSP CDAR SYMBOL-LISTP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  (OR) NIL NIL NIL)
 ((VAL) NIL (CAR SYMBOLP SYMBOL-LISTP CDAR CDR) NIL NIL NIL NIL)
 ((VAL VAL VAL) NIL (CAAR CAAR) NIL NIL NIL NIL)
 ((VAL VAL) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-FREE-VAR-RUNES-ALLP"
 (NIL NIL (PSEUDO-THEORYP1) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-FREE-VAR-RUNES-ONCEP"
 (NIL NIL (PSEUDO-THEORYP1) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::WEAK-TRANSLATE-CERT-DATA-RECORD-LISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM LST) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) (AND) NIL NIL NIL)
 ((LST) NIL
  (WEAK-TRANSLATE-CERT-DATA-RECORD-P ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((LST LST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-TRANSLATE-CERT-DATAP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM VAL) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) NIL NIL (AND) NIL)
 ((VAL) NIL
  (CONSP SYMBOLP WEAK-TRANSLATE-CERT-DATA-RECORD-LISTP
         ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 (NIL NIL (CAR CAAR CDAR CDR) NIL NIL NIL NIL)
 ((VAL VAL VAL VAL) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::CHK-NEW-NAME-LSTP"
 (NIL NIL (SYMBOL-LISTP) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-TAU-PAIRP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-TAU-PAIRP-LISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM LST) T) NIL NIL NIL NIL)
 (NIL NIL NIL (EQUAL) (AND) NIL NIL)
 ((LST NIL) NIL (CONSP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  (PSEUDO-TAU-PAIRP) NIL NIL NIL)
 ((NIL) NIL (CAR CAR CDR) NIL NIL NIL NIL)
 ((LST LST LST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::INDEXED-PAIRS-ORDERED-STRICTLY-DESCENDINGP"
 ((LST) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-TAU-PAIRSP"
 (NIL NIL NIL (AND) NIL NIL NIL)
 (NIL NIL (PSEUDO-TAU-PAIRP-LISTP INDEXED-PAIRS-ORDERED-STRICTLY-DESCENDINGP)
  NIL NIL NIL NIL)
 ((X X) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-EVG-SINGLETONP"
 (NIL NIL NIL (AND) NIL NIL NIL) (NIL NIL (CONSP NULL) NIL NIL NIL NIL)
 ((X) NIL (CDR) NIL NIL NIL NIL) ((X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-EVG-SINGLETONSP1"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM LST) T) NIL NIL NIL NIL)
 (NIL NIL NIL (EQUAL AND) NIL NIL NIL)
 ((LST NIL) NIL
  (PSEUDO-EVG-SINGLETONP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL
  NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((LST LST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::LEXORDER-STRICT-ASCENDINGP-WITHOUT-LIST-NIL"
 (NIL NIL NIL NIL NIL (COND) NIL)
 (NIL NIL ((ATOM LST) (ATOM (CDR LST)) (LEXORDER (CADR LST) (CAR LST)) T) NIL
  NIL NIL NIL)
 ((T T NIL) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL NIL)
 (NIL NIL (CDR) NIL NIL NIL NIL) ((LST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-EVG-SINGLETONSP"
 (NIL NIL NIL (AND) NIL NIL NIL)
 (NIL NIL (PSEUDO-EVG-SINGLETONSP1 LEXORDER-STRICT-ASCENDINGP-WITHOUT-LIST-NIL)
  NIL NIL NIL NIL)
 ((LST) NIL NIL NIL (IF) NIL NIL) ((LST) NIL (CDR) (EQUAL) NIL NIL NIL)
 ((LST) NIL (CAR QUOTE) NIL NIL NIL NIL) ((LST NIL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-TAU-INTERVALP"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL
  ((EQ X NIL)
   (AND (CONSP X) (CONSP (CDR X)) (CONSP (CAR (CDR X))) (CONSP (CDR (CDR X))))
   T)
  NIL NIL NIL NIL)
 ((T NIL) NIL NIL (LET) NIL NIL NIL)
 (NIL NIL NIL (AND) NIL ((DOM (CAR X))) NIL)
 (NIL NIL (LO-REL LO HI-REL HI) NIL (IF) (OR) NIL)
 (NIL NIL (CAR CDR CAR CDR NULL) (EQ EQ EQ EQ) NIL (AND AND) NIL)
 ((DOM DOM DOM DOM DOM) NIL
  (CADR CADR CDDR CDDR QUOTE QUOTE QUOTE QUOTE NULL NULL BOOLEANP BOOLEANP)
  (OR OR OR OR) NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-TAUP"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL ((ATOM X) (ATOM (CAR X)) T) NIL NIL NIL NIL)
 (NIL NIL NIL (EQUAL AND AND) NIL NIL NIL)
 ((X NIL) NIL NIL (EQUAL AND) (IF IF) NIL NIL)
 ((NIL) NIL (CAR CONSP PSEUDO-EVG-SINGLETONSP CONSP) (AND EQUAL OR AND EQUAL)
  NIL NIL NIL)
 ((X NIL NIL) NIL
  (CDR PSEUDO-TAU-INTERVALP CDR NULL PSEUDO-EVG-SINGLETONP CDR CDR
       PSEUDO-TAU-INTERVALP CDR)
  (COND COND) NIL NIL NIL)
 ((X X X X) NIL (CADR (ATOM (CDDR X)) T CAR CAR CAR CADR (ATOM (CDDR X)) T) NIL
  NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-TAUP-LISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM X) T) NIL NIL NIL NIL)
 (NIL NIL NIL (EQUAL AND) NIL NIL NIL)
 ((X NIL) NIL (PSEUDO-TAUP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-TAU-CONJUNCTIVE-RULESP"
 (NIL NIL (PSEUDO-TAUP-LISTP) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-RUNEP-LISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM VAL) T) NIL NIL NIL NIL)
 (NIL NIL NIL (EQUAL AND) NIL NIL NIL)
 ((VAL NIL) NIL (PSEUDO-RUNEP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((VAL VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::TTAGS-SEENP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM VAL) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) NIL NIL NIL (AND))
 ((VAL) NIL
  (CONSP SYMBOLP TRUE-LISTP BOOK-NAME-LISTP
         ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 (NIL NIL (CAR CAR CDR CDR) (REMOVE1-EQ) NIL NIL NIL)
 ((VAL VAL) NIL (CAR CAR QUOTE CDR) NIL NIL NIL NIL)
 ((VAL VAL NIL) NIL (CAR) NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::WELL-FORMEDNESS-GUARANTEEP"
 (NIL NIL NIL NIL NIL (AND) NIL)
 (NIL NIL (CONSP SYMBOL-LISTP ARITY-ALISTP) (OR) NIL NIL NIL)
 ((X) NIL (CAR CDR) (EQUAL EQUAL) NIL NIL NIL)
 ((X X) (3 5) (LEN LEN) NIL NIL NIL NIL) (NIL NIL (CAR CAR) NIL NIL NIL NIL)
 ((X X) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::WELL-FORMEDNESS-GUARANTEE-LISTP"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL (ATOM) (EQ AND) NIL NIL NIL)
 ((LST LST NIL) NIL
  (WELL-FORMEDNESS-GUARANTEEP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((LST LST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::NEVER-UNTOUCHABLE-FNSP"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL (ATOM) (EQ) NIL (AND) NIL)
 ((VAL VAL NIL) NIL
  (CONSP SYMBOLP WELL-FORMEDNESS-GUARANTEE-LISTP
         ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 (NIL NIL (CAR CAR CDR CDR) NIL NIL NIL NIL)
 ((VAL VAL) NIL (CAR CAR) NIL NIL NIL NIL) ((VAL VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::UNTOUCHABLE-FNSP"
 (NIL NIL (SYMBOL-LISTP) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::UNTOUCHABLE-VARSP"
 (NIL NIL (SYMBOL-LISTP) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::NEVER-IRRELEVANT-FNS-ALISTP"
 (NIL NIL NIL (AND) NIL NIL NIL)
 (NIL NIL (SYMBOL-ALISTP) (SUBSETP-EQ) NIL NIL NIL)
 ((VAL) NIL (STRIP-CDRS QUOTE) NIL NIL NIL NIL) ((VAL) NIL NIL (T) NIL NIL NIL)
 ((NIL :BOTH) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-DEFINED-HEREDITARILY-CONSTRAINED-FNSP"
 (NIL NIL NIL (PSEUDO-FUNCTION-SYMBOL-LISTP) NIL NIL NIL)
 ((VAL NIL) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::WORLD-GLOBALSP"
 (NIL NIL (SYMBOL-LISTP) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::LAMBDA$-ALISTP"
 (NIL NIL (ALISTP) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::LOOP$-ALISTP"
 (NIL NIL (ALISTP) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::COMMON-LISP-COMPLIANT-LAMBDASP"
 (NIL NIL (TRUE-LISTP) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-LOOP-STOPPER-ELEMENTP"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((X) NIL ((VAR1 VAR2 . FNS) &) NIL NIL NIL NIL)
 ((NIL) NIL NIL NIL (AND) NIL NIL)
 (NIL NIL (SYMBOLP SYMBOLP) (PSEUDO-FUNCTION-SYMBOL-LISTP) NIL NIL NIL)
 ((VAR1 VAR2 FNS NIL) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-LOOP-STOPPERP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM X) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) (AND) NIL NIL NIL)
 ((X) NIL
  (PSEUDO-LOOP-STOPPER-ELEMENTP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::NIL-OR-NAT-LISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM X) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) (AND) NIL NIL NIL)
 ((X) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (OR) NIL NIL NIL)
 (NIL NIL (NULL NATP CDR) NIL NIL NIL NIL) ((X) NIL (CAR CAR) NIL NIL NIL NIL)
 ((X X) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-MATCH-FREEP"
 (NIL NIL NIL NIL (OR) NIL NIL) (NIL NIL (NULL) (EQ EQ) NIL NIL NIL)
 ((X X :ONCE X :ALL) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-REWRITE-QUOTED-CONSTANT-RULEP"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((X) NIL
  (('REWRITE-RULE RUNE NUME HYPS EQUIV LHS RHS SUBCLASS HEURISTIC-INFO
    BACKCHAIN-LIMIT-LST VAR-INFO . MATCH-FREE)
   &)
  NIL NIL NIL NIL)
 ((NIL) NIL NIL (COND) NIL NIL NIL)
 (NIL NIL ((EQ SUBCLASS 'REWRITE-QUOTED-CONSTANT) T) NIL NIL NIL NIL)
 ((NIL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL
  (PSEUDO-RUNEP PSEUDO-NUMEP PSEUDO-TERM-LISTP PSEUDO-TERMP PSEUDO-TERMP CONSP
   INTEGERP PSEUDO-LOOP-STOPPERP BOOLEANP PSEUDO-MATCH-FREEP)
  (PSEUDO-FUNCTION-SYMBOLP <= <= OR) NIL NIL NIL)
 ((RUNE NUME HYPS EQUIV LHS RHS HEURISTIC-INFO VAR-INFO MATCH-FREE) (2 1 3)
  (CAR CAR CAR CDR NULL NIL-OR-NAT-LISTP) NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-REWRITE-QUOTED-CONSTANT-RULESP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM X) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) (AND) NIL NIL NIL)
 ((X) NIL
  (PSEUDO-REWRITE-QUOTED-CONSTANT-RULEP
   ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-EVALUATOR-CHECK-INPUTS-P"
 (NIL NIL (TRUE-LISTP) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::ABSOLUTE-EVENT-NUMBERP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::ABSSTOBJ-INFOP"
 (NIL NIL NIL NIL (AND) NIL NIL)
 (NIL NIL (WEAK-ABSSTOBJ-INFO-P SYMBOLP) (LET) NIL NIL NIL)
 ((VAL (ABSSTOBJ-TUPLES (ACCESS ABSSTOBJ-INFO VAL :ABSSTOBJ-TUPLES))) NIL NIL
  (AND) (ACCESS) NIL NIL)
 ((ABSSTOBJ-INFO VAL :ST$C) NIL (SYMBOL-ALISTP) (LET) NIL NIL NIL)
 ((ABSSTOBJ-TUPLES (CDRS (STRIP-CDRS ABSSTOBJ-TUPLES))) NIL NIL (AND) NIL NIL
  NIL)
 (NIL NIL (SYMBOL-ALISTP) (LET) NIL NIL NIL)
 ((CDRS (CDDRS (STRIP-CDRS CDRS))) NIL NIL (AND) NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::ACCESSOR-NAMESP"
 (NIL NIL NIL (ARRAY1P) NIL NIL NIL) ((SYM VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::ATTACHMENT-PROPERTYP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-BIG-SWITCHP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::TAU-INTERVAL-DOMAINSP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM X) T) NIL NIL NIL NIL)
 (NIL NIL NIL (EQ AND) NIL NIL NIL)
 ((X NIL) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (MEMBER-EQ) NIL NIL
  NIL)
 (NIL NIL (CAR QUOTE CDR) NIL NIL NIL NIL)
 ((X X) NIL NIL NIL (INTEGERP) NIL NIL)
 ((RATIONALP ACL2-NUMBERP NIL) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::TAU-INTERVAL-DOMAINSP-LISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM X) T) NIL NIL NIL NIL)
 (NIL NIL NIL (EQ AND) NIL NIL NIL)
 ((X NIL) NIL (TAU-INTERVAL-DOMAINSP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-BOUNDER-CORRECTNESSP"
 (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL
  (CONSP CONSP CONSP SYMBOLP TAU-INTERVAL-DOMAINSP-LISTP SYMBOLP NAT-LISTP)
  (EQ) NIL NIL NIL)
 ((X SYM) NIL (CAR CDR CAR CDR CAR CAR CDR) NIL NIL NIL NIL)
 ((X X) NIL (CAR CAR CAR CDR CDR) NIL NIL NIL NIL)
 ((X X X X X) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-TAU-BOUNDERSP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM VAL) T) NIL NIL NIL NIL)
 (NIL NIL NIL (EQ AND) NIL NIL NIL)
 ((VAL NIL) NIL NIL
  (PSEUDO-BOUNDER-CORRECTNESSP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL NIL)
 ((SYM SYM) NIL (CAR CDR) NIL NIL NIL NIL) ((VAL VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-TAU-BOUNDERSP-LISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM VAL) T) NIL NIL NIL NIL)
 (NIL NIL NIL (EQ AND) NIL NIL NIL)
 ((VAL NIL) NIL NIL
  (PSEUDO-TAU-BOUNDERSP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL)
 ((SYM SYM) NIL (CAR CDR) NIL NIL NIL NIL) ((VAL VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::CLASSESP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::CLASSICALPP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::CLAUSE-PROCESSORP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::COARSENINGSP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::CONCRETE-STOBJP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-CONGRUENCE-RULEP"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((X) NIL ((NUME EQUIV . RUNE) &) NIL NIL NIL NIL)
 ((NIL) NIL NIL NIL (AND) NIL NIL)
 (NIL NIL (PSEUDO-NUMEP PSEUDO-RUNEP) (PSEUDO-FUNCTION-SYMBOLP) NIL NIL NIL)
 ((NUME EQUIV RUNE) (2) NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-CONGRUENCE-RULE-LISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM X) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) (AND) NIL NIL NIL)
 ((X) NIL (PSEUDO-CONGRUENCE-RULEP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-CONGRUENCE-RULE-LIST-LISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM X) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) (AND) NIL NIL NIL)
 ((X) NIL
  (PSEUDO-CONGRUENCE-RULE-LISTP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-CONGRUENCE-TUPLEP"
 (NIL NIL NIL (OR) NIL NIL NIL) (NIL NIL (NULL) NIL (AND) NIL NIL)
 ((X) NIL (CONSP PSEUDO-CONGRUENCE-RULE-LIST-LISTP) (PSEUDO-FUNCTION-SYMBOLP)
  NIL NIL NIL)
 ((X) (2) (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-CONGRUENCE-TUPLE-LISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM X) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) (AND) NIL NIL NIL)
 ((X) NIL (PSEUDO-CONGRUENCE-TUPLEP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::CONGRUENCESP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-PEQUIV-PATTERN-P"
 (NIL NIL NIL (OR) NIL NIL NIL) (NIL NIL (LEGAL-VARIABLEP) NIL NIL NIL NIL)
 ((P) NIL
  (WEAK-PEQUIV-PATTERN-P SYMBOLP PSEUDO-TERM-LISTP PSEUDO-TERM-LISTP
                         ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  (EQL) NIL NIL NIL)
 ((P) NIL (1+) NIL (ACCESS ACCESS ACCESS ACCESS ACCESS) NIL NIL)
 ((PEQUIV-PATTERN P :FN PEQUIV-PATTERN P :PRE-REV PEQUIV-PATTERN P :POST
   PEQUIV-PATTERN P :POSN PEQUIV-PATTERN P :NEXT)
  NIL (LENGTH) NIL NIL NIL NIL)
 (NIL NIL NIL NIL (ACCESS) NIL NIL)
 ((PEQUIV-PATTERN P :PRE-REV) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-PEQUIV-P"
 (NIL NIL NIL NIL NIL (AND) NIL)
 (NIL NIL
  (WEAK-PEQUIV-P PSEUDO-PEQUIV-PATTERN-P ALISTP PSEUDO-CONGRUENCE-RULEP) NIL
  NIL NIL NIL)
 ((X) NIL NIL NIL (ACCESS ACCESS ACCESS) NIL NIL)
 ((PEQUIV X :PATTERN PEQUIV X :UNIFY-SUBST PEQUIV X :CONGRUENCE-RULE) NIL NIL
  NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-PEQUIV-LISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM LST) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) (AND) NIL NIL NIL)
 ((LST) NIL (PSEUDO-PEQUIV-P ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((LST LST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-PEQUIV-ALISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM ALIST) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) NIL NIL (AND) NIL)
 ((ALIST) NIL
  (CONSP SYMBOLP PSEUDO-PEQUIV-LISTP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 (NIL NIL (CAR CAAR CDAR CDR) NIL NIL NIL NIL)
 ((ALIST ALIST ALIST ALIST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PEQUIVSP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::CONGRUENT-STOBJ-REPP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::CONST-PROPERTYP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-CONSTRAINEDPP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::CONSTRAINT-LSTP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-CONTROLLER-ALISTP"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL
  ((ATOM ALIST)
   (AND (CONSP (CAR ALIST)) (PSEUDO-FUNCTION-SYMBOLP (CAAR ALIST) NIL)
        (BOOLEAN-LISTP (CDAR ALIST)))
   T)
  NIL NIL NIL NIL)
 ((NIL) NIL (NULL ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL NIL NIL)
 ((ALIST) NIL (CDR) NIL NIL NIL NIL) ((ALIST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-DEF-BODYP"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((X) NIL
  (((NUME HYP . CONCL) EQUIV RECURSIVEP FORMALS RUNE . CONTROLLER-ALIST) &) NIL
  NIL NIL NIL)
 ((NIL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL
  (PSEUDO-NUMEP PSEUDO-TERMP PSEUDO-ARGLISTP PSEUDO-RUNEP
   PSEUDO-CONTROLLER-ALISTP)
  (OR AND PSEUDO-FUNCTION-SYMBOL-LISTP) NIL NIL NIL)
 ((NUME CONCL EQUIV RECURSIVEP NIL FORMALS RUNE CONTROLLER-ALIST) NIL
  (NULL PSEUDO-TERMP SYMBOLP) NIL NIL NIL NIL)
 ((HYP HYP EQUIV) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-DEF-BODY-LISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM X) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) (AND) NIL NIL NIL)
 ((X) NIL (PSEUDO-DEF-BODYP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-DEF-BODIESP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::DEFAXIOM-SUPPORTERP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-DEFCHOOSE-AXIOMP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-ELIM-RULEP"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((X) NIL
  (('ELIM-RULE ((NUME . CRUCIAL-POSITION) DESTRUCTOR-TERM . DESTRUCTOR-TERMS)
    (HYPS . EQUIV) (LHS . RHS) . RUNE)
   &)
  NIL NIL NIL NIL)
 ((NIL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL
  (PSEUDO-NUMEP NATP PSEUDO-TERMP PSEUDO-TERM-LISTP PSEUDO-TERM-LISTP
   PSEUDO-TERMP SYMBOLP PSEUDO-RUNEP CONSP)
  (PSEUDO-FUNCTION-SYMBOLP < EQUAL) NIL NIL NIL)
 ((NUME CRUCIAL-POSITION DESTRUCTOR-TERM DESTRUCTOR-TERMS HYPS EQUIV LHS RHS
   RUNE DESTRUCTOR-TERM CRUCIAL-POSITION RHS)
  (2) (LEN) (NTH) NIL NIL NIL)
 ((CRUCIAL-POSITION) NIL (CDR CDR) NIL NIL NIL NIL)
 ((DESTRUCTOR-TERM DESTRUCTOR-TERM) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-ELIMINATE-DESTRUCTORS-RULES"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-FORMALSP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-FORWARD-CHAINING-RULEP"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((X) NIL
  (('FORWARD-CHAINING-RULE (RUNE . NUME) TRIGGER HYPS CONCLS . MATCH-FREE) &)
  NIL NIL NIL NIL)
 ((NIL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL
  (PSEUDO-RUNEP PSEUDO-NUMEP PSEUDO-TERMP PSEUDO-TERM-LISTP PSEUDO-TERM-LISTP
   PSEUDO-MATCH-FREEP)
  NIL NIL NIL NIL)
 ((RUNE NUME TRIGGER HYPS CONCLS MATCH-FREE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-FORWARD-CHAINING-RULE-LISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM X) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) (AND) NIL NIL NIL)
 ((X) NIL
  (PSEUDO-FORWARD-CHAINING-RULEP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-FORWARD-CHAINING-RULESP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::STOBJ-LISTP"
 (NIL NIL NIL (X) NIL NIL NIL) ((KNOWN-STOBJS W) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::GLOBAL-STOBJS-P"
 (NIL NIL (VAL) NIL NIL NIL NIL) ((W) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-GLOBAL-VALUEP"
 (NIL NIL NIL (SYM) NIL NIL NIL) ((VAL W) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-GUARDP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-HEREDITARILY-CONSTRAINED-FNNAMESP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-INDUCTION-MACHINEP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-INDUCTION-RULEP"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((X) NIL (('INDUCTION-RULE NUME (PATTERN . CONDITION) SCHEME . RUNE) &) NIL
  NIL NIL NIL)
 ((NIL) NIL NIL NIL NIL NIL (AND))
 (NIL NIL
  (PSEUDO-NUMEP PSEUDO-TERMP PSEUDO-TERM-LISTP PSEUDO-TERMP PSEUDO-RUNEP) NIL
  NIL NIL NIL)
 ((NUME PATTERN CONDITION SCHEME RUNE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-INDUCTION-RULE-LISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM X) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) (AND) NIL NIL NIL)
 ((X) NIL (PSEUDO-INDUCTION-RULEP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-INDUCTION-RULESP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-RULER-EXTENDERSP"
 (NIL NIL NIL (OR) NIL NIL NIL)
 (NIL NIL NIL (EQ PSEUDO-FUNCTION-SYMBOL-LISTP) NIL NIL NIL)
 ((X :ALL X NIL) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-JUSTIFICATIONP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::LABELP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-REWRITE-RULEP"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((X) NIL
  (('REWRITE-RULE RUNE NUME HYPS EQUIV LHS RHS SUBCLASS HEURISTIC-INFO
    BACKCHAIN-LIMIT-LST VAR-INFO . MATCH-FREE)
   &)
  NIL NIL NIL NIL)
 ((NIL) NIL NIL NIL NIL NIL NIL)
 ((SUBCLASS) NIL (BACKCHAIN ABBREVIATION META DEFINITION OTHERWISE) NIL NIL NIL
  NIL)
 ((NIL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL
  (PSEUDO-RUNEP PSEUDO-NUMEP PSEUDO-TERM-LISTP PSEUDO-TERMP PSEUDO-TERMP
   PSEUDO-LOOP-STOPPERP BOOLEANP PSEUDO-MATCH-FREEP PSEUDO-RUNEP PSEUDO-NUMEP
   NULL PSEUDO-TERMP PSEUDO-TERMP NULL NULL BOOLEANP NULL PSEUDO-RUNEP
   PSEUDO-NUMEP NULL PSEUDO-RUNEP PSEUDO-NUMEP PSEUDO-TERM-LISTP PSEUDO-TERMP
   PSEUDO-TERMP NULL INTEGER-LISTP NULL)
  (PSEUDO-FUNCTION-SYMBOLP OR PSEUDO-FUNCTION-SYMBOLP OR
   PSEUDO-FUNCTION-SYMBOLP PSEUDO-FUNCTION-SYMBOLP OR OR OR
   PSEUDO-FUNCTION-SYMBOLP)
  (AND) NIL NIL)
 ((RUNE NUME HYPS EQUIV LHS RHS HEURISTIC-INFO VAR-INFO MATCH-FREE RUNE NUME
   HYPS EQUIV LHS RHS HEURISTIC-INFO BACKCHAIN-LIMIT-LST VAR-INFO MATCH-FREE
   RUNE NUME EQUIV LHS MATCH-FREE RUNE NUME HYPS EQUIV LHS RHS
   BACKCHAIN-LIMIT-LST VAR-INFO MATCH-FREE)
  (2 2 2 1 2)
  (NULL NIL-OR-NAT-LISTP NULL NULL NULL WELL-FORMEDNESS-GUARANTEEP NULL NATP
        CONSP PSEUDO-CONTROLLER-ALISTP)
  (PSEUDO-FUNCTION-SYMBOLP EQ PSEUDO-FUNCTION-SYMBOL-LISTP) NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-REWRITE-RULE-LISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM X) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) (AND) NIL NIL NIL)
 ((X) NIL (PSEUDO-REWRITE-RULEP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-LEMMASP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::LEVEL-NOP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-LINEAR-LEMMAP"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((X) NIL
  (('LINEAR-LEMMA (NUME . HYPS) MAX-TERM CONCL BACKCHAIN-LIMIT-LST RUNE
    . MATCH-FREE)
   &)
  NIL NIL NIL NIL)
 ((NIL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL
  (PSEUDO-NUMEP PSEUDO-TERM-LISTP PSEUDO-TERMP PSEUDO-TERMP PSEUDO-RUNEP
   PSEUDO-MATCH-FREEP)
  (OR) NIL NIL NIL)
 ((NUME HYPS MAX-TERM CONCL RUNE MATCH-FREE) NIL (NULL NIL-OR-NAT-LISTP) NIL
  NIL NIL NIL)
 ((BACKCHAIN-LIMIT-LST BACKCHAIN-LIMIT-LST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-LINEAR-LEMMA-LISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM X) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) (AND) NIL NIL NIL)
 ((X) NIL (PSEUDO-LINEAR-LEMMAP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-LINEAR-LEMMASP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::LOOP$-RECURSIONP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::HINT-FOR-MACRO-ARGLIST-KEYSP"
 (NIL NIL NIL (ARGS) NIL NIL NIL) ((PASSED1 PASSED2) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-MACRO-ARGLIST-MSGP"
 (NIL NIL NIL (AND) NIL NIL NIL)
 (NIL NIL (MACRO-ARGS-STRUCTUREP PSEUDO-ARGLISTP) NIL NIL NIL NIL)
 ((ARGS) NIL (MACRO-VARS) NIL NIL NIL NIL) ((ARGS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-MACRO-ARGSP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-MACRO-BODYP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-NEG-IMPLICANTSP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::NON-EXECUTABLEPP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::NON-MEMOIZABLEP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-POS-IMPLICANTSP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PREDEFINEDP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PRIMITIVE-RECURSIVE-DEFUNPP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-QUICK-BLOCK-INFO-LISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM LST) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) (AND) NIL NIL NIL)
 ((LST) NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) (MEMBER-EQ) NIL NIL NIL)
 (NIL NIL (CAR QUOTE CDR) NIL NIL NIL NIL)
 ((LST LST) NIL NIL (QUESTIONABLE) NIL NIL NIL)
 ((UNCHANGING SELF-REFLEXIVE) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-QUICK-BLOCK-INFOP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-RECOGNIZER-TUPLEP"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((X) NIL ((!FN (NUME . TRUE-TS) (FALSE-TS . STRONGP) . RUNE) &) NIL NIL NIL
  NIL)
 ((NIL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL (TYPE-SETP TYPE-SETP BOOLEANP PSEUDO-RUNEP)
  (PSEUDO-FUNCTION-SYMBOLP OR) NIL NIL NIL)
 ((FN TRUE-TS FALSE-TS STRONGP RUNE) (1) (NULL PSEUDO-NUMEP) NIL NIL NIL NIL)
 ((NUME NUME) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-RECOGNIZER-ALISTP"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL (ATOM NULL) (AND) NIL NIL NIL)
 ((X X) NIL NIL
  (PSEUDO-RECOGNIZER-TUPLEP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL)
 ((FN FN) NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-RECURSIVEPP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::REDEFINEDP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-INTEGER-BOUNDP"
 (NIL NIL NIL NIL (OR) NIL NIL) (NIL NIL (INTEGERP) (EQ) (AND) NIL NIL)
 ((X X) NIL (QUOTE CONSP INTEGERP NULL) NIL NIL NIL NIL)
 ((* X) NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-RATIONAL-BOUNDP"
 (NIL NIL NIL NIL (OR) NIL NIL) (NIL NIL (INTEGERP) (EQ) (AND) NIL NIL)
 ((X X) NIL (QUOTE CONSP RATIONALP NULL) NIL NIL NIL NIL)
 ((* X) NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-TYPE-SPECP"
 (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL
  ((OR (EQ X 'INTEGER) (EQ X 'SIGNED-BYTE))
   (AND (CONSP X) (EQ (CAR X) 'INTEGER) (TRUE-LISTP X) (EQUAL (LENGTH X) 3))
   (EQ X 'RATIONAL) (EQ X 'REAL) (EQ X 'COMPLEX)
   (AND (CONSP X) (OR (EQ (CAR X) 'RATIONAL) (EQ (CAR X) 'REAL)) (TRUE-LISTP X)
        (EQUAL (LENGTH X) 3))
   (EQ X 'BIT)
   (AND (CONSP X) (EQ (CAR X) 'MOD) (TRUE-LISTP X) (EQUAL (LENGTH X) 2)
        (INTEGERP (CADR X)))
   (AND (CONSP X) (EQ (CAR X) 'SIGNED-BYTE) (TRUE-LISTP X) (EQUAL (LENGTH X) 2)
        (INTEGERP (CADR X)) (> (CADR X) 0))
   (EQ X 'UNSIGNED-BYTE)
   (AND (CONSP X) (EQ (CAR X) 'UNSIGNED-BYTE) (TRUE-LISTP X)
        (EQUAL (LENGTH X) 2) (INTEGERP (CADR X)) (> (CADR X) 0))
   (EQ X 'ATOM) (EQ X 'CHARACTER) (EQ X 'CONS) (EQ X 'LIST) (EQ X 'NIL)
   (EQ X 'NULL) (EQ X 'RATIO) (EQ X 'STANDARD-CHAR) (EQ X 'STRING)
   (AND (CONSP X) (EQ (CAR X) 'STRING) (TRUE-LISTP X) (EQUAL (LENGTH X) 2)
        (INTEGERP (CADR X)) (>= (CADR X) 0))
   (EQ X 'SYMBOL) (EQ X 'T) (WEAK-SATISFIES-TYPE-SPEC-P X)
   (AND (CONSP X) (EQ (CAR X) 'MEMBER) (EQLABLE-LISTP (CDR X))) T)
  NIL NIL NIL NIL)
 ((T T T T T T T T T T T T T T T T T T T T T T T NIL) NIL NIL (AND AND) NIL NIL
  NIL)
 (NIL NIL
  (PSEUDO-INTEGER-BOUNDP PSEUDO-INTEGER-BOUNDP PSEUDO-RATIONAL-BOUNDP
   PSEUDO-RATIONAL-BOUNDP)
  NIL NIL NIL NIL)
 (NIL NIL (CADR CADDR CADR CADDR) NIL NIL NIL NIL)
 ((X X X X) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-ARRAY1-TYPE-SPECP"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((X) NIL (('ARRAY TYPE-SPEC (MAX)) &) NIL NIL NIL NIL)
 ((NIL) NIL NIL (AND) NIL NIL NIL)
 (NIL NIL (PSEUDO-TYPE-SPECP NATP) NIL NIL NIL NIL)
 ((TYPE-SPEC MAX) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-STOBJ-FIELD-DESCRIPTOR-KEYWORD-PAIRP"
 (NIL NIL NIL NIL NIL (COND) NIL)
 (NIL NIL ((EQ KEY :TYPE) (EQ KEY :INITIALLY) (EQ KEY :RESIZABLE) T) NIL NIL
  NIL NIL)
 ((T NIL) NIL (BOOLEANP) (OR) NIL NIL NIL)
 ((VAL) NIL (PSEUDO-TYPE-SPECP PSEUDO-ARRAY1-TYPE-SPECP) NIL NIL NIL NIL)
 ((VAL VAL) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-STOBJ-FIELD-DESCRIPTOR-KEYWORD-ALISTP"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL ((ATOM X) (ATOM (CDR X)) T) NIL NIL NIL NIL)
 ((T NIL) NIL NIL (AND) NIL NIL NIL)
 (NIL NIL (ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  (PSEUDO-STOBJ-FIELD-DESCRIPTOR-KEYWORD-PAIRP) NIL NIL NIL)
 (NIL NIL (CAR CADR CDDR) NIL NIL NIL NIL) ((X X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-STOBJ-FIELD-DESCRIPTORP"
 (NIL NIL NIL (OR) NIL NIL NIL)
 (NIL NIL NIL (PSEUDO-FUNCTION-SYMBOLP) NIL (AND) NIL)
 ((X NIL) NIL (TRUE-LISTP CONSP PSEUDO-STOBJ-FIELD-DESCRIPTOR-KEYWORD-ALISTP)
  (PSEUDO-FUNCTION-SYMBOLP) NIL NIL NIL)
 ((X X NIL) NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-STOBJ-FIELD-DESCRIPTOR-LISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM X) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) (AND) NIL NIL NIL)
 ((X) NIL
  (PSEUDO-STOBJ-FIELD-DESCRIPTORP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-DOUBLET-STYLE-RENAMING-ALISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM X) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) NIL NIL NIL NIL)
 ((X) NIL
  (CONSP SYMBOLP CONSP SYMBOLP NULL ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 (NIL NIL (CAR CAR CDR CADR CDDR CDR) NIL NIL NIL NIL)
 ((X X) NIL (CAR CAR CAR CAR) NIL NIL NIL NIL)
 ((X X X X) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-REDUNDANCY-BUNDLEP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-RUNIC-MAPPING-PAIRS-LISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM X) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) NIL NIL (AND) NIL)
 ((X) NIL
  (CONSP PSEUDO-NUMEP PSEUDO-RUNEP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 (NIL NIL (CAR CAR CDR CDR) NIL NIL NIL NIL)
 ((X X) NIL (CAR CAR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-RUNIC-MAPPING-PAIRSP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::SIBLINGS-PROPERTYP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-SIGNATUREP"
 (NIL NIL NIL NIL (AND) NIL NIL) (NIL NIL (TRUE-LISTP) (EQUAL LET) NIL NIL NIL)
 ((X) (4) (LEN) NIL ((INPUTS-TAU-LIST (NTH 0 X))) NIL NIL)
 ((X) NIL
  (VARS-AND-DEPENDENT-HYPS OUTPUT-SIGN OUTPUT-RECOG PSEUDO-TAUP-LISTP CONSP
   SYMBOL-LISTP NO-DUPLICATESP-EQ PSEUDO-TERM-LISTP BOOLEANP)
  (OR) NIL NIL NIL)
 ((INPUTS-TAU-LIST VARS-AND-DEPENDENT-HYPS OUTPUT-SIGN) NIL
  (CAR CAR CDR PSEUDO-EVG-SINGLETONP) (NTH NTH NTH PSEUDO-TAU-PAIRP) NIL NIL
  NIL)
 ((X X X VARS-AND-DEPENDENT-HYPS VARS-AND-DEPENDENT-HYPS
   VARS-AND-DEPENDENT-HYPS NIL OUTPUT-RECOG OUTPUT-RECOG)
  (1 2 3) NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-SIGNATUREP-LISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM X) T) NIL NIL NIL NIL)
 (NIL NIL NIL (EQUAL AND) NIL NIL NIL)
 ((X NIL) NIL (PSEUDO-SIGNATUREP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL
  NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-SIGNATURE-RULES-FORM-1P"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-SIGNATUREP-LISTP-LISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM X) T) NIL NIL NIL NIL)
 (NIL NIL NIL (EQUAL AND) NIL NIL NIL)
 ((X NIL) NIL
  (PSEUDO-SIGNATUREP-LISTP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL) NIL NIL
  NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-SIGNATURE-RULES-FORM-2P"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-SPLIT-TYPES-TERMP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-INVARIANT-RISKP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-STOBJP"
 (NIL NIL NIL NIL (IF) NIL NIL) (NIL NIL NIL (EQ EQUAL OR) NIL NIL NIL)
 ((SYM VAL) NIL (QUOTE QUOTE NULL WEAK-STOBJ-PROPERTY-P) NIL NIL NIL NIL)
 ((STATE *THE-LIVE-STATE* VAL VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-STOBJ-CONSTANTP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-STOBJ-FUNCTIONP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-STOBJ-LIVE-VARP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-STOBJS-INP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-STOBJS-OUTP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::SYMBOL-CLASSP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::TABLE-ALISTP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-TABLE-GUARDP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-THEOREMP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-THEORYP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((LST) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-TYPE-PRESCRIPTIONP"
 (NIL NIL NIL NIL (CASE-MATCH) NIL NIL)
 ((X) NIL
  ((BASIC-TS (NUME . TERM) (HYPS . BACKCHAIN-LIMIT-LST) (VARS . RUNE)
    . COROLLARY)
   &)
  NIL NIL NIL NIL)
 ((NIL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL
  (TYPE-SETP PSEUDO-TERMP PSEUDO-TERM-LISTP SYMBOL-LISTP PSEUDO-RUNEP
   PSEUDO-TERMP)
  (OR OR) NIL NIL NIL)
 ((BASIC-TS TERM HYPS VARS RUNE COROLLARY) NIL (NULL PSEUDO-NUMEP NULL) (AND)
  NIL NIL NIL)
 ((NUME NUME BACKCHAIN-LIMIT-LST) NIL (BACKCHAIN-LIMIT-LISTP) (EQUAL) NIL NIL
  NIL)
 ((BACKCHAIN-LIMIT-LST) NIL (LENGTH LENGTH) NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-TYPE-PRESCRIPTION-LISTP"
 (NIL NIL NIL (COND) NIL NIL NIL) (NIL NIL ((ATOM X) T) NIL NIL NIL NIL)
 (NIL NIL (NULL) (AND) NIL NIL NIL)
 ((X) NIL (PSEUDO-TYPE-PRESCRIPTIONP ACL2ML-COMPLETE-ORIGINAL::RECURSIVE-CALL)
  NIL NIL NIL NIL)
 (NIL NIL (CAR CDR) NIL NIL NIL NIL) ((X X) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-TYPE-PRESCRIPTIONSP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-UNEVALABLE-BUT-KNOWNP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::UNNORMALIZED-BODYP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::UNTRANSLATED-THEOREMP"
 (NIL NIL (SYM) NIL NIL NIL NIL) ((VAL) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-GOOD-WORLD-TRIPLEP"
 (NIL NIL NIL (TRIP) NIL NIL NIL) ((W REDEFP) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-GOOD-WORLDP2"
 (NIL NIL NIL (POS) NIL NIL NIL) ((W REDEFP) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-GOOD-WORLDP1"
 (NIL NIL (W) NIL NIL NIL NIL) ((REDEFP) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::GOOD-COMMAND-BLOCKSP1"
 (NIL NIL NIL NIL (POS) NIL NIL)
 ((JUST-ENTERED-COMMAND-BLOCKP NO-EVENT-LANDMARK-YETP W) NIL NIL NIL NIL NIL
  NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::GOOD-COMMAND-BLOCKSP"
 ((W) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::SEQUENTIAL-EVENT-LANDMARKSP1"
 (NIL NIL NIL (POS) NIL NIL NIL) ((N W) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::SEQUENTIAL-EVENT-LANDMARKSP"
 ((W) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::SEQUENTIAL-COMMAND-LANDMARKSP1"
 (NIL NIL NIL (POS) NIL NIL NIL) ((N W) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::SEQUENTIAL-COMMAND-LANDMARKSP"
 ((W) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/system/pseudo-good-worldp.lisp::PSEUDO-GOOD-WORLDP"
 (NIL NIL NIL NIL NIL NIL (AND))
 (NIL NIL
  (PLIST-WORLDP SEQUENTIAL-EVENT-LANDMARKSP SEQUENTIAL-COMMAND-LANDMARKSP
                GOOD-COMMAND-BLOCKSP)
  NIL (PSEUDO-GOOD-WORLDP2) NIL NIL)
 ((W W REDEFP W W W) (0) NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
