("/home/acl2/books/kestrel/utilities/er-soft-plus.lisp::ERROR1+"
 (NIL NIL NIL NIL NIL NIL (CTX))
 ((ERP VAL STR ALIST STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
