("/home/acl2/books/arithmetic-3/bind-free/mini-theories.lisp::(- x)"
 (NIL NIL NIL (EQUAL) NIL NIL NIL) (NIL NIL (-) (*) NIL NIL NIL)
 ((X X) (-1) NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/bind-free/mini-theories.lisp::(/ x)"
 (NIL NIL NIL (EQUAL) NIL NIL NIL) (NIL NIL (/) (EXPT) NIL NIL NIL)
 ((X X) (-1) NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/bind-free/mini-theories.lisp::REWRITE-LINEAR-EQUALITIES-TO-IFF"
 (NIL NIL NIL (EQUAL) NIL NIL NIL) (NIL NIL NIL (EQUAL IFF) NIL NIL NIL)
 (NIL NIL NIL (< < < <) NIL NIL NIL)
 ((W X Y Z W X Y Z) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/bind-free/mini-theories.lisp::EXPT-TYPE-PRESCRIPTION-NEGATIVE-BASE-EVEN-EXPONENT"
 (NIL NIL NIL (IMPLIES) NIL NIL NIL) (NIL NIL NIL (<) NIL (AND) NIL)
 (NIL (0) (RATIONALP INTEGERP INTEGERP) (< EXPT) NIL NIL NIL)
 ((R R I R I) (0) NIL (*) NIL NIL NIL) ((1/2 I) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/bind-free/mini-theories.lisp::EXPT-TYPE-PRESCRIPTION-NEGATIVE-BASE-ODD-EXPONENT"
 (NIL NIL NIL (IMPLIES) NIL NIL NIL) (NIL NIL NIL (<) NIL (AND) NIL)
 (NIL (0) (RATIONALP INTEGERP NOT) (< EXPT) NIL NIL NIL)
 ((R R I R I) (0) (INTEGERP) NIL NIL NIL NIL) (NIL NIL NIL (*) NIL NIL NIL)
 ((1/2 I) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/bind-free/mini-theories.lisp::EXPT-TYPE-PRESCRIPTION-NONPOSITIVE-BASE-EVEN-EXPONENT"
 (NIL NIL NIL (IMPLIES) NIL NIL NIL) (NIL NIL NIL (<=) NIL (AND) NIL)
 (NIL (0) (RATIONALP INTEGERP INTEGERP) (<= EXPT) NIL NIL NIL)
 ((R R I R I) (0) NIL (*) NIL NIL NIL) ((1/2 I) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/bind-free/mini-theories.lisp::EXPT-TYPE-PRESCRIPTION-NONPOSITIVE-BASE-ODD-EXPONENT"
 (NIL NIL NIL (IMPLIES) NIL NIL NIL) (NIL NIL NIL (<=) NIL (AND) NIL)
 (NIL (0) (RATIONALP INTEGERP NOT) (<= EXPT) NIL NIL NIL)
 ((R R I R I) (0) (INTEGERP) NIL NIL NIL NIL) (NIL NIL NIL (*) NIL NIL NIL)
 ((1/2 I) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/bind-free/mini-theories.lisp::EXPT-NEGATIVE-BASE-EVEN-EXPONENT"
 (NIL NIL NIL (IMPLIES) NIL NIL NIL) (NIL NIL NIL (EQUAL) (AND) NIL NIL)
 (NIL NIL (RATIONALP INTEGERP INTEGERP) (EXPT EXPT) NIL NIL NIL)
 ((R I I R I) NIL NIL (* *) NIL NIL NIL) ((1/2 I R) (-1) NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/bind-free/mini-theories.lisp::EXPT-NEGATIVE-BASE-ODD-EXPONENT"
 (NIL NIL NIL (IMPLIES) NIL NIL NIL) (NIL NIL NIL (EQUAL) (AND) NIL NIL)
 (NIL NIL (RATIONALP INTEGERP NOT) (EXPT *) NIL NIL NIL)
 ((R I I) (-1) (INTEGERP) (* EXPT) NIL NIL NIL)
 ((R R I) (-1) NIL (*) NIL NIL NIL) ((1/2 I) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
