("/home/acl2/books/arithmetic-3/bind-free/integerp-meta.lisp::INTP-+"
 (NIL NIL (X) NIL NIL NIL NIL) ((Y) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/bind-free/integerp-meta.lisp::INTP-*"
 (NIL NIL (X) NIL NIL NIL NIL) ((Y) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/bind-free/integerp-meta.lisp::INTP-1"
 (NIL NIL NIL (IMPLIES) NIL NIL NIL) (NIL NIL (INTEGERP) (AND) NIL NIL NIL)
 (NIL NIL (INTEGERP INTEGERP) (INTP-*) NIL NIL NIL)
 ((X Y X Y) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/bind-free/integerp-meta.lisp::INTP-2"
 (NIL NIL NIL (IMPLIES) NIL NIL NIL) (NIL NIL (INTEGERP) (AND) NIL NIL NIL)
 (NIL NIL (INTEGERP INTEGERP) (INTP-+) NIL NIL NIL)
 ((X Y X Y) NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/bind-free/integerp-meta.lisp::NINTP-1"
 (NIL NIL NIL (IMPLIES) NIL NIL NIL) (NIL NIL (NOT) NIL (AND) NIL NIL)
 (NIL NIL (ACL2-NUMBERP NOT INTEGERP INTEGERP) NIL NIL NIL NIL)
 ((X Y) NIL (INTEGERP) (INTP-+) NIL NIL NIL) ((X X Y) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/bind-free/integerp-meta.lisp::NINTP-2"
 (NIL NIL NIL (IMPLIES) NIL NIL NIL) (NIL NIL (NOT) NIL (AND) NIL NIL)
 (NIL NIL (INTEGERP ACL2-NUMBERP NOT INTEGERP) NIL NIL NIL NIL)
 ((X Y) NIL (INTEGERP) (INTP-+) NIL NIL NIL) ((Y X Y) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/bind-free/integerp-meta.lisp::LEAVES"
 (NIL NIL (TERM) NIL NIL NIL NIL) ((BIN-OP) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/bind-free/integerp-meta.lisp::TREE"
 (NIL NIL (LEAVES) NIL NIL NIL NIL) ((BIN-OP) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/bind-free/integerp-meta.lisp::BIG-TREE"
 (NIL NIL NIL (BAGS) NIL NIL NIL) ((BIG-BIN-OP BIN-OP) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/bind-free/integerp-meta.lisp::BAG-LEAVES"
 (NIL NIL NIL NIL NIL (LEAVES) NIL)
 ((MFC STATE INTP-BAGS NON-INTP-BAGS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/bind-free/integerp-meta.lisp::BAG-TERMS"
 (NIL NIL NIL NIL (TYPE-ALIST) NIL NIL)
 ((BIN-OP INTP-BAGS NON-INTP-BAGS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/bind-free/integerp-meta.lisp::SUBTRACT-LEAF"
 (NIL NIL (LEAF) NIL NIL NIL NIL) ((LEAVES) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/bind-free/integerp-meta.lisp::SUBTRACT-BAG"
 (NIL NIL (BAG) NIL NIL NIL NIL) ((LEAVES) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/bind-free/integerp-meta.lisp::COLLECT-BAGS-INTP"
 (NIL NIL (LEAVES) NIL NIL NIL NIL) ((INTP-BAGS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/bind-free/integerp-meta.lisp::COLLECT-BAGS-NON-INTP"
 (NIL NIL NIL (LEAVES) NIL NIL NIL)
 ((INTP-BAGS NON-INTP-BAGS) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/bind-free/integerp-meta.lisp::COLLECT-BAGS"
 (NIL NIL NIL NIL (LEAVES) NIL NIL)
 ((INTP-BAGS NON-INTP-BAGS BIN-OP) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
("/home/acl2/books/arithmetic-3/bind-free/integerp-meta.lisp::META-INTEGERP"
 (NIL NIL NIL (TERM) NIL NIL NIL) ((MFC STATE) NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL) (NIL NIL NIL NIL NIL NIL NIL)
 (NIL NIL NIL NIL NIL NIL NIL))
