("/home/acl2/books/arithmetic-3/bind-free/default-hint.lisp::NONLINEARP-DEFAULT-HINT"
 (NIL NIL NIL NIL (COND) NIL NIL)
 (NIL NIL
  (STABLE-UNDER-SIMPLIFICATIONP
   (ACCESS REWRITE-CONSTANT (ACCESS PROVE-SPEC-VAR PSPV :REWRITE-CONSTANT)
    :NONLINEARP)
   T)
  NIL NIL NIL NIL)
 ((NIL) NIL NIL NIL (IF IF) NIL NIL)
 ((NIL NIL) NIL (NOT NOT) (PROG2$ PROG2$) NIL NIL NIL)
 (NIL NIL 'QUOTE (OBSERVATION-CW EQUAL OBSERVATION-CW) (ACCESS) NIL NIL)
 ((REWRITE-CONSTANT :NONLINEARP "We now enable non-linear arithmetic."
   "We now disable non-linear arithmetic.")
  NIL (QUOTE CAAR QUOTE QUOTE) NIL
  (ACCESS :COMPUTED-HINT-REPLACEMENT :COMPUTED-HINT-REPLACEMENT) NIL NIL)
 ((PROVE-SPEC-VAR PSPV :REWRITE-CONSTANT RECURSIVE-CALL T :NONLINEARP T HIST
   SETTLED-DOWN-CLAUSE RECURSIVE-CALL T :NONLINEARP NIL)
  NIL NIL NIL NIL NIL NIL))
